/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#include <phymod/phymod.h>
#include <phymod/phymod.h>
#include <phymod/phymod_dispatch.h>

#ifdef PHYMOD_TSCE_SUPPORT

#include <phymod/chip/tsce.h>

__phymod__dispatch__t__ phymod_tsce_driver = {

    tsce_core_identify,
    tsce_core_info_get,
    tsce_core_lane_map_set,
    tsce_core_lane_map_get,
    tsce_core_reset_set,
    tsce_core_reset_get,
    tsce_core_firmware_info_get,
    tsce_phy_firmware_core_config_set,
    tsce_phy_firmware_core_config_get,
    tsce_phy_firmware_lane_config_set,
    tsce_phy_firmware_lane_config_get,
    tsce_core_pll_sequencer_restart,
    tsce_core_wait_event,
    tsce_phy_rx_restart,
    tsce_phy_polarity_set,
    tsce_phy_polarity_get,
    tsce_phy_tx_set,
    tsce_phy_tx_get,
    tsce_phy_media_type_tx_get,
    tsce_phy_tx_override_set,
    tsce_phy_tx_override_get,
    tsce_phy_rx_set,
    tsce_phy_rx_get,
    tsce_phy_reset_set,
    tsce_phy_reset_get,
    tsce_phy_power_set,
    tsce_phy_power_get,
    tsce_phy_tx_lane_control_set,
    tsce_phy_tx_lane_control_get,
    tsce_phy_rx_lane_control_set,
    tsce_phy_rx_lane_control_get,
    tsce_phy_fec_enable_set,
    tsce_phy_fec_enable_get,
    tsce_phy_interface_config_set,
    tsce_phy_interface_config_get,
    tsce_phy_cl72_set,
    tsce_phy_cl72_get,
    tsce_phy_cl72_status_get,
    tsce_phy_autoneg_ability_set,
    tsce_phy_autoneg_ability_get,
    tsce_phy_autoneg_remote_ability_get,
    tsce_phy_autoneg_set,
    tsce_phy_autoneg_get,
    tsce_phy_autoneg_status_get,
    tsce_core_init,
    tsce_phy_init,
    tsce_phy_loopback_set,
    tsce_phy_loopback_get,
    tsce_phy_rx_pmd_locked_get,
    tsce_phy_link_status_get,
    NULL, /* phymod_phy_status_dump */
    tsce_phy_pcs_userspeed_set,
    tsce_phy_pcs_userspeed_get,
    tsce_phy_reg_read,
    tsce_phy_reg_write,
};

#endif /* PHYMOD_TSCE_SUPPORT */
