/*
 * $Id: 8c3b3b74edb719fe8a0fc2ea81e12442396f1810 $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __SHR_BSLENUM_H__
#define __SHR_BSLENUM_H__

typedef enum bsl_severity_e {
    bslSeverityOff            = 0,
    bslSeverityFatal          = 1,
    bslSeverityError          = 2,
    bslSeverityWarn           = 3,
    bslSeverityInfo           = 4,
    bslSeverityVerbose        = 5,
    bslSeverityDebug          = 6,
    bslSeverityNormal         = bslSeverityInfo,
    bslSeverityCount          = 7
} bsl_severity_t;

#define BSL_SEVERITY_NAMES_INIT { \
    "Off", \
    "Fatal", \
    "Error", \
    "Warn", \
    "Info", \
    "Verbose", \
    "Debug" \
}

typedef enum bsl_layer_e {
    bslLayerAppl              = 0,
    bslLayerBcm               = 1,
    bslLayerBcmx              = 2,
    bslLayerBoard             = 3,
    bslLayerSal               = 4,
    bslLayerSoc               = 5,
    bslLayerSocdnx            = 6,
    bslLayerSys               = 7,
    bslLayerTks               = 8,
    bslLayerCount             = 9
} bsl_layer_t;

#define BSL_LAYER_NAMES_INIT { \
    "APPL", \
    "BCM", \
    "BCMX", \
    "BOARD", \
    "SAL", \
    "SOC", \
    "SOCDNX", \
    "SYS", \
    "TKS"  \
}

typedef enum bsl_source_e {
    bslSource100g             = 0,
    bslSource10g              = 1,
    bslSourceAccessctrllist   = 2,
    bslSourceActioncmd        = 3,
    bslSourceAlpm             = 4,
    bslSourceApi              = 5,
    bslSourceArl              = 6,
    bslSourceArlmon           = 7,
    bslSourceAtp              = 8,
    bslSourceAtpv             = 9,
    bslSourceAttach           = 10,
    bslSourceAuth             = 11,
    bslSourceBfd              = 12,
    bslSourceC2c              = 13,
    bslSourceC2cv             = 14,
    bslSourceCeinstructions   = 15,
    bslSourceCell             = 16,
    bslSourceCes              = 17,
    bslSourceChassis          = 18,
    bslSourceChip             = 19,
    bslSourceCmic             = 20,
    bslSourceCnm              = 21,
    bslSourceCnt              = 22,
    bslSourceCommon           = 23,
    bslSourceCosq             = 24,
    bslSourceCounter          = 25,
    bslSourceCtpkt            = 26,
    bslSourceCtpktv           = 27,
    bslSourceDdr              = 28,
    bslSourceDiag             = 29,
    bslSourceDiagnostics      = 30,
    bslSourceDiscover         = 31,
    bslSourceDiscv            = 32,
    bslSourceDma              = 33,
    bslSourceDram             = 34,
    bslSourceEgress           = 35,
    bslSourceElpm             = 36,
    bslSourceEnd              = 37,
    bslSourceEsemaccess       = 38,
    bslSourceEsm              = 39,
    bslSourceExtender         = 40,
    bslSourceFabric           = 41,
    bslSourceFailover         = 42,
    bslSourceFcoe             = 43,
    bslSourceFlexctr          = 44,
    bslSourceFlowcontrol      = 45,
    bslSourceForward          = 46,
    bslSourceFp               = 47,
    bslSourceFramework        = 48,
    bslSourceGe               = 49,
    bslSourceGeneral          = 50,
    bslSourceHash             = 51,
    bslSourceHeaders          = 52,
    bslSourceHwdebug          = 53,
    bslSourceI2c              = 54,
    bslSourceIngress          = 55,
    bslSourceInit             = 56,
    bslSourceInterrupts       = 57,
    bslSourceIntr             = 58,
    bslSourceIpfix            = 59,
    bslSourceIpmc             = 60,
    bslSourceKlif             = 61,
    bslSourceKnet             = 62,
    bslSourceL2               = 63,
    bslSourceL2gre            = 64,
    bslSourceL2table          = 65,
    bslSourceL3               = 66,
    bslSourceL3srcbind        = 67,
    bslSourceLag              = 68,
    bslSourceLemaccess        = 69,
    bslSourceLif              = 70,
    bslSourceLink             = 71,
    bslSourceLlp              = 72,
    bslSourceLoadbalancing    = 73,
    bslSourceLpm              = 74,
    bslSourceMacsec           = 75,
    bslSourceManagement       = 76,
    bslSourceManagment        = 77,
    bslSourceMbist            = 78,
    bslSourceMcast            = 79,
    bslSourceMem              = 80,
    bslSourceMemtune          = 81,
    bslSourceMetering         = 82,
    bslSourceMii              = 83,
    bslSourceMiim             = 84,
    bslSourceMim              = 85,
    bslSourceMirror           = 86,
    bslSourceMmu              = 87,
    bslSourceMpls             = 88,
    bslSourceMsg              = 89,
    bslSourceMulticast        = 90,
    bslSourceMymac            = 91,
    bslSourceNh               = 92,
    bslSourceNhv              = 93,
    bslSourceNif              = 94,
    bslSourceNiv              = 95,
    bslSourceOam              = 96,
    bslSourceOfp              = 97,
    bslSourceOther            = 98,
    bslSourcePacket           = 99,
    bslSourceParser           = 100,
    bslSourcePci              = 101,
    bslSourcePhy              = 102,
    bslSourcePhymod           = 103,
    bslSourcePhysim           = 104,
    bslSourcePkt              = 105,
    bslSourcePktdata          = 106,
    bslSourcePmf              = 107,
    bslSourcePolicer          = 108,
    bslSourcePort             = 109,
    bslSourcePorts            = 110,
    bslSourcePpc              = 111,
    bslSourcePpd              = 112,
    bslSourcePtp              = 113,
    bslSourceQos              = 114,
    bslSourceRcload           = 115,
    bslSourceRcpu             = 116,
    bslSourceReg              = 117,
    bslSourceRegex            = 118,
    bslSourceRif              = 119,
    bslSourceRx               = 120,
    bslSourceSchan            = 121,
    bslSourceSchedular        = 122,
    bslSourceSemaccess        = 123,
    bslSourceSerdes           = 124,
    bslSourceShell            = 125,
    bslSourceSlb              = 126,
    bslSourceSocmem           = 127,
    bslSourceStat             = 128,
    bslSourceStg              = 129,
    bslSourceStk              = 130,
    bslSourceStktask          = 131,
    bslSourceStkv             = 132,
    bslSourceStp              = 133,
    bslSourceSubport          = 134,
    bslSourceSw               = 135,
    bslSourceSwdb             = 136,
    bslSourceSwitch           = 137,
    bslSourceSymtab           = 138,
    bslSourceTblaccess        = 139,
    bslSourceTcam             = 140,
    bslSourceTdm              = 141,
    bslSourceTests            = 142,
    bslSourceTime             = 143,
    bslSourceTopology         = 144,
    bslSourceTopov            = 145,
    bslSourceTrap             = 146,
    bslSourceTrapmgmt         = 147,
    bslSourceTrill            = 148,
    bslSourceTrunk            = 149,
    bslSourceTunnel           = 150,
    bslSourceTunnelv          = 151,
    bslSourceTx               = 152,
    bslSourceUtils            = 153,
    bslSourceVerinet          = 154,
    bslSourceVlan             = 155,
    bslSourceVsi              = 156,
    bslSourceVxlan            = 157,
    bslSourceWbdb             = 158,
    bslSourceXlmac            = 159,
    bslSourceCount            = 160
} bsl_source_t;

#define BSL_SOURCE_NAMES_INIT { \
    "100G", \
    "10G", \
    "AccessCtrlList", \
    "ActionCMD", \
    "ALpm", \
    "API", \
    "ARL", \
    "ARLMON", \
    "ATP", \
    "ATPV", \
    "ATTach", \
    "AUth", \
    "BFD", \
    "C2C", \
    "C2CV", \
    "CEINSTructions", \
    "CELL", \
    "CES", \
    "CHASsis", \
    "CHIP", \
    "CMIC", \
    "CNM", \
    "CNT", \
    "COMMON", \
    "COSq", \
    "CounTeR", \
    "CTPKT", \
    "CTPKTV", \
    "DDR", \
    "DIAG", \
    "DIAGNostics", \
    "DISCover", \
    "DISCV", \
    "DMA", \
    "DRAM", \
    "EGRess", \
    "ELPM", \
    "END", \
    "ESEMACCess", \
    "ESM", \
    "EXTender", \
    "FABric", \
    "FAILover", \
    "FCOE", \
    "FLEXctr", \
    "FlowControl", \
    "ForWaRD", \
    "FP", \
    "FrameWork", \
    "GE", \
    "GENeral", \
    "HAsh", \
    "HEADers", \
    "HWDEBug", \
    "I2C", \
    "INGress", \
    "INIT", \
    "INTERrupts", \
    "INTr", \
    "IPFIX", \
    "IPMC", \
    "KLIF", \
    "KNET", \
    "L2", \
    "L2GRE", \
    "L2TABLE", \
    "L3", \
    "L3SRCBind", \
    "LAG", \
    "LEMACCess", \
    "LIF", \
    "LInk", \
    "LLP", \
    "LoadBalancing", \
    "LPM", \
    "MacSEC", \
    "ManaGeMenT", \
    "ManaGMeNT", \
    "MBIST", \
    "MCast", \
    "MEM", \
    "MemTUNE", \
    "METering", \
    "MII", \
    "MIIM", \
    "MIM", \
    "MIRRor", \
    "MMU", \
    "MPLS", \
    "MSG", \
    "MultiCast", \
    "MYMAC", \
    "NH", \
    "NHV", \
    "NIF", \
    "NIV", \
    "OAM", \
    "OFP", \
    "OTHER", \
    "PACKet", \
    "PARSer", \
    "PCI", \
    "PHY", \
    "PHYMOD", \
    "PHYSIM", \
    "PKT", \
    "PKTdata", \
    "PMF", \
    "POLicer", \
    "POrt", \
    "PORTS", \
    "PPC", \
    "PPD", \
    "PTP", \
    "QOS", \
    "RCLOAD", \
    "RCPU", \
    "REG", \
    "Regex", \
    "RIF", \
    "RX", \
    "SChan", \
    "SCHeDular", \
    "SEMACCess", \
    "SERdes", \
    "SHell", \
    "SLB", \
    "SOCMEM", \
    "STAT", \
    "STG", \
    "STK", \
    "STKtask", \
    "STKV", \
    "STP", \
    "SUBPort", \
    "SW", \
    "SWDB", \
    "SWItch", \
    "SYMtab", \
    "TBLACCess", \
    "TCAM", \
    "TDM", \
    "TESTS", \
    "TIME", \
    "TOPOlogy", \
    "TOPOV", \
    "TRAP", \
    "TRapMGMT", \
    "TRILL", \
    "TRUNK", \
    "TUNNEL", \
    "TUNNELV", \
    "TX", \
    "UTILs", \
    "VERInet", \
    "VLAN", \
    "VSI", \
    "VXLAN", \
    "WBDB", \
    "XLMAC"  \
}

/* Short hand macros for Appl layer */
#define BSL_APPL_ACCESSCTRLLIST         BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceAccessctrllist
#define BSL_APPL_ARL                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceArl
#define BSL_APPL_CHASSIS                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceChassis
#define BSL_APPL_CMIC                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceCmic
#define BSL_APPL_COMMON                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceCommon
#define BSL_APPL_COUNTER                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceCounter
#define BSL_APPL_DMA                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceDma
#define BSL_APPL_END                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceEnd
#define BSL_APPL_FABRIC                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceFabric
#define BSL_APPL_I2C                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceI2c
#define BSL_APPL_KLIF                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceKlif
#define BSL_APPL_L2TABLE                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceL2table
#define BSL_APPL_L3                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceL3
#define BSL_APPL_MPLS                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceMpls
#define BSL_APPL_OTHER                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceOther
#define BSL_APPL_PCI                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourcePci
#define BSL_APPL_PHY                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourcePhy
#define BSL_APPL_PKT                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourcePkt
#define BSL_APPL_PORT                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourcePort
#define BSL_APPL_RCLOAD                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceRcload
#define BSL_APPL_REG                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceReg
#define BSL_APPL_RX                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceRx
#define BSL_APPL_SHELL                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceShell
#define BSL_APPL_SOCMEM                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceSocmem
#define BSL_APPL_SYMTAB                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceSymtab
#define BSL_APPL_TESTS                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceTests
#define BSL_APPL_TX                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceTx

/* Sources valid for Appl layer */
#define BSL_SOURCE_APPL_VALID_INIT { \
    bslSourceRcload, \
    bslSourceL3, \
    bslSourceTx, \
    bslSourceCommon, \
    bslSourceMpls, \
    bslSourceChassis, \
    bslSourceCmic, \
    bslSourceAccessctrllist, \
    bslSourceArl, \
    bslSourceDma, \
    bslSourceShell, \
    bslSourcePkt, \
    bslSourcePci, \
    bslSourceSymtab, \
    bslSourceFabric, \
    bslSourceL2table, \
    bslSourcePhy, \
    bslSourceReg, \
    bslSourceCounter, \
    bslSourceSocmem, \
    bslSourcePort, \
    bslSourceEnd, \
    bslSourceOther, \
    bslSourceI2c, \
    bslSourceRx, \
    bslSourceKlif, \
    bslSourceTests, \
    bslSourceCount \
}

/* Short hand macros for Bcm layer */
#define BSL_BCM_ALPM                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceAlpm
#define BSL_BCM_API                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceApi
#define BSL_BCM_ARL                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceArl
#define BSL_BCM_ATTACH                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceAttach
#define BSL_BCM_AUTH                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceAuth
#define BSL_BCM_BFD                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceBfd
#define BSL_BCM_CES                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceCes
#define BSL_BCM_CNT                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceCnt
#define BSL_BCM_COMMON                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceCommon
#define BSL_BCM_COSQ                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceCosq
#define BSL_BCM_COUNTER                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceCounter
#define BSL_BCM_DMA                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceDma
#define BSL_BCM_ELPM                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceElpm
#define BSL_BCM_EXTENDER                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceExtender
#define BSL_BCM_FABRIC                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceFabric
#define BSL_BCM_FAILOVER                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceFailover
#define BSL_BCM_FCOE                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceFcoe
#define BSL_BCM_FLEXCTR                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceFlexctr
#define BSL_BCM_FP                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceFp
#define BSL_BCM_INIT                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceInit
#define BSL_BCM_INTR                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceIntr
#define BSL_BCM_IPFIX                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceIpfix
#define BSL_BCM_IPMC                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceIpmc
#define BSL_BCM_KNET                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceKnet
#define BSL_BCM_L2                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceL2
#define BSL_BCM_L2GRE                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceL2gre
#define BSL_BCM_L2TABLE                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceL2table
#define BSL_BCM_L3                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceL3
#define BSL_BCM_LINK                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceLink
#define BSL_BCM_MACSEC                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceMacsec
#define BSL_BCM_MCAST                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceMcast
#define BSL_BCM_MEM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceMem
#define BSL_BCM_MIM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceMim
#define BSL_BCM_MIRROR                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceMirror
#define BSL_BCM_MPLS                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceMpls
#define BSL_BCM_MSG                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceMsg
#define BSL_BCM_MULTICAST               BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceMulticast
#define BSL_BCM_NIV                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceNiv
#define BSL_BCM_OAM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceOam
#define BSL_BCM_OTHER                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceOther
#define BSL_BCM_PACKET                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourcePacket
#define BSL_BCM_PHY                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourcePhy
#define BSL_BCM_PKT                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourcePkt
#define BSL_BCM_POLICER                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourcePolicer
#define BSL_BCM_PORT                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourcePort
#define BSL_BCM_PTP                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourcePtp
#define BSL_BCM_QOS                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceQos
#define BSL_BCM_RCPU                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceRcpu
#define BSL_BCM_REGEX                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceRegex
#define BSL_BCM_RX                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceRx
#define BSL_BCM_STAT                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceStat
#define BSL_BCM_STG                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceStg
#define BSL_BCM_STK                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceStk
#define BSL_BCM_STP                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceStp
#define BSL_BCM_SUBPORT                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceSubport
#define BSL_BCM_SWITCH                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceSwitch
#define BSL_BCM_TESTS                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceTests
#define BSL_BCM_TIME                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceTime
#define BSL_BCM_TRILL                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceTrill
#define BSL_BCM_TRUNK                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceTrunk
#define BSL_BCM_TUNNEL                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceTunnel
#define BSL_BCM_TX                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceTx
#define BSL_BCM_UTILS                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceUtils
#define BSL_BCM_VLAN                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceVlan
#define BSL_BCM_VXLAN                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcm, bslSourceVxlan

/* Sources valid for Bcm layer */
#define BSL_SOURCE_BCM_VALID_INIT { \
    bslSourceInit, \
    bslSourceIntr, \
    bslSourcePacket, \
    bslSourceElpm, \
    bslSourceStat, \
    bslSourceStp, \
    bslSourceL3, \
    bslSourceRegex, \
    bslSourceMim, \
    bslSourceTime, \
    bslSourceMirror, \
    bslSourceSubport, \
    bslSourceStg, \
    bslSourceAttach, \
    bslSourceMsg, \
    bslSourceTx, \
    bslSourceUtils, \
    bslSourceCommon, \
    bslSourceMpls, \
    bslSourceCosq, \
    bslSourceMulticast, \
    bslSourceQos, \
    bslSourceCes, \
    bslSourceBfd, \
    bslSourceL2gre, \
    bslSourceMacsec, \
    bslSourceCnt, \
    bslSourceFailover, \
    bslSourceFp, \
    bslSourceArl, \
    bslSourceAuth, \
    bslSourceDma, \
    bslSourceNiv, \
    bslSourcePtp, \
    bslSourceAlpm, \
    bslSourceVlan, \
    bslSourceFcoe, \
    bslSourceTrill, \
    bslSourceOam, \
    bslSourceExtender, \
    bslSourcePkt, \
    bslSourceStk, \
    bslSourceFlexctr, \
    bslSourceFabric, \
    bslSourceMcast, \
    bslSourceL2table, \
    bslSourcePhy, \
    bslSourceIpfix, \
    bslSourceKnet, \
    bslSourceL2, \
    bslSourceTunnel, \
    bslSourceSwitch, \
    bslSourceRcpu, \
    bslSourceCounter, \
    bslSourcePort, \
    bslSourceOther, \
    bslSourceMem, \
    bslSourceVxlan, \
    bslSourceIpmc, \
    bslSourceApi, \
    bslSourceLink, \
    bslSourceTrunk, \
    bslSourceRx, \
    bslSourcePolicer, \
    bslSourceTests, \
    bslSourceCount \
}

/* Short hand macros for Bcmx layer */
#define BSL_BCMX_ATTACH                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceAttach
#define BSL_BCMX_COMMON                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceCommon
#define BSL_BCMX_COUNTER                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceCounter
#define BSL_BCMX_L2                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceL2
#define BSL_BCMX_L3                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceL3
#define BSL_BCMX_LINK                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceLink
#define BSL_BCMX_OTHER                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceOther
#define BSL_BCMX_PKTDATA                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourcePktdata
#define BSL_BCMX_PORT                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourcePort
#define BSL_BCMX_RX                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceRx
#define BSL_BCMX_TX                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceTx
#define BSL_BCMX_VLAN                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBcmx, bslSourceVlan

/* Sources valid for Bcmx layer */
#define BSL_SOURCE_BCMX_VALID_INIT { \
    bslSourceL3, \
    bslSourceAttach, \
    bslSourceTx, \
    bslSourceCommon, \
    bslSourcePktdata, \
    bslSourceVlan, \
    bslSourceL2, \
    bslSourceCounter, \
    bslSourcePort, \
    bslSourceOther, \
    bslSourceLink, \
    bslSourceRx, \
    bslSourceCount \
}

/* Short hand macros for Board layer */
#define BSL_BOARD_COMMON                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBoard, bslSourceCommon
#define BSL_BOARD_OTHER                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerBoard, bslSourceOther

/* Sources valid for Board layer */
#define BSL_SOURCE_BOARD_VALID_INIT { \
    bslSourceCommon, \
    bslSourceOther, \
    bslSourceCount \
}

/* Short hand macros for Sal layer */
#define BSL_SAL_COMMON                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSal, bslSourceCommon
#define BSL_SAL_OTHER                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSal, bslSourceOther

/* Sources valid for Sal layer */
#define BSL_SOURCE_SAL_VALID_INIT { \
    bslSourceCommon, \
    bslSourceOther, \
    bslSourceCount \
}

/* Short hand macros for Soc layer */
#define BSL_SOC_100G                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSource100g
#define BSL_SOC_10G                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSource10g
#define BSL_SOC_ALPM                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceAlpm
#define BSL_SOC_ARL                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceArl
#define BSL_SOC_ARLMON                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceArlmon
#define BSL_SOC_CHIP                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceChip
#define BSL_SOC_CNM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceCnm
#define BSL_SOC_CNT                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceCnt
#define BSL_SOC_COMMON                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceCommon
#define BSL_SOC_COSQ                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceCosq
#define BSL_SOC_COUNTER                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceCounter
#define BSL_SOC_DDR                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceDdr
#define BSL_SOC_DIAG                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceDiag
#define BSL_SOC_DMA                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceDma
#define BSL_SOC_DRAM                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceDram
#define BSL_SOC_EGRESS                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceEgress
#define BSL_SOC_ESM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceEsm
#define BSL_SOC_FABRIC                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceFabric
#define BSL_SOC_FLOWCONTROL             BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceFlowcontrol
#define BSL_SOC_FORWARD                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceForward
#define BSL_SOC_FP                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceFp
#define BSL_SOC_GE                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceGe
#define BSL_SOC_GENERAL                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceGeneral
#define BSL_SOC_HASH                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceHash
#define BSL_SOC_HEADERS                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceHeaders
#define BSL_SOC_I2C                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceI2c
#define BSL_SOC_INGRESS                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceIngress
#define BSL_SOC_INIT                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceInit
#define BSL_SOC_INTR                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceIntr
#define BSL_SOC_KNET                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceKnet
#define BSL_SOC_L2                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceL2
#define BSL_SOC_L2TABLE                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceL2table
#define BSL_SOC_L3                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceL3
#define BSL_SOC_LIF                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceLif
#define BSL_SOC_LINK                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceLink
#define BSL_SOC_LLP                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceLlp
#define BSL_SOC_LPM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceLpm
#define BSL_SOC_MANAGEMENT              BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceManagement
#define BSL_SOC_MBIST                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMbist
#define BSL_SOC_MCAST                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMcast
#define BSL_SOC_MEM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMem
#define BSL_SOC_MEMTUNE                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMemtune
#define BSL_SOC_METERING                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMetering
#define BSL_SOC_MII                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMii
#define BSL_SOC_MIIM                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMiim
#define BSL_SOC_MIRROR                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMirror
#define BSL_SOC_MMU                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMmu
#define BSL_SOC_MPLS                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMpls
#define BSL_SOC_MSG                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMsg
#define BSL_SOC_MULTICAST               BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceMulticast
#define BSL_SOC_OAM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceOam
#define BSL_SOC_OTHER                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceOther
#define BSL_SOC_PACKET                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePacket
#define BSL_SOC_PCI                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePci
#define BSL_SOC_PHY                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePhy
#define BSL_SOC_PHYMOD                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePhymod
#define BSL_SOC_PHYSIM                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePhysim
#define BSL_SOC_PKT                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePkt
#define BSL_SOC_PORT                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePort
#define BSL_SOC_PPC                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePpc
#define BSL_SOC_PPD                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePpd
#define BSL_SOC_PTP                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePtp
#define BSL_SOC_RCPU                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceRcpu
#define BSL_SOC_REG                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceReg
#define BSL_SOC_SCHAN                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceSchan
#define BSL_SOC_SLB                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceSlb
#define BSL_SOC_SOCMEM                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceSocmem
#define BSL_SOC_STAT                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceStat
#define BSL_SOC_STK                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceStk
#define BSL_SOC_STP                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceStp
#define BSL_SOC_SWDB                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceSwdb
#define BSL_SOC_TCAM                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceTcam
#define BSL_SOC_TDM                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceTdm
#define BSL_SOC_TESTS                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceTests
#define BSL_SOC_TRAP                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceTrap
#define BSL_SOC_TRUNK                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceTrunk
#define BSL_SOC_TX                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceTx
#define BSL_SOC_VLAN                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceVlan
#define BSL_SOC_VSI                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceVsi
#define BSL_SOC_XLMAC                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceXlmac

/* Sources valid for Soc layer */
#define BSL_SOURCE_SOC_VALID_INIT { \
    bslSourceInit, \
    bslSourceIntr, \
    bslSourceTrap, \
    bslSourcePacket, \
    bslSourceDiag, \
    bslSourceStat, \
    bslSourceHash, \
    bslSourceStp, \
    bslSourceL3, \
    bslSourceEsm, \
    bslSourceGe, \
    bslSourceMirror, \
    bslSourceMsg, \
    bslSourceTx, \
    bslSourcePpd, \
    bslSourceCommon, \
    bslSourceMpls, \
    bslSource10g, \
    bslSourceMbist, \
    bslSourceCosq, \
    bslSourceMulticast, \
    bslSourceLlp, \
    bslSourceSlb, \
    bslSourceCnt, \
    bslSourceDdr, \
    bslSourceMiim, \
    bslSourceChip, \
    bslSourceXlmac, \
    bslSourceGeneral, \
    bslSourceHeaders, \
    bslSourceFp, \
    bslSourceArl, \
    bslSourceDma, \
    bslSourcePtp, \
    bslSourceAlpm, \
    bslSourceSchan, \
    bslSourceArlmon, \
    bslSourceIngress, \
    bslSourceVlan, \
    bslSourcePhymod, \
    bslSourceOam, \
    bslSourceForward, \
    bslSourceMmu, \
    bslSourcePpc, \
    bslSourcePkt, \
    bslSourceEgress, \
    bslSourcePci, \
    bslSourceStk, \
    bslSourceCnm, \
    bslSourceTcam, \
    bslSourceFabric, \
    bslSourceMemtune, \
    bslSourceMcast, \
    bslSourceL2table, \
    bslSourcePhy, \
    bslSourceKnet, \
    bslSourceReg, \
    bslSourceL2, \
    bslSourceRcpu, \
    bslSourceCounter, \
    bslSourceTdm, \
    bslSourceSocmem, \
    bslSourceSwdb, \
    bslSourceVsi, \
    bslSourceLpm, \
    bslSourcePort, \
    bslSourceMii, \
    bslSourceOther, \
    bslSourceMem, \
    bslSourceMetering, \
    bslSourceLif, \
    bslSourceManagement, \
    bslSourcePhysim, \
    bslSourceI2c, \
    bslSourceDram, \
    bslSourceLink, \
    bslSourceTrunk, \
    bslSourceFlowcontrol, \
    bslSource100g, \
    bslSourceTests, \
    bslSourceCount \
}

/* Short hand macros for Socdnx layer */
#define BSL_SOCDNX_ACTIONCMD            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceActioncmd
#define BSL_SOCDNX_CEINSTRUCTIONS       BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceCeinstructions
#define BSL_SOCDNX_CELL                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceCell
#define BSL_SOCDNX_CHIP                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceChip
#define BSL_SOCDNX_CNM                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceCnm
#define BSL_SOCDNX_CNT                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceCnt
#define BSL_SOCDNX_COSQ                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceCosq
#define BSL_SOCDNX_DIAGNOSTICS          BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceDiagnostics
#define BSL_SOCDNX_DRAM                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceDram
#define BSL_SOCDNX_EGRESS               BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceEgress
#define BSL_SOCDNX_ESEMACCESS           BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceEsemaccess
#define BSL_SOCDNX_FABRIC               BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceFabric
#define BSL_SOCDNX_FLOWCONTROL          BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceFlowcontrol
#define BSL_SOCDNX_FORWARD              BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceForward
#define BSL_SOCDNX_FP                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceFp
#define BSL_SOCDNX_FRAMEWORK            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceFramework
#define BSL_SOCDNX_GENERAL              BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceGeneral
#define BSL_SOCDNX_HEADERS              BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceHeaders
#define BSL_SOCDNX_HWDEBUG              BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceHwdebug
#define BSL_SOCDNX_INGRESS              BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceIngress
#define BSL_SOCDNX_INIT                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceInit
#define BSL_SOCDNX_INTERRUPTS           BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceInterrupts
#define BSL_SOCDNX_L3SRCBIND            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceL3srcbind
#define BSL_SOCDNX_LAG                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceLag
#define BSL_SOCDNX_LEMACCESS            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceLemaccess
#define BSL_SOCDNX_LIF                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceLif
#define BSL_SOCDNX_LLP                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceLlp
#define BSL_SOCDNX_LOADBALANCING        BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceLoadbalancing
#define BSL_SOCDNX_MANAGMENT            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceManagment
#define BSL_SOCDNX_MBIST                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceMbist
#define BSL_SOCDNX_MEM                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceMem
#define BSL_SOCDNX_METERING             BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceMetering
#define BSL_SOCDNX_MPLS                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceMpls
#define BSL_SOCDNX_MULTICAST            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceMulticast
#define BSL_SOCDNX_MYMAC                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceMymac
#define BSL_SOCDNX_NIF                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceNif
#define BSL_SOCDNX_OAM                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceOam
#define BSL_SOCDNX_OFP                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceOfp
#define BSL_SOCDNX_PARSER               BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceParser
#define BSL_SOCDNX_PKT                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourcePkt
#define BSL_SOCDNX_PMF                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourcePmf
#define BSL_SOCDNX_PORTS                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourcePorts
#define BSL_SOCDNX_PPC                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourcePpc
#define BSL_SOCDNX_PPD                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourcePpd
#define BSL_SOCDNX_PTP                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourcePtp
#define BSL_SOCDNX_REG                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceReg
#define BSL_SOCDNX_RIF                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceRif
#define BSL_SOCDNX_SCHEDULAR            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceSchedular
#define BSL_SOCDNX_SEMACCESS            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceSemaccess
#define BSL_SOCDNX_SERDES               BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceSerdes
#define BSL_SOCDNX_STAT                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceStat
#define BSL_SOCDNX_SW                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceSw
#define BSL_SOCDNX_TBLACCESS            BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceTblaccess
#define BSL_SOCDNX_TCAM                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceTcam
#define BSL_SOCDNX_TDM                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceTdm
#define BSL_SOCDNX_TRAPMGMT             BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceTrapmgmt
#define BSL_SOCDNX_VSI                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceVsi
#define BSL_SOCDNX_WBDB                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSocdnx, bslSourceWbdb

/* Sources valid for Socdnx layer */
#define BSL_SOURCE_SOCDNX_VALID_INIT { \
    bslSourceWbdb, \
    bslSourceInit, \
    bslSourceEsemaccess, \
    bslSourceStat, \
    bslSourceL3srcbind, \
    bslSourcePpd, \
    bslSourceMpls, \
    bslSourceActioncmd, \
    bslSourceMbist, \
    bslSourceCosq, \
    bslSourceSchedular, \
    bslSourceMulticast, \
    bslSourcePmf, \
    bslSourceLemaccess, \
    bslSourceFramework, \
    bslSourceLlp, \
    bslSourceCnt, \
    bslSourceChip, \
    bslSourceRif, \
    bslSourceGeneral, \
    bslSourceTblaccess, \
    bslSourceHeaders, \
    bslSourceManagment, \
    bslSourceFp, \
    bslSourceInterrupts, \
    bslSourceLoadbalancing, \
    bslSourceCell, \
    bslSourcePtp, \
    bslSourceLag, \
    bslSourceIngress, \
    bslSourceOam, \
    bslSourceNif, \
    bslSourceForward, \
    bslSourcePpc, \
    bslSourcePkt, \
    bslSourceEgress, \
    bslSourceCnm, \
    bslSourceTcam, \
    bslSourceFabric, \
    bslSourceSemaccess, \
    bslSourceMymac, \
    bslSourceSerdes, \
    bslSourceCeinstructions, \
    bslSourceReg, \
    bslSourceTdm, \
    bslSourceTrapmgmt, \
    bslSourceSw, \
    bslSourceVsi, \
    bslSourceOfp, \
    bslSourcePorts, \
    bslSourceDiagnostics, \
    bslSourceMem, \
    bslSourceMetering, \
    bslSourceLif, \
    bslSourceParser, \
    bslSourceDram, \
    bslSourceFlowcontrol, \
    bslSourceHwdebug, \
    bslSourceCount \
}

/* Short hand macros for Sys layer */
#define BSL_SYS_DMA                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSys, bslSourceDma
#define BSL_SYS_END                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSys, bslSourceEnd
#define BSL_SYS_PCI                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSys, bslSourcePci
#define BSL_SYS_VERINET                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSys, bslSourceVerinet

/* Sources valid for Sys layer */
#define BSL_SOURCE_SYS_VALID_INIT { \
    bslSourceVerinet, \
    bslSourceDma, \
    bslSourcePci, \
    bslSourceEnd, \
    bslSourceCount \
}

/* Short hand macros for Tks layer */
#define BSL_TKS_ATP                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceAtp
#define BSL_TKS_ATPV                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceAtpv
#define BSL_TKS_C2C                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceC2c
#define BSL_TKS_C2CV                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceC2cv
#define BSL_TKS_COMMON                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceCommon
#define BSL_TKS_CTPKT                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceCtpkt
#define BSL_TKS_CTPKTV                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceCtpktv
#define BSL_TKS_DISCOVER                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceDiscover
#define BSL_TKS_DISCV                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceDiscv
#define BSL_TKS_NH                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceNh
#define BSL_TKS_NHV                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceNhv
#define BSL_TKS_OTHER                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceOther
#define BSL_TKS_STKTASK                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceStktask
#define BSL_TKS_STKV                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceStkv
#define BSL_TKS_TOPOLOGY                BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceTopology
#define BSL_TKS_TOPOV                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceTopov
#define BSL_TKS_TUNNEL                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceTunnel
#define BSL_TKS_TUNNELV                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceTunnelv
#define BSL_TKS_TX                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerTks, bslSourceTx

/* Sources valid for Tks layer */
#define BSL_SOURCE_TKS_VALID_INIT { \
    bslSourceC2cv, \
    bslSourceNhv, \
    bslSourceCtpktv, \
    bslSourceStktask, \
    bslSourceAtpv, \
    bslSourceTx, \
    bslSourceCommon, \
    bslSourceTopov, \
    bslSourceNh, \
    bslSourceDiscover, \
    bslSourceTopology, \
    bslSourceDiscv, \
    bslSourceCtpkt, \
    bslSourceC2c, \
    bslSourceTunnelv, \
    bslSourceTunnel, \
    bslSourceOther, \
    bslSourceStkv, \
    bslSourceAtp, \
    bslSourceCount \
}

/* Organize layer/source/severity in a single 32-bit word */
#define BSL_LAYER_SHFT          24
#define BSL_LAYER_MASK          0xff
#define BSL_SOURCE_SHFT         8
#define BSL_SOURCE_MASK         0xffff
#define BSL_SEVERITY_SHFT       0
#define BSL_SEVERITY_MASK       0xff

/* Get elements of packed meta data */
#define BSL_LAYER_GET(chk_) \
    (((chk_) >> BSL_LAYER_SHFT) & BSL_LAYER_MASK)
#define BSL_SOURCE_GET(chk_) \
    (((chk_) >> BSL_SOURCE_SHFT) & BSL_SOURCE_MASK)
#define BSL_SEVERITY_GET(chk_) \
    (((chk_) >> BSL_SEVERITY_SHFT) & BSL_SEVERITY_MASK)

/* Encode elements for packed meta data */
#define BSL_LAYER_ENC(layer_) \
    ((layer_) << BSL_LAYER_SHFT)
#define BSL_SOURCE_ENC(source_) \
    ((source_) << BSL_SOURCE_SHFT)
#define BSL_SEVERITY_ENC(severity_) \
    ((severity_) << BSL_SEVERITY_SHFT)

/* Severity defines for LOG_* macros */
#define BSL_FATAL               BSL_SEVERITY_ENC(bslSeverityFatal)
#define BSL_ERROR               BSL_SEVERITY_ENC(bslSeverityError)
#define BSL_WARN                BSL_SEVERITY_ENC(bslSeverityWarn)
#define BSL_INFO                BSL_SEVERITY_ENC(bslSeverityInfo)
#define BSL_VERBOSE             BSL_SEVERITY_ENC(bslSeverityVerbose)
#define BSL_DEBUG               BSL_SEVERITY_ENC(bslSeverityDebug)

/* Layer defines for LOG_* macros */
#define BSL_L_APPL              BSL_LAYER_ENC(bslLayerAppl)
#define BSL_L_BCM               BSL_LAYER_ENC(bslLayerBcm)
#define BSL_L_BCMX              BSL_LAYER_ENC(bslLayerBcmx)
#define BSL_L_BOARD             BSL_LAYER_ENC(bslLayerBoard)
#define BSL_L_SAL               BSL_LAYER_ENC(bslLayerSal)
#define BSL_L_SOC               BSL_LAYER_ENC(bslLayerSoc)
#define BSL_L_SOCDNX            BSL_LAYER_ENC(bslLayerSocdnx)
#define BSL_L_SYS               BSL_LAYER_ENC(bslLayerSys)
#define BSL_L_TKS               BSL_LAYER_ENC(bslLayerTks)

/* Source defines for LOG_* macros */
#define BSL_S_100G              BSL_SOURCE_ENC(bslSource100g)
#define BSL_S_10G               BSL_SOURCE_ENC(bslSource10g)
#define BSL_S_ACCESSCTRLLIST    BSL_SOURCE_ENC(bslSourceAccessctrllist)
#define BSL_S_ACTIONCMD         BSL_SOURCE_ENC(bslSourceActioncmd)
#define BSL_S_ALPM              BSL_SOURCE_ENC(bslSourceAlpm)
#define BSL_S_API               BSL_SOURCE_ENC(bslSourceApi)
#define BSL_S_ARL               BSL_SOURCE_ENC(bslSourceArl)
#define BSL_S_ARLMON            BSL_SOURCE_ENC(bslSourceArlmon)
#define BSL_S_ATP               BSL_SOURCE_ENC(bslSourceAtp)
#define BSL_S_ATPV              BSL_SOURCE_ENC(bslSourceAtpv)
#define BSL_S_ATTACH            BSL_SOURCE_ENC(bslSourceAttach)
#define BSL_S_AUTH              BSL_SOURCE_ENC(bslSourceAuth)
#define BSL_S_BFD               BSL_SOURCE_ENC(bslSourceBfd)
#define BSL_S_C2C               BSL_SOURCE_ENC(bslSourceC2c)
#define BSL_S_C2CV              BSL_SOURCE_ENC(bslSourceC2cv)
#define BSL_S_CEINSTRUCTIONS    BSL_SOURCE_ENC(bslSourceCeinstructions)
#define BSL_S_CELL              BSL_SOURCE_ENC(bslSourceCell)
#define BSL_S_CES               BSL_SOURCE_ENC(bslSourceCes)
#define BSL_S_CHASSIS           BSL_SOURCE_ENC(bslSourceChassis)
#define BSL_S_CHIP              BSL_SOURCE_ENC(bslSourceChip)
#define BSL_S_CMIC              BSL_SOURCE_ENC(bslSourceCmic)
#define BSL_S_CNM               BSL_SOURCE_ENC(bslSourceCnm)
#define BSL_S_CNT               BSL_SOURCE_ENC(bslSourceCnt)
#define BSL_S_COMMON            BSL_SOURCE_ENC(bslSourceCommon)
#define BSL_S_COSQ              BSL_SOURCE_ENC(bslSourceCosq)
#define BSL_S_COUNTER           BSL_SOURCE_ENC(bslSourceCounter)
#define BSL_S_CTPKT             BSL_SOURCE_ENC(bslSourceCtpkt)
#define BSL_S_CTPKTV            BSL_SOURCE_ENC(bslSourceCtpktv)
#define BSL_S_DDR               BSL_SOURCE_ENC(bslSourceDdr)
#define BSL_S_DIAG              BSL_SOURCE_ENC(bslSourceDiag)
#define BSL_S_DIAGNOSTICS       BSL_SOURCE_ENC(bslSourceDiagnostics)
#define BSL_S_DISCOVER          BSL_SOURCE_ENC(bslSourceDiscover)
#define BSL_S_DISCV             BSL_SOURCE_ENC(bslSourceDiscv)
#define BSL_S_DMA               BSL_SOURCE_ENC(bslSourceDma)
#define BSL_S_DRAM              BSL_SOURCE_ENC(bslSourceDram)
#define BSL_S_EGRESS            BSL_SOURCE_ENC(bslSourceEgress)
#define BSL_S_ELPM              BSL_SOURCE_ENC(bslSourceElpm)
#define BSL_S_END               BSL_SOURCE_ENC(bslSourceEnd)
#define BSL_S_ESEMACCESS        BSL_SOURCE_ENC(bslSourceEsemaccess)
#define BSL_S_ESM               BSL_SOURCE_ENC(bslSourceEsm)
#define BSL_S_EXTENDER          BSL_SOURCE_ENC(bslSourceExtender)
#define BSL_S_FABRIC            BSL_SOURCE_ENC(bslSourceFabric)
#define BSL_S_FAILOVER          BSL_SOURCE_ENC(bslSourceFailover)
#define BSL_S_FCOE              BSL_SOURCE_ENC(bslSourceFcoe)
#define BSL_S_FLEXCTR           BSL_SOURCE_ENC(bslSourceFlexctr)
#define BSL_S_FLOWCONTROL       BSL_SOURCE_ENC(bslSourceFlowcontrol)
#define BSL_S_FORWARD           BSL_SOURCE_ENC(bslSourceForward)
#define BSL_S_FP                BSL_SOURCE_ENC(bslSourceFp)
#define BSL_S_FRAMEWORK         BSL_SOURCE_ENC(bslSourceFramework)
#define BSL_S_GE                BSL_SOURCE_ENC(bslSourceGe)
#define BSL_S_GENERAL           BSL_SOURCE_ENC(bslSourceGeneral)
#define BSL_S_HASH              BSL_SOURCE_ENC(bslSourceHash)
#define BSL_S_HEADERS           BSL_SOURCE_ENC(bslSourceHeaders)
#define BSL_S_HWDEBUG           BSL_SOURCE_ENC(bslSourceHwdebug)
#define BSL_S_I2C               BSL_SOURCE_ENC(bslSourceI2c)
#define BSL_S_INGRESS           BSL_SOURCE_ENC(bslSourceIngress)
#define BSL_S_INIT              BSL_SOURCE_ENC(bslSourceInit)
#define BSL_S_INTERRUPTS        BSL_SOURCE_ENC(bslSourceInterrupts)
#define BSL_S_INTR              BSL_SOURCE_ENC(bslSourceIntr)
#define BSL_S_IPFIX             BSL_SOURCE_ENC(bslSourceIpfix)
#define BSL_S_IPMC              BSL_SOURCE_ENC(bslSourceIpmc)
#define BSL_S_KLIF              BSL_SOURCE_ENC(bslSourceKlif)
#define BSL_S_KNET              BSL_SOURCE_ENC(bslSourceKnet)
#define BSL_S_L2                BSL_SOURCE_ENC(bslSourceL2)
#define BSL_S_L2GRE             BSL_SOURCE_ENC(bslSourceL2gre)
#define BSL_S_L2TABLE           BSL_SOURCE_ENC(bslSourceL2table)
#define BSL_S_L3                BSL_SOURCE_ENC(bslSourceL3)
#define BSL_S_L3SRCBIND         BSL_SOURCE_ENC(bslSourceL3srcbind)
#define BSL_S_LAG               BSL_SOURCE_ENC(bslSourceLag)
#define BSL_S_LEMACCESS         BSL_SOURCE_ENC(bslSourceLemaccess)
#define BSL_S_LIF               BSL_SOURCE_ENC(bslSourceLif)
#define BSL_S_LINK              BSL_SOURCE_ENC(bslSourceLink)
#define BSL_S_LLP               BSL_SOURCE_ENC(bslSourceLlp)
#define BSL_S_LOADBALANCING     BSL_SOURCE_ENC(bslSourceLoadbalancing)
#define BSL_S_LPM               BSL_SOURCE_ENC(bslSourceLpm)
#define BSL_S_MACSEC            BSL_SOURCE_ENC(bslSourceMacsec)
#define BSL_S_MANAGEMENT        BSL_SOURCE_ENC(bslSourceManagement)
#define BSL_S_MANAGMENT         BSL_SOURCE_ENC(bslSourceManagment)
#define BSL_S_MBIST             BSL_SOURCE_ENC(bslSourceMbist)
#define BSL_S_MCAST             BSL_SOURCE_ENC(bslSourceMcast)
#define BSL_S_MEM               BSL_SOURCE_ENC(bslSourceMem)
#define BSL_S_MEMTUNE           BSL_SOURCE_ENC(bslSourceMemtune)
#define BSL_S_METERING          BSL_SOURCE_ENC(bslSourceMetering)
#define BSL_S_MII               BSL_SOURCE_ENC(bslSourceMii)
#define BSL_S_MIIM              BSL_SOURCE_ENC(bslSourceMiim)
#define BSL_S_MIM               BSL_SOURCE_ENC(bslSourceMim)
#define BSL_S_MIRROR            BSL_SOURCE_ENC(bslSourceMirror)
#define BSL_S_MMU               BSL_SOURCE_ENC(bslSourceMmu)
#define BSL_S_MPLS              BSL_SOURCE_ENC(bslSourceMpls)
#define BSL_S_MSG               BSL_SOURCE_ENC(bslSourceMsg)
#define BSL_S_MULTICAST         BSL_SOURCE_ENC(bslSourceMulticast)
#define BSL_S_MYMAC             BSL_SOURCE_ENC(bslSourceMymac)
#define BSL_S_NH                BSL_SOURCE_ENC(bslSourceNh)
#define BSL_S_NHV               BSL_SOURCE_ENC(bslSourceNhv)
#define BSL_S_NIF               BSL_SOURCE_ENC(bslSourceNif)
#define BSL_S_NIV               BSL_SOURCE_ENC(bslSourceNiv)
#define BSL_S_OAM               BSL_SOURCE_ENC(bslSourceOam)
#define BSL_S_OFP               BSL_SOURCE_ENC(bslSourceOfp)
#define BSL_S_OTHER             BSL_SOURCE_ENC(bslSourceOther)
#define BSL_S_PACKET            BSL_SOURCE_ENC(bslSourcePacket)
#define BSL_S_PARSER            BSL_SOURCE_ENC(bslSourceParser)
#define BSL_S_PCI               BSL_SOURCE_ENC(bslSourcePci)
#define BSL_S_PHY               BSL_SOURCE_ENC(bslSourcePhy)
#define BSL_S_PHYMOD            BSL_SOURCE_ENC(bslSourcePhymod)
#define BSL_S_PHYSIM            BSL_SOURCE_ENC(bslSourcePhysim)
#define BSL_S_PKT               BSL_SOURCE_ENC(bslSourcePkt)
#define BSL_S_PKTDATA           BSL_SOURCE_ENC(bslSourcePktdata)
#define BSL_S_PMF               BSL_SOURCE_ENC(bslSourcePmf)
#define BSL_S_POLICER           BSL_SOURCE_ENC(bslSourcePolicer)
#define BSL_S_PORT              BSL_SOURCE_ENC(bslSourcePort)
#define BSL_S_PORTS             BSL_SOURCE_ENC(bslSourcePorts)
#define BSL_S_PPC               BSL_SOURCE_ENC(bslSourcePpc)
#define BSL_S_PPD               BSL_SOURCE_ENC(bslSourcePpd)
#define BSL_S_PTP               BSL_SOURCE_ENC(bslSourcePtp)
#define BSL_S_QOS               BSL_SOURCE_ENC(bslSourceQos)
#define BSL_S_RCLOAD            BSL_SOURCE_ENC(bslSourceRcload)
#define BSL_S_RCPU              BSL_SOURCE_ENC(bslSourceRcpu)
#define BSL_S_REG               BSL_SOURCE_ENC(bslSourceReg)
#define BSL_S_REGEX             BSL_SOURCE_ENC(bslSourceRegex)
#define BSL_S_RIF               BSL_SOURCE_ENC(bslSourceRif)
#define BSL_S_RX                BSL_SOURCE_ENC(bslSourceRx)
#define BSL_S_SCHAN             BSL_SOURCE_ENC(bslSourceSchan)
#define BSL_S_SCHEDULAR         BSL_SOURCE_ENC(bslSourceSchedular)
#define BSL_S_SEMACCESS         BSL_SOURCE_ENC(bslSourceSemaccess)
#define BSL_S_SERDES            BSL_SOURCE_ENC(bslSourceSerdes)
#define BSL_S_SHELL             BSL_SOURCE_ENC(bslSourceShell)
#define BSL_S_SLB               BSL_SOURCE_ENC(bslSourceSlb)
#define BSL_S_SOCMEM            BSL_SOURCE_ENC(bslSourceSocmem)
#define BSL_S_STAT              BSL_SOURCE_ENC(bslSourceStat)
#define BSL_S_STG               BSL_SOURCE_ENC(bslSourceStg)
#define BSL_S_STK               BSL_SOURCE_ENC(bslSourceStk)
#define BSL_S_STKTASK           BSL_SOURCE_ENC(bslSourceStktask)
#define BSL_S_STKV              BSL_SOURCE_ENC(bslSourceStkv)
#define BSL_S_STP               BSL_SOURCE_ENC(bslSourceStp)
#define BSL_S_SUBPORT           BSL_SOURCE_ENC(bslSourceSubport)
#define BSL_S_SW                BSL_SOURCE_ENC(bslSourceSw)
#define BSL_S_SWDB              BSL_SOURCE_ENC(bslSourceSwdb)
#define BSL_S_SWITCH            BSL_SOURCE_ENC(bslSourceSwitch)
#define BSL_S_SYMTAB            BSL_SOURCE_ENC(bslSourceSymtab)
#define BSL_S_TBLACCESS         BSL_SOURCE_ENC(bslSourceTblaccess)
#define BSL_S_TCAM              BSL_SOURCE_ENC(bslSourceTcam)
#define BSL_S_TDM               BSL_SOURCE_ENC(bslSourceTdm)
#define BSL_S_TESTS             BSL_SOURCE_ENC(bslSourceTests)
#define BSL_S_TIME              BSL_SOURCE_ENC(bslSourceTime)
#define BSL_S_TOPOLOGY          BSL_SOURCE_ENC(bslSourceTopology)
#define BSL_S_TOPOV             BSL_SOURCE_ENC(bslSourceTopov)
#define BSL_S_TRAP              BSL_SOURCE_ENC(bslSourceTrap)
#define BSL_S_TRAPMGMT          BSL_SOURCE_ENC(bslSourceTrapmgmt)
#define BSL_S_TRILL             BSL_SOURCE_ENC(bslSourceTrill)
#define BSL_S_TRUNK             BSL_SOURCE_ENC(bslSourceTrunk)
#define BSL_S_TUNNEL            BSL_SOURCE_ENC(bslSourceTunnel)
#define BSL_S_TUNNELV           BSL_SOURCE_ENC(bslSourceTunnelv)
#define BSL_S_TX                BSL_SOURCE_ENC(bslSourceTx)
#define BSL_S_UTILS             BSL_SOURCE_ENC(bslSourceUtils)
#define BSL_S_VERINET           BSL_SOURCE_ENC(bslSourceVerinet)
#define BSL_S_VLAN              BSL_SOURCE_ENC(bslSourceVlan)
#define BSL_S_VSI               BSL_SOURCE_ENC(bslSourceVsi)
#define BSL_S_VXLAN             BSL_SOURCE_ENC(bslSourceVxlan)
#define BSL_S_WBDB              BSL_SOURCE_ENC(bslSourceWbdb)
#define BSL_S_XLMAC             BSL_SOURCE_ENC(bslSourceXlmac)

/* Combined layer/sources for Appl layer */
#define BSL_LS_APPL_ACCESSCTRLLIST      (BSL_L_APPL | BSL_S_ACCESSCTRLLIST)
#define BSL_LS_APPL_ARL                 (BSL_L_APPL | BSL_S_ARL)
#define BSL_LS_APPL_CHASSIS             (BSL_L_APPL | BSL_S_CHASSIS)
#define BSL_LS_APPL_CMIC                (BSL_L_APPL | BSL_S_CMIC)
#define BSL_LS_APPL_COMMON              (BSL_L_APPL | BSL_S_COMMON)
#define BSL_LS_APPL_COUNTER             (BSL_L_APPL | BSL_S_COUNTER)
#define BSL_LS_APPL_DMA                 (BSL_L_APPL | BSL_S_DMA)
#define BSL_LS_APPL_END                 (BSL_L_APPL | BSL_S_END)
#define BSL_LS_APPL_FABRIC              (BSL_L_APPL | BSL_S_FABRIC)
#define BSL_LS_APPL_I2C                 (BSL_L_APPL | BSL_S_I2C)
#define BSL_LS_APPL_KLIF                (BSL_L_APPL | BSL_S_KLIF)
#define BSL_LS_APPL_L2TABLE             (BSL_L_APPL | BSL_S_L2TABLE)
#define BSL_LS_APPL_L3                  (BSL_L_APPL | BSL_S_L3)
#define BSL_LS_APPL_MPLS                (BSL_L_APPL | BSL_S_MPLS)
#define BSL_LS_APPL_OTHER               (BSL_L_APPL | BSL_S_OTHER)
#define BSL_LS_APPL_PCI                 (BSL_L_APPL | BSL_S_PCI)
#define BSL_LS_APPL_PHY                 (BSL_L_APPL | BSL_S_PHY)
#define BSL_LS_APPL_PKT                 (BSL_L_APPL | BSL_S_PKT)
#define BSL_LS_APPL_PORT                (BSL_L_APPL | BSL_S_PORT)
#define BSL_LS_APPL_RCLOAD              (BSL_L_APPL | BSL_S_RCLOAD)
#define BSL_LS_APPL_REG                 (BSL_L_APPL | BSL_S_REG)
#define BSL_LS_APPL_RX                  (BSL_L_APPL | BSL_S_RX)
#define BSL_LS_APPL_SHELL               (BSL_L_APPL | BSL_S_SHELL)
#define BSL_LS_APPL_SOCMEM              (BSL_L_APPL | BSL_S_SOCMEM)
#define BSL_LS_APPL_SYMTAB              (BSL_L_APPL | BSL_S_SYMTAB)
#define BSL_LS_APPL_TESTS               (BSL_L_APPL | BSL_S_TESTS)
#define BSL_LS_APPL_TX                  (BSL_L_APPL | BSL_S_TX)

/* Combined layer/sources for Bcm layer */
#define BSL_LS_BCM_ALPM                 (BSL_L_BCM | BSL_S_ALPM)
#define BSL_LS_BCM_API                  (BSL_L_BCM | BSL_S_API)
#define BSL_LS_BCM_ARL                  (BSL_L_BCM | BSL_S_ARL)
#define BSL_LS_BCM_ATTACH               (BSL_L_BCM | BSL_S_ATTACH)
#define BSL_LS_BCM_AUTH                 (BSL_L_BCM | BSL_S_AUTH)
#define BSL_LS_BCM_BFD                  (BSL_L_BCM | BSL_S_BFD)
#define BSL_LS_BCM_CES                  (BSL_L_BCM | BSL_S_CES)
#define BSL_LS_BCM_CNT                  (BSL_L_BCM | BSL_S_CNT)
#define BSL_LS_BCM_COMMON               (BSL_L_BCM | BSL_S_COMMON)
#define BSL_LS_BCM_COSQ                 (BSL_L_BCM | BSL_S_COSQ)
#define BSL_LS_BCM_COUNTER              (BSL_L_BCM | BSL_S_COUNTER)
#define BSL_LS_BCM_DMA                  (BSL_L_BCM | BSL_S_DMA)
#define BSL_LS_BCM_ELPM                 (BSL_L_BCM | BSL_S_ELPM)
#define BSL_LS_BCM_EXTENDER             (BSL_L_BCM | BSL_S_EXTENDER)
#define BSL_LS_BCM_FABRIC               (BSL_L_BCM | BSL_S_FABRIC)
#define BSL_LS_BCM_FAILOVER             (BSL_L_BCM | BSL_S_FAILOVER)
#define BSL_LS_BCM_FCOE                 (BSL_L_BCM | BSL_S_FCOE)
#define BSL_LS_BCM_FLEXCTR              (BSL_L_BCM | BSL_S_FLEXCTR)
#define BSL_LS_BCM_FP                   (BSL_L_BCM | BSL_S_FP)
#define BSL_LS_BCM_INIT                 (BSL_L_BCM | BSL_S_INIT)
#define BSL_LS_BCM_INTR                 (BSL_L_BCM | BSL_S_INTR)
#define BSL_LS_BCM_IPFIX                (BSL_L_BCM | BSL_S_IPFIX)
#define BSL_LS_BCM_IPMC                 (BSL_L_BCM | BSL_S_IPMC)
#define BSL_LS_BCM_KNET                 (BSL_L_BCM | BSL_S_KNET)
#define BSL_LS_BCM_L2                   (BSL_L_BCM | BSL_S_L2)
#define BSL_LS_BCM_L2GRE                (BSL_L_BCM | BSL_S_L2GRE)
#define BSL_LS_BCM_L2TABLE              (BSL_L_BCM | BSL_S_L2TABLE)
#define BSL_LS_BCM_L3                   (BSL_L_BCM | BSL_S_L3)
#define BSL_LS_BCM_LINK                 (BSL_L_BCM | BSL_S_LINK)
#define BSL_LS_BCM_MACSEC               (BSL_L_BCM | BSL_S_MACSEC)
#define BSL_LS_BCM_MCAST                (BSL_L_BCM | BSL_S_MCAST)
#define BSL_LS_BCM_MEM                  (BSL_L_BCM | BSL_S_MEM)
#define BSL_LS_BCM_MIM                  (BSL_L_BCM | BSL_S_MIM)
#define BSL_LS_BCM_MIRROR               (BSL_L_BCM | BSL_S_MIRROR)
#define BSL_LS_BCM_MPLS                 (BSL_L_BCM | BSL_S_MPLS)
#define BSL_LS_BCM_MSG                  (BSL_L_BCM | BSL_S_MSG)
#define BSL_LS_BCM_MULTICAST            (BSL_L_BCM | BSL_S_MULTICAST)
#define BSL_LS_BCM_NIV                  (BSL_L_BCM | BSL_S_NIV)
#define BSL_LS_BCM_OAM                  (BSL_L_BCM | BSL_S_OAM)
#define BSL_LS_BCM_OTHER                (BSL_L_BCM | BSL_S_OTHER)
#define BSL_LS_BCM_PACKET               (BSL_L_BCM | BSL_S_PACKET)
#define BSL_LS_BCM_PHY                  (BSL_L_BCM | BSL_S_PHY)
#define BSL_LS_BCM_PKT                  (BSL_L_BCM | BSL_S_PKT)
#define BSL_LS_BCM_POLICER              (BSL_L_BCM | BSL_S_POLICER)
#define BSL_LS_BCM_PORT                 (BSL_L_BCM | BSL_S_PORT)
#define BSL_LS_BCM_PTP                  (BSL_L_BCM | BSL_S_PTP)
#define BSL_LS_BCM_QOS                  (BSL_L_BCM | BSL_S_QOS)
#define BSL_LS_BCM_RCPU                 (BSL_L_BCM | BSL_S_RCPU)
#define BSL_LS_BCM_REGEX                (BSL_L_BCM | BSL_S_REGEX)
#define BSL_LS_BCM_RX                   (BSL_L_BCM | BSL_S_RX)
#define BSL_LS_BCM_STAT                 (BSL_L_BCM | BSL_S_STAT)
#define BSL_LS_BCM_STG                  (BSL_L_BCM | BSL_S_STG)
#define BSL_LS_BCM_STK                  (BSL_L_BCM | BSL_S_STK)
#define BSL_LS_BCM_STP                  (BSL_L_BCM | BSL_S_STP)
#define BSL_LS_BCM_SUBPORT              (BSL_L_BCM | BSL_S_SUBPORT)
#define BSL_LS_BCM_SWITCH               (BSL_L_BCM | BSL_S_SWITCH)
#define BSL_LS_BCM_TESTS                (BSL_L_BCM | BSL_S_TESTS)
#define BSL_LS_BCM_TIME                 (BSL_L_BCM | BSL_S_TIME)
#define BSL_LS_BCM_TRILL                (BSL_L_BCM | BSL_S_TRILL)
#define BSL_LS_BCM_TRUNK                (BSL_L_BCM | BSL_S_TRUNK)
#define BSL_LS_BCM_TUNNEL               (BSL_L_BCM | BSL_S_TUNNEL)
#define BSL_LS_BCM_TX                   (BSL_L_BCM | BSL_S_TX)
#define BSL_LS_BCM_UTILS                (BSL_L_BCM | BSL_S_UTILS)
#define BSL_LS_BCM_VLAN                 (BSL_L_BCM | BSL_S_VLAN)
#define BSL_LS_BCM_VXLAN                (BSL_L_BCM | BSL_S_VXLAN)

/* Combined layer/sources for Bcmx layer */
#define BSL_LS_BCMX_ATTACH              (BSL_L_BCMX | BSL_S_ATTACH)
#define BSL_LS_BCMX_COMMON              (BSL_L_BCMX | BSL_S_COMMON)
#define BSL_LS_BCMX_COUNTER             (BSL_L_BCMX | BSL_S_COUNTER)
#define BSL_LS_BCMX_L2                  (BSL_L_BCMX | BSL_S_L2)
#define BSL_LS_BCMX_L3                  (BSL_L_BCMX | BSL_S_L3)
#define BSL_LS_BCMX_LINK                (BSL_L_BCMX | BSL_S_LINK)
#define BSL_LS_BCMX_OTHER               (BSL_L_BCMX | BSL_S_OTHER)
#define BSL_LS_BCMX_PKTDATA             (BSL_L_BCMX | BSL_S_PKTDATA)
#define BSL_LS_BCMX_PORT                (BSL_L_BCMX | BSL_S_PORT)
#define BSL_LS_BCMX_RX                  (BSL_L_BCMX | BSL_S_RX)
#define BSL_LS_BCMX_TX                  (BSL_L_BCMX | BSL_S_TX)
#define BSL_LS_BCMX_VLAN                (BSL_L_BCMX | BSL_S_VLAN)

/* Combined layer/sources for Board layer */
#define BSL_LS_BOARD_COMMON             (BSL_L_BOARD | BSL_S_COMMON)
#define BSL_LS_BOARD_OTHER              (BSL_L_BOARD | BSL_S_OTHER)

/* Combined layer/sources for Sal layer */
#define BSL_LS_SAL_COMMON               (BSL_L_SAL | BSL_S_COMMON)
#define BSL_LS_SAL_OTHER                (BSL_L_SAL | BSL_S_OTHER)

/* Combined layer/sources for Soc layer */
#define BSL_LS_SOC_100G                 (BSL_L_SOC | BSL_S_100G)
#define BSL_LS_SOC_10G                  (BSL_L_SOC | BSL_S_10G)
#define BSL_LS_SOC_ALPM                 (BSL_L_SOC | BSL_S_ALPM)
#define BSL_LS_SOC_ARL                  (BSL_L_SOC | BSL_S_ARL)
#define BSL_LS_SOC_ARLMON               (BSL_L_SOC | BSL_S_ARLMON)
#define BSL_LS_SOC_CHIP                 (BSL_L_SOC | BSL_S_CHIP)
#define BSL_LS_SOC_CNM                  (BSL_L_SOC | BSL_S_CNM)
#define BSL_LS_SOC_CNT                  (BSL_L_SOC | BSL_S_CNT)
#define BSL_LS_SOC_COMMON               (BSL_L_SOC | BSL_S_COMMON)
#define BSL_LS_SOC_COSQ                 (BSL_L_SOC | BSL_S_COSQ)
#define BSL_LS_SOC_COUNTER              (BSL_L_SOC | BSL_S_COUNTER)
#define BSL_LS_SOC_DDR                  (BSL_L_SOC | BSL_S_DDR)
#define BSL_LS_SOC_DIAG                 (BSL_L_SOC | BSL_S_DIAG)
#define BSL_LS_SOC_DMA                  (BSL_L_SOC | BSL_S_DMA)
#define BSL_LS_SOC_DRAM                 (BSL_L_SOC | BSL_S_DRAM)
#define BSL_LS_SOC_EGRESS               (BSL_L_SOC | BSL_S_EGRESS)
#define BSL_LS_SOC_ESM                  (BSL_L_SOC | BSL_S_ESM)
#define BSL_LS_SOC_FABRIC               (BSL_L_SOC | BSL_S_FABRIC)
#define BSL_LS_SOC_FLOWCONTROL          (BSL_L_SOC | BSL_S_FLOWCONTROL)
#define BSL_LS_SOC_FORWARD              (BSL_L_SOC | BSL_S_FORWARD)
#define BSL_LS_SOC_FP                   (BSL_L_SOC | BSL_S_FP)
#define BSL_LS_SOC_GE                   (BSL_L_SOC | BSL_S_GE)
#define BSL_LS_SOC_GENERAL              (BSL_L_SOC | BSL_S_GENERAL)
#define BSL_LS_SOC_HASH                 (BSL_L_SOC | BSL_S_HASH)
#define BSL_LS_SOC_HEADERS              (BSL_L_SOC | BSL_S_HEADERS)
#define BSL_LS_SOC_I2C                  (BSL_L_SOC | BSL_S_I2C)
#define BSL_LS_SOC_INGRESS              (BSL_L_SOC | BSL_S_INGRESS)
#define BSL_LS_SOC_INIT                 (BSL_L_SOC | BSL_S_INIT)
#define BSL_LS_SOC_INTR                 (BSL_L_SOC | BSL_S_INTR)
#define BSL_LS_SOC_KNET                 (BSL_L_SOC | BSL_S_KNET)
#define BSL_LS_SOC_L2                   (BSL_L_SOC | BSL_S_L2)
#define BSL_LS_SOC_L2TABLE              (BSL_L_SOC | BSL_S_L2TABLE)
#define BSL_LS_SOC_L3                   (BSL_L_SOC | BSL_S_L3)
#define BSL_LS_SOC_LIF                  (BSL_L_SOC | BSL_S_LIF)
#define BSL_LS_SOC_LINK                 (BSL_L_SOC | BSL_S_LINK)
#define BSL_LS_SOC_LLP                  (BSL_L_SOC | BSL_S_LLP)
#define BSL_LS_SOC_LPM                  (BSL_L_SOC | BSL_S_LPM)
#define BSL_LS_SOC_MANAGEMENT           (BSL_L_SOC | BSL_S_MANAGEMENT)
#define BSL_LS_SOC_MBIST                (BSL_L_SOC | BSL_S_MBIST)
#define BSL_LS_SOC_MCAST                (BSL_L_SOC | BSL_S_MCAST)
#define BSL_LS_SOC_MEM                  (BSL_L_SOC | BSL_S_MEM)
#define BSL_LS_SOC_MEMTUNE              (BSL_L_SOC | BSL_S_MEMTUNE)
#define BSL_LS_SOC_METERING             (BSL_L_SOC | BSL_S_METERING)
#define BSL_LS_SOC_MII                  (BSL_L_SOC | BSL_S_MII)
#define BSL_LS_SOC_MIIM                 (BSL_L_SOC | BSL_S_MIIM)
#define BSL_LS_SOC_MIRROR               (BSL_L_SOC | BSL_S_MIRROR)
#define BSL_LS_SOC_MMU                  (BSL_L_SOC | BSL_S_MMU)
#define BSL_LS_SOC_MPLS                 (BSL_L_SOC | BSL_S_MPLS)
#define BSL_LS_SOC_MSG                  (BSL_L_SOC | BSL_S_MSG)
#define BSL_LS_SOC_MULTICAST            (BSL_L_SOC | BSL_S_MULTICAST)
#define BSL_LS_SOC_OAM                  (BSL_L_SOC | BSL_S_OAM)
#define BSL_LS_SOC_OTHER                (BSL_L_SOC | BSL_S_OTHER)
#define BSL_LS_SOC_PACKET               (BSL_L_SOC | BSL_S_PACKET)
#define BSL_LS_SOC_PCI                  (BSL_L_SOC | BSL_S_PCI)
#define BSL_LS_SOC_PHY                  (BSL_L_SOC | BSL_S_PHY)
#define BSL_LS_SOC_PHYMOD               (BSL_L_SOC | BSL_S_PHYMOD)
#define BSL_LS_SOC_PHYSIM               (BSL_L_SOC | BSL_S_PHYSIM)
#define BSL_LS_SOC_PKT                  (BSL_L_SOC | BSL_S_PKT)
#define BSL_LS_SOC_PORT                 (BSL_L_SOC | BSL_S_PORT)
#define BSL_LS_SOC_PPC                  (BSL_L_SOC | BSL_S_PPC)
#define BSL_LS_SOC_PPD                  (BSL_L_SOC | BSL_S_PPD)
#define BSL_LS_SOC_PTP                  (BSL_L_SOC | BSL_S_PTP)
#define BSL_LS_SOC_RCPU                 (BSL_L_SOC | BSL_S_RCPU)
#define BSL_LS_SOC_REG                  (BSL_L_SOC | BSL_S_REG)
#define BSL_LS_SOC_SCHAN                (BSL_L_SOC | BSL_S_SCHAN)
#define BSL_LS_SOC_SLB                  (BSL_L_SOC | BSL_S_SLB)
#define BSL_LS_SOC_SOCMEM               (BSL_L_SOC | BSL_S_SOCMEM)
#define BSL_LS_SOC_STAT                 (BSL_L_SOC | BSL_S_STAT)
#define BSL_LS_SOC_STK                  (BSL_L_SOC | BSL_S_STK)
#define BSL_LS_SOC_STP                  (BSL_L_SOC | BSL_S_STP)
#define BSL_LS_SOC_SWDB                 (BSL_L_SOC | BSL_S_SWDB)
#define BSL_LS_SOC_TCAM                 (BSL_L_SOC | BSL_S_TCAM)
#define BSL_LS_SOC_TDM                  (BSL_L_SOC | BSL_S_TDM)
#define BSL_LS_SOC_TESTS                (BSL_L_SOC | BSL_S_TESTS)
#define BSL_LS_SOC_TRAP                 (BSL_L_SOC | BSL_S_TRAP)
#define BSL_LS_SOC_TRUNK                (BSL_L_SOC | BSL_S_TRUNK)
#define BSL_LS_SOC_TX                   (BSL_L_SOC | BSL_S_TX)
#define BSL_LS_SOC_VLAN                 (BSL_L_SOC | BSL_S_VLAN)
#define BSL_LS_SOC_VSI                  (BSL_L_SOC | BSL_S_VSI)
#define BSL_LS_SOC_XLMAC                (BSL_L_SOC | BSL_S_XLMAC)

/* Combined layer/sources for Socdnx layer */
#define BSL_LS_SOCDNX_ACTIONCMD         (BSL_L_SOCDNX | BSL_S_ACTIONCMD)
#define BSL_LS_SOCDNX_CEINSTRUCTIONS    (BSL_L_SOCDNX | BSL_S_CEINSTRUCTIONS)
#define BSL_LS_SOCDNX_CELL              (BSL_L_SOCDNX | BSL_S_CELL)
#define BSL_LS_SOCDNX_CHIP              (BSL_L_SOCDNX | BSL_S_CHIP)
#define BSL_LS_SOCDNX_CNM               (BSL_L_SOCDNX | BSL_S_CNM)
#define BSL_LS_SOCDNX_CNT               (BSL_L_SOCDNX | BSL_S_CNT)
#define BSL_LS_SOCDNX_COSQ              (BSL_L_SOCDNX | BSL_S_COSQ)
#define BSL_LS_SOCDNX_DIAGNOSTICS       (BSL_L_SOCDNX | BSL_S_DIAGNOSTICS)
#define BSL_LS_SOCDNX_DRAM              (BSL_L_SOCDNX | BSL_S_DRAM)
#define BSL_LS_SOCDNX_EGRESS            (BSL_L_SOCDNX | BSL_S_EGRESS)
#define BSL_LS_SOCDNX_ESEMACCESS        (BSL_L_SOCDNX | BSL_S_ESEMACCESS)
#define BSL_LS_SOCDNX_FABRIC            (BSL_L_SOCDNX | BSL_S_FABRIC)
#define BSL_LS_SOCDNX_FLOWCONTROL       (BSL_L_SOCDNX | BSL_S_FLOWCONTROL)
#define BSL_LS_SOCDNX_FORWARD           (BSL_L_SOCDNX | BSL_S_FORWARD)
#define BSL_LS_SOCDNX_FP                (BSL_L_SOCDNX | BSL_S_FP)
#define BSL_LS_SOCDNX_FRAMEWORK         (BSL_L_SOCDNX | BSL_S_FRAMEWORK)
#define BSL_LS_SOCDNX_GENERAL           (BSL_L_SOCDNX | BSL_S_GENERAL)
#define BSL_LS_SOCDNX_HEADERS           (BSL_L_SOCDNX | BSL_S_HEADERS)
#define BSL_LS_SOCDNX_HWDEBUG           (BSL_L_SOCDNX | BSL_S_HWDEBUG)
#define BSL_LS_SOCDNX_INGRESS           (BSL_L_SOCDNX | BSL_S_INGRESS)
#define BSL_LS_SOCDNX_INIT              (BSL_L_SOCDNX | BSL_S_INIT)
#define BSL_LS_SOCDNX_INTERRUPTS        (BSL_L_SOCDNX | BSL_S_INTERRUPTS)
#define BSL_LS_SOCDNX_L3SRCBIND         (BSL_L_SOCDNX | BSL_S_L3SRCBIND)
#define BSL_LS_SOCDNX_LAG               (BSL_L_SOCDNX | BSL_S_LAG)
#define BSL_LS_SOCDNX_LEMACCESS         (BSL_L_SOCDNX | BSL_S_LEMACCESS)
#define BSL_LS_SOCDNX_LIF               (BSL_L_SOCDNX | BSL_S_LIF)
#define BSL_LS_SOCDNX_LLP               (BSL_L_SOCDNX | BSL_S_LLP)
#define BSL_LS_SOCDNX_LOADBALANCING     (BSL_L_SOCDNX | BSL_S_LOADBALANCING)
#define BSL_LS_SOCDNX_MANAGMENT         (BSL_L_SOCDNX | BSL_S_MANAGMENT)
#define BSL_LS_SOCDNX_MBIST             (BSL_L_SOCDNX | BSL_S_MBIST)
#define BSL_LS_SOCDNX_MEM               (BSL_L_SOCDNX | BSL_S_MEM)
#define BSL_LS_SOCDNX_METERING          (BSL_L_SOCDNX | BSL_S_METERING)
#define BSL_LS_SOCDNX_MPLS              (BSL_L_SOCDNX | BSL_S_MPLS)
#define BSL_LS_SOCDNX_MULTICAST         (BSL_L_SOCDNX | BSL_S_MULTICAST)
#define BSL_LS_SOCDNX_MYMAC             (BSL_L_SOCDNX | BSL_S_MYMAC)
#define BSL_LS_SOCDNX_NIF               (BSL_L_SOCDNX | BSL_S_NIF)
#define BSL_LS_SOCDNX_OAM               (BSL_L_SOCDNX | BSL_S_OAM)
#define BSL_LS_SOCDNX_OFP               (BSL_L_SOCDNX | BSL_S_OFP)
#define BSL_LS_SOCDNX_PARSER            (BSL_L_SOCDNX | BSL_S_PARSER)
#define BSL_LS_SOCDNX_PKT               (BSL_L_SOCDNX | BSL_S_PKT)
#define BSL_LS_SOCDNX_PMF               (BSL_L_SOCDNX | BSL_S_PMF)
#define BSL_LS_SOCDNX_PORTS             (BSL_L_SOCDNX | BSL_S_PORTS)
#define BSL_LS_SOCDNX_PPC               (BSL_L_SOCDNX | BSL_S_PPC)
#define BSL_LS_SOCDNX_PPD               (BSL_L_SOCDNX | BSL_S_PPD)
#define BSL_LS_SOCDNX_PTP               (BSL_L_SOCDNX | BSL_S_PTP)
#define BSL_LS_SOCDNX_REG               (BSL_L_SOCDNX | BSL_S_REG)
#define BSL_LS_SOCDNX_RIF               (BSL_L_SOCDNX | BSL_S_RIF)
#define BSL_LS_SOCDNX_SCHEDULAR         (BSL_L_SOCDNX | BSL_S_SCHEDULAR)
#define BSL_LS_SOCDNX_SEMACCESS         (BSL_L_SOCDNX | BSL_S_SEMACCESS)
#define BSL_LS_SOCDNX_SERDES            (BSL_L_SOCDNX | BSL_S_SERDES)
#define BSL_LS_SOCDNX_STAT              (BSL_L_SOCDNX | BSL_S_STAT)
#define BSL_LS_SOCDNX_SW                (BSL_L_SOCDNX | BSL_S_SW)
#define BSL_LS_SOCDNX_TBLACCESS         (BSL_L_SOCDNX | BSL_S_TBLACCESS)
#define BSL_LS_SOCDNX_TCAM              (BSL_L_SOCDNX | BSL_S_TCAM)
#define BSL_LS_SOCDNX_TDM               (BSL_L_SOCDNX | BSL_S_TDM)
#define BSL_LS_SOCDNX_TRAPMGMT          (BSL_L_SOCDNX | BSL_S_TRAPMGMT)
#define BSL_LS_SOCDNX_VSI               (BSL_L_SOCDNX | BSL_S_VSI)
#define BSL_LS_SOCDNX_WBDB              (BSL_L_SOCDNX | BSL_S_WBDB)

/* Combined layer/sources for Sys layer */
#define BSL_LS_SYS_DMA                  (BSL_L_SYS | BSL_S_DMA)
#define BSL_LS_SYS_END                  (BSL_L_SYS | BSL_S_END)
#define BSL_LS_SYS_PCI                  (BSL_L_SYS | BSL_S_PCI)
#define BSL_LS_SYS_VERINET              (BSL_L_SYS | BSL_S_VERINET)

/* Combined layer/sources for Tks layer */
#define BSL_LS_TKS_ATP                  (BSL_L_TKS | BSL_S_ATP)
#define BSL_LS_TKS_ATPV                 (BSL_L_TKS | BSL_S_ATPV)
#define BSL_LS_TKS_C2C                  (BSL_L_TKS | BSL_S_C2C)
#define BSL_LS_TKS_C2CV                 (BSL_L_TKS | BSL_S_C2CV)
#define BSL_LS_TKS_COMMON               (BSL_L_TKS | BSL_S_COMMON)
#define BSL_LS_TKS_CTPKT                (BSL_L_TKS | BSL_S_CTPKT)
#define BSL_LS_TKS_CTPKTV               (BSL_L_TKS | BSL_S_CTPKTV)
#define BSL_LS_TKS_DISCOVER             (BSL_L_TKS | BSL_S_DISCOVER)
#define BSL_LS_TKS_DISCV                (BSL_L_TKS | BSL_S_DISCV)
#define BSL_LS_TKS_NH                   (BSL_L_TKS | BSL_S_NH)
#define BSL_LS_TKS_NHV                  (BSL_L_TKS | BSL_S_NHV)
#define BSL_LS_TKS_OTHER                (BSL_L_TKS | BSL_S_OTHER)
#define BSL_LS_TKS_STKTASK              (BSL_L_TKS | BSL_S_STKTASK)
#define BSL_LS_TKS_STKV                 (BSL_L_TKS | BSL_S_STKV)
#define BSL_LS_TKS_TOPOLOGY             (BSL_L_TKS | BSL_S_TOPOLOGY)
#define BSL_LS_TKS_TOPOV                (BSL_L_TKS | BSL_S_TOPOV)
#define BSL_LS_TKS_TUNNEL               (BSL_L_TKS | BSL_S_TUNNEL)
#define BSL_LS_TKS_TUNNELV              (BSL_L_TKS | BSL_S_TUNNELV)
#define BSL_LS_TKS_TX                   (BSL_L_TKS | BSL_S_TX)

#define BSL_SOURCES_VALID_DEF(type_) \
static type_ bsl_source_appl_valid[] = BSL_SOURCE_APPL_VALID_INIT; \
static type_ bsl_source_bcm_valid[] = BSL_SOURCE_BCM_VALID_INIT; \
static type_ bsl_source_bcmx_valid[] = BSL_SOURCE_BCMX_VALID_INIT; \
static type_ bsl_source_board_valid[] = BSL_SOURCE_BOARD_VALID_INIT; \
static type_ bsl_source_sal_valid[] = BSL_SOURCE_SAL_VALID_INIT; \
static type_ bsl_source_soc_valid[] = BSL_SOURCE_SOC_VALID_INIT; \
static type_ bsl_source_socdnx_valid[] = BSL_SOURCE_SOCDNX_VALID_INIT; \
static type_ bsl_source_sys_valid[] = BSL_SOURCE_SYS_VALID_INIT; \
static type_ bsl_source_tks_valid[] = BSL_SOURCE_TKS_VALID_INIT


#define BSL_SOURCES_VALID_INIT { \
    bsl_source_appl_valid, \
    bsl_source_bcm_valid, \
    bsl_source_bcmx_valid, \
    bsl_source_board_valid, \
    bsl_source_sal_valid, \
    bsl_source_soc_valid, \
    bsl_source_socdnx_valid, \
    bsl_source_sys_valid, \
    bsl_source_tks_valid, \
    NULL \
}

#endif /* __SHR_BSLENUM_H__ */
