/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _PHYMOD_DISPATCH_H__H_
#define _PHYMOD_DISPATCH_H__H_

#include <phymod/phymod_definitions.h>
#include <phymod/phymod.h>

typedef int (*__dispatch__phymod_core_identify_f)(const phymod_core_access_t* core, uint32_t core_id, uint32_t* is_identified);
typedef int (*__dispatch__phymod_core_info_get_f)(const phymod_core_access_t* core, phymod_core_info_t* info);
typedef int (*__dispatch__phymod_core_lane_map_set_f)(const phymod_core_access_t* core, const phymod_lane_map_t* lane_map);
typedef int (*__dispatch__phymod_core_lane_map_get_f)(const phymod_core_access_t* core, phymod_lane_map_t* lane_map);
typedef int (*__dispatch__phymod_core_reset_set_f)(const phymod_core_access_t* core, phymod_reset_mode_t reset_mode, phymod_reset_direction_t direction);
typedef int (*__dispatch__phymod_core_reset_get_f)(const phymod_core_access_t* core, phymod_reset_mode_t reset_mode, phymod_reset_direction_t* direction);
typedef int (*__dispatch__phymod_core_firmware_info_get_f)(const phymod_core_access_t* core, phymod_core_firmware_info_t* fw_info);
typedef int (*__dispatch__phymod_phy_firmware_core_config_set_f)(const phymod_phy_access_t* phy, phymod_firmware_core_config_t fw_core_config);
typedef int (*__dispatch__phymod_phy_firmware_core_config_get_f)(const phymod_phy_access_t* phy, phymod_firmware_core_config_t* fw_core_config);
typedef int (*__dispatch__phymod_phy_firmware_lane_config_set_f)(const phymod_phy_access_t* phy, phymod_firmware_lane_config_t fw_lane_config);
typedef int (*__dispatch__phymod_phy_firmware_lane_config_get_f)(const phymod_phy_access_t* phy, phymod_firmware_lane_config_t* fw_lane_config);
typedef int (*__dispatch__phymod_core_pll_sequencer_restart_f)(const phymod_core_access_t* core, uint32_t flags, phymod_sequencer_operation_t operation);
typedef int (*__dispatch__phymod_core_wait_event_f)(const phymod_core_access_t* core, phymod_core_event_t event, uint32_t timeout);
typedef int (*__dispatch__phymod_phy_rx_restart_f)(const phymod_phy_access_t* phy);
typedef int (*__dispatch__phymod_phy_polarity_set_f)(const phymod_phy_access_t* phy, const phymod_polarity_t* polarity);
typedef int (*__dispatch__phymod_phy_polarity_get_f)(const phymod_phy_access_t* phy, phymod_polarity_t* polarity);
typedef int (*__dispatch__phymod_phy_tx_set_f)(const phymod_phy_access_t* phy, const phymod_tx_t* tx);
typedef int (*__dispatch__phymod_phy_tx_get_f)(const phymod_phy_access_t* phy, phymod_tx_t* tx);
typedef int (*__dispatch__phymod_phy_media_type_tx_get_f)(const phymod_phy_access_t* phy, phymod_media_typed_t media, phymod_tx_t* tx);
typedef int (*__dispatch__phymod_phy_tx_override_set_f)(const phymod_phy_access_t* phy, const phymod_tx_override_t* tx_override);
typedef int (*__dispatch__phymod_phy_tx_override_get_f)(const phymod_phy_access_t* phy, phymod_tx_override_t* tx_override);
typedef int (*__dispatch__phymod_phy_rx_set_f)(const phymod_phy_access_t* phy, const phymod_rx_t* rx);
typedef int (*__dispatch__phymod_phy_rx_get_f)(const phymod_phy_access_t* phy, phymod_rx_t* rx);
typedef int (*__dispatch__phymod_phy_reset_set_f)(const phymod_phy_access_t* phy, const phymod_phy_reset_t* reset);
typedef int (*__dispatch__phymod_phy_reset_get_f)(const phymod_phy_access_t* phy, phymod_phy_reset_t* reset);
typedef int (*__dispatch__phymod_phy_power_set_f)(const phymod_phy_access_t* phy, const phymod_phy_power_t* power);
typedef int (*__dispatch__phymod_phy_power_get_f)(const phymod_phy_access_t* phy, phymod_phy_power_t* power);
typedef int (*__dispatch__phymod_phy_tx_lane_control_set_f)(const phymod_phy_access_t* phy, uint32_t enable);
typedef int (*__dispatch__phymod_phy_tx_lane_control_get_f)(const phymod_phy_access_t* phy, uint32_t* enable);
typedef int (*__dispatch__phymod_phy_rx_lane_control_set_f)(const phymod_phy_access_t* phy, uint32_t enable);
typedef int (*__dispatch__phymod_phy_rx_lane_control_get_f)(const phymod_phy_access_t* phy, uint32_t* enable);
typedef int (*__dispatch__phymod_phy_fec_enable_set_f)(const phymod_phy_access_t* phy, uint32_t enable);
typedef int (*__dispatch__phymod_phy_fec_enable_get_f)(const phymod_phy_access_t* phy, uint32_t* enable);
typedef int (*__dispatch__phymod_phy_interface_config_set_f)(const phymod_phy_access_t* phy, uint32_t flags, const phymod_phy_inf_config_t* config);
typedef int (*__dispatch__phymod_phy_interface_config_get_f)(const phymod_phy_access_t* phy, uint32_t flags, phymod_phy_inf_config_t* config);
typedef int (*__dispatch__phymod_phy_cl72_set_f)(const phymod_phy_access_t* phy, uint32_t cl72_en);
typedef int (*__dispatch__phymod_phy_cl72_get_f)(const phymod_phy_access_t* phy, uint32_t* cl72_en);
typedef int (*__dispatch__phymod_phy_cl72_status_get_f)(const phymod_phy_access_t* phy, phymod_cl72_status_t* status);
typedef int (*__dispatch__phymod_phy_autoneg_ability_set_f)(const phymod_phy_access_t* phy, const phymod_autoneg_ability_t* an_ability_set_type);
typedef int (*__dispatch__phymod_phy_autoneg_ability_get_f)(const phymod_phy_access_t* phy, phymod_autoneg_ability_t* an_ability_get_type);
typedef int (*__dispatch__phymod_phy_autoneg_remote_ability_get_f)(const phymod_phy_access_t* phy, phymod_autoneg_ability_t* an_ability_get_type);
typedef int (*__dispatch__phymod_phy_autoneg_set_f)(const phymod_phy_access_t* phy, const phymod_autoneg_control_t* an);
typedef int (*__dispatch__phymod_phy_autoneg_get_f)(const phymod_phy_access_t* phy, phymod_autoneg_control_t* an, uint32_t* an_done);
typedef int (*__dispatch__phymod_phy_autoneg_status_get_f)(const phymod_phy_access_t* phy, phymod_autoneg_status_t* status);
typedef int (*__dispatch__phymod_core_init_f)(const phymod_core_access_t* core, const phymod_core_init_config_t* init_config, const phymod_core_status_t* core_status);
typedef int (*__dispatch__phymod_phy_init_f)(const phymod_phy_access_t* phy, const phymod_phy_init_config_t* init_config);
typedef int (*__dispatch__phymod_phy_loopback_set_f)(const phymod_phy_access_t* phy, phymod_loopback_mode_t loopback, uint32_t enable);
typedef int (*__dispatch__phymod_phy_loopback_get_f)(const phymod_phy_access_t* phy, phymod_loopback_mode_t loopback, uint32_t* enable);
typedef int (*__dispatch__phymod_phy_rx_pmd_locked_get_f)(const phymod_phy_access_t* phy, uint32_t* rx_pmd_locked);
typedef int (*__dispatch__phymod_phy_link_status_get_f)(const phymod_phy_access_t* phy, uint32_t* link_status);
typedef int (*__dispatch__phymod_phy_status_dump_f)(const phymod_phy_access_t* phy);
typedef int (*__dispatch__phymod_phy_pcs_userspeed_set_f)(const phymod_phy_access_t* phy, const phymod_pcs_userspeed_config_t* config);
typedef int (*__dispatch__phymod_phy_pcs_userspeed_get_f)(const phymod_phy_access_t* phy, phymod_pcs_userspeed_config_t* config);
typedef int (*__dispatch__phymod_phy_reg_read_f)(const phymod_phy_access_t* phy, uint32_t reg_addr, uint32_t* val);
typedef int (*__dispatch__phymod_phy_reg_write_f)(const phymod_phy_access_t* phy, uint32_t reg_addr, uint32_t val);

typedef struct __phymod__dispatch__s__ {
    __dispatch__phymod_core_identify_f                                               f_phymod_core_identify;
    __dispatch__phymod_core_info_get_f                                               f_phymod_core_info_get;
    __dispatch__phymod_core_lane_map_set_f                                           f_phymod_core_lane_map_set;
    __dispatch__phymod_core_lane_map_get_f                                           f_phymod_core_lane_map_get;
    __dispatch__phymod_core_reset_set_f                                              f_phymod_core_reset_set;
    __dispatch__phymod_core_reset_get_f                                              f_phymod_core_reset_get;
    __dispatch__phymod_core_firmware_info_get_f                                      f_phymod_core_firmware_info_get;
    __dispatch__phymod_phy_firmware_core_config_set_f                                f_phymod_phy_firmware_core_config_set;
    __dispatch__phymod_phy_firmware_core_config_get_f                                f_phymod_phy_firmware_core_config_get;
    __dispatch__phymod_phy_firmware_lane_config_set_f                                f_phymod_phy_firmware_lane_config_set;
    __dispatch__phymod_phy_firmware_lane_config_get_f                                f_phymod_phy_firmware_lane_config_get;
    __dispatch__phymod_core_pll_sequencer_restart_f                                  f_phymod_core_pll_sequencer_restart;
    __dispatch__phymod_core_wait_event_f                                             f_phymod_core_wait_event;
    __dispatch__phymod_phy_rx_restart_f                                              f_phymod_phy_rx_restart;
    __dispatch__phymod_phy_polarity_set_f                                            f_phymod_phy_polarity_set;
    __dispatch__phymod_phy_polarity_get_f                                            f_phymod_phy_polarity_get;
    __dispatch__phymod_phy_tx_set_f                                                  f_phymod_phy_tx_set;
    __dispatch__phymod_phy_tx_get_f                                                  f_phymod_phy_tx_get;
    __dispatch__phymod_phy_media_type_tx_get_f                                       f_phymod_phy_media_type_tx_get;
    __dispatch__phymod_phy_tx_override_set_f                                         f_phymod_phy_tx_override_set;
    __dispatch__phymod_phy_tx_override_get_f                                         f_phymod_phy_tx_override_get;
    __dispatch__phymod_phy_rx_set_f                                                  f_phymod_phy_rx_set;
    __dispatch__phymod_phy_rx_get_f                                                  f_phymod_phy_rx_get;
    __dispatch__phymod_phy_reset_set_f                                               f_phymod_phy_reset_set;
    __dispatch__phymod_phy_reset_get_f                                               f_phymod_phy_reset_get;
    __dispatch__phymod_phy_power_set_f                                               f_phymod_phy_power_set;
    __dispatch__phymod_phy_power_get_f                                               f_phymod_phy_power_get;
    __dispatch__phymod_phy_tx_lane_control_set_f                                     f_phymod_phy_tx_lane_control_set;
    __dispatch__phymod_phy_tx_lane_control_get_f                                     f_phymod_phy_tx_lane_control_get;
    __dispatch__phymod_phy_rx_lane_control_set_f                                     f_phymod_phy_rx_lane_control_set;
    __dispatch__phymod_phy_rx_lane_control_get_f                                     f_phymod_phy_rx_lane_control_get;
    __dispatch__phymod_phy_fec_enable_set_f                                          f_phymod_phy_fec_enable_set;
    __dispatch__phymod_phy_fec_enable_get_f                                          f_phymod_phy_fec_enable_get;
    __dispatch__phymod_phy_interface_config_set_f                                    f_phymod_phy_interface_config_set;
    __dispatch__phymod_phy_interface_config_get_f                                    f_phymod_phy_interface_config_get;
    __dispatch__phymod_phy_cl72_set_f                                                f_phymod_phy_cl72_set;
    __dispatch__phymod_phy_cl72_get_f                                                f_phymod_phy_cl72_get;
    __dispatch__phymod_phy_cl72_status_get_f                                         f_phymod_phy_cl72_status_get;
    __dispatch__phymod_phy_autoneg_ability_set_f                                     f_phymod_phy_autoneg_ability_set;
    __dispatch__phymod_phy_autoneg_ability_get_f                                     f_phymod_phy_autoneg_ability_get;
    __dispatch__phymod_phy_autoneg_remote_ability_get_f                              f_phymod_phy_autoneg_remote_ability_get;
    __dispatch__phymod_phy_autoneg_set_f                                             f_phymod_phy_autoneg_set;
    __dispatch__phymod_phy_autoneg_get_f                                             f_phymod_phy_autoneg_get;
    __dispatch__phymod_phy_autoneg_status_get_f                                      f_phymod_phy_autoneg_status_get;
    __dispatch__phymod_core_init_f                                                   f_phymod_core_init;
    __dispatch__phymod_phy_init_f                                                    f_phymod_phy_init;
    __dispatch__phymod_phy_loopback_set_f                                            f_phymod_phy_loopback_set;
    __dispatch__phymod_phy_loopback_get_f                                            f_phymod_phy_loopback_get;
    __dispatch__phymod_phy_rx_pmd_locked_get_f                                       f_phymod_phy_rx_pmd_locked_get;
    __dispatch__phymod_phy_link_status_get_f                                         f_phymod_phy_link_status_get;
    __dispatch__phymod_phy_status_dump_f                                             f_phymod_phy_status_dump;
    __dispatch__phymod_phy_pcs_userspeed_set_f                                       f_phymod_phy_pcs_userspeed_set;
    __dispatch__phymod_phy_pcs_userspeed_get_f                                       f_phymod_phy_pcs_userspeed_get;
    __dispatch__phymod_phy_reg_read_f                                                f_phymod_phy_reg_read;
    __dispatch__phymod_phy_reg_write_f                                               f_phymod_phy_reg_write;
} __phymod__dispatch__t__;

extern __phymod__dispatch__t__* __phymod__dispatch__[phymodDispatchTypeCount];

#endif /*_PHYMOD_DISPATCH_H_*/
