/*
 * $Id: 280c0d11c48b3da0dc6144849c19a18f41acc96c $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __BCMX_OAM_H__
#define __BCMX_OAM_H__

#include <bcm/types.h>
#include <bcmx/bcmx.h>
#include <bcm/oam.h>

typedef bcm_oam_group_info_t bcmx_oam_group_info_t;

typedef bcm_oam_endpoint_info_t bcmx_oam_endpoint_info_t;

/* Initialize an OAM group info structure */
extern void bcmx_oam_group_info_t_init(
    bcmx_oam_group_info_t *group_info);

/* Initialize an OAM endpoint info structure */
extern void bcmx_oam_endpoint_info_t_init(
    bcmx_oam_endpoint_info_t *endpoint_info);

/* Initialize the OAM subsystem */
extern int bcmx_oam_init(void);

/* Shut down the OAM subsystem */
extern int bcmx_oam_detach(void);

/* Create or replace an OAM group object */
extern int bcmx_oam_group_create(
    bcmx_oam_group_info_t *group_info);

/* Get an OAM group object */
extern int bcmx_oam_group_get(
    bcm_oam_group_t group, 
    bcmx_oam_group_info_t *group_info);

/* 
 * Destroy an OAM group object.  All OAM endpoints associated with the
 * group will also be destroyed.
 */
extern int bcmx_oam_group_destroy(
    bcm_oam_group_t group);

/* 
 * Destroy all OAM group objects.  All OAM endpoints will also be
 * destroyed.
 */
extern int bcmx_oam_group_destroy_all(void);

/* Create or replace an OAM endpoint object */
extern int bcmx_oam_endpoint_create(
    bcmx_oam_endpoint_info_t *endpoint_info);

/* Get an OAM endpoint object */
extern int bcmx_oam_endpoint_get(
    bcm_oam_endpoint_t endpoint, 
    bcmx_oam_endpoint_info_t *endpoint_info);

/* Destroy an OAM endpoint object */
extern int bcmx_oam_endpoint_destroy(
    bcm_oam_endpoint_t endpoint);

/* Destroy all OAM endpoint objects associated with a given OAM group */
extern int bcmx_oam_endpoint_destroy_all(
    bcm_oam_group_t group);

#endif /* __BCMX_OAM_H__ */
