/*
 * $Id: f4d26f0c0a8abfa836af2157443ed8b80a98acab $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __BCM_UDF_H__
#define __BCM_UDF_H__

#include <bcm/types.h>
#include <bcm/field.h>

/* Options to control UDF allocation */
#define BCM_UDF_CREATE_O_NONE           (0)        /* Default. */
#define BCM_UDF_CREATE_O_WITHID         (1 << 0)   /* Use input UDF ID instead
                                                      of allocating one. */
#define BCM_UDF_CREATE_O_REPLACE        (1 << 1)   /* Replace/Update existing
                                                      UDF object. */
#define BCM_UDF_CREATE_O_FLEXHASH       (1 << 2)   /* UDF allocation will be
                                                      adjusted for use by flex
                                                      hashing feature. */
#define BCM_UDF_CREATE_O_FIELD_INGRESS  (1 << 3)   /* UDF allocation will be
                                                      adjusted for use by
                                                      Ingress stage FP. */
#define BCM_UDF_CREATE_O_FIELD_LOOKUP   (1 << 4)   /* UDF allocation will be
                                                      adjusted for use by Lookup
                                                      stage FP. */
#define BCM_UDF_CREATE_O_SHARED_HWID    (1 << 5)   /* Use same hardware
                                                      resources as 'shared_udf' */

/* UDF Packet Format Options */
#define BCM_UDF_PKT_FORMAT_CREATE_O_NONE    0          /* Default. */
#define BCM_UDF_PKT_FORMAT_CREATE_O_WITHID  (1 << 0)   /* Create packet format
                                                          with given ID */
#define BCM_UDF_PKT_FORMAT_CREATE_O_REPLACE (1 << 1)   /* Update existing packet
                                                          format */

/* Packet format options */
typedef uint32 bcm_udf_pkt_format_options_t;

/* Flags to be used with bcm_udf_t.flags */
#define BCM_UDF_F_ADJUST_IP4_OPTIONS    (1 << 1)   /* Adjust offset accounting
                                                      IP4 options */
#define BCM_UDF_F_ADJUST_IP6_OPTIONS    (1 << 2)   /* Adjust offset accounting
                                                      IP6 Extension Headers */

/* Base header the switch can parse. */
typedef enum bcm_udf_layer_e {
    bcmUdfLayerL2Header = 1,        /* Start of L2 header in the Packet */
    bcmUdfLayerL3OuterHeader = 2,   /* Start of outer L3 header in the packet */
    bcmUdfLayerL3InnerHeader = 3,   /* Start of inner L3 header in the packet */
    bcmUdfLayerL4OuterHeader = 4,   /* Start of outer L4 header in the packet */
    bcmUdfLayerL4InnerHeader = 5,   /* Start of outer L4 header in the packet */
    bcmUdfLayerHigigHeader = 6,     /* Start of Higig header in the packet */
    bcmUdfLayerHigig2Header = 7,    /* Start of Higig2 header in the packet */
    bcmUdfLayerTunnelHeader = 8,    /* Start of outermost tunnel header in the
                                       Packet */
    bcmUdfLayerTunnelPayload = 9,   /* Start of outermost tunnel payload in the
                                       Packet */
    bcmUdfLayerUserPayload = 10,    /* Start of application payload in the
                                       Packet. */
    bcmUdfLayerCount                /* Unused. Always last in the list */
} bcm_udf_layer_t;

#define BCM_UDF_LAYER \
{ \
    "L2Header", \
    "L3OuterHeader", \
    "L3InnerHeader", \
    "L4OuterHeader", \
    "L4InnerHeader", \
    "HigigHeader", \
    "Higig2Header", \
    "TunnelHeader", \
    "TunnelPayload", \
    "UserPayload"  \
}

/* UDF structure. */
typedef struct bcm_udf_s {
    uint32 flags;           /* See BCM_UDF_F_XXX */
    bcm_udf_layer_t layer;  /* UDF base offset. bcmUdfLayerXxx */
    int start;              /* Relative offset in bits (from the 'layer') in the
                               packet */
    uint32 width;           /* width of data in bits to extract */
} bcm_udf_t;

/* UDF allocation hints. */
typedef struct bcm_udf_alloc_hints_s {
    uint32 flags;               /* See BCM_UDF_CREATE_O_xxx */
    bcm_udf_id_t shared_udf;    /* Used when BCM_UDF_CREATE_O_SHARED_HWID is set */
    bcm_field_qset_t qset;      /* Field group qset for optimal H/W resource
                                   allocation */
} bcm_udf_alloc_hints_t;

/* Packet format based UDF specification structure. */
typedef struct bcm_udf_pkt_format_info_s {
    int prio;                       /* Priority of the UDF */
    bcm_ethertype_t ethertype;      /* Ethertype in the packet */
    bcm_ethertype_t ethertype_mask; /* Ethertype Mask */
    uint8 ip_protocol;              /* IP protocol field in the packet */
    uint8 ip_protocol_mask;         /* IP protocol Mask */
    uint16 l2;                      /* L2 packet format. (BCM_PKT_FORMAT_L2_XXX) */
    uint16 vlan_tag;                /* Vlan tag format.
                                       (BCM_PKT_FORMAT_VLAN_XXX) */
    uint16 outer_ip;                /* Outer IP header type.
                                       (BCM_PKT_FORMAT_IP_XXX) */
    uint16 inner_ip;                /* Inner IP header type.
                                       (BCM_PKT_FORMAT_IP_XXX) */
    uint16 tunnel;                  /* Tunnel type. (BCM_PKT_FORMAT_TUNNEL_XXX) */
    uint16 mpls;                    /* Mpls labels. (BCM_PKT_FORMAT_MPLS_XXX) */
    uint16 fibre_chan_outer;        /* Fibre Channel outer header type.
                                       (BCM_PKT_FORMAT_FIBRE_CHAN_XXX) */
    uint16 fibre_chan_inner;        /* Fibre Channel inner header
                                       type.(BCM_PKT_FORMAT_FIBRE_CHAN_XXX) */
    uint16 higig;                   /* HIGIG packet
                                       format.(BCM_PKT_FORMAT_HIGIG_XXX) */
    uint16 vntag;                   /* NIV packet
                                       format.(BCM_PKT_FORMAT_VNTAG_XXX) */
    uint16 etag;                    /* Extender tag packet
                                       format.(BCM_PKT_FORMAT_ETAG_XXX) */
    uint16 cntag;                   /* CNTAG packet
                                       format.(BCM_PKT_FORMAT_CNTAG_XXX) */
    uint16 icnm;                    /* ICNM packet
                                       format.(BCM_PKT_FORMAT_ICNM_XXX) */
} bcm_udf_pkt_format_info_t;

/* Initializes the UDF structure */
extern void bcm_udf_t_init(
    bcm_udf_t *udf_info);

/* Initializes the UDF alloc hints structure */
extern void bcm_udf_alloc_hints_t_init(
    bcm_udf_alloc_hints_t *udf_hints);

/* Initialize the UDF packet format structure */
extern void bcm_udf_pkt_format_info_t_init(
    bcm_udf_pkt_format_info_t *pkt_format);

#ifndef BCM_HIDE_DISPATCHABLE

/* Initialize UDF module */
extern int bcm_udf_init(
    int unit);

/* Detach UDF module */
extern int bcm_udf_detach(
    int unit);

/* Creates a UDF object */
extern int bcm_udf_create(
    int unit, 
    bcm_udf_alloc_hints_t *hints, 
    bcm_udf_t *udf_info, 
    bcm_udf_id_t *udf_id);

/* Fetches the UDF object created in the system */
extern int bcm_udf_get(
    int unit, 
    bcm_udf_id_t udf_id, 
    bcm_udf_t *udf_info);

/* Fetches all existing UDF ids */
extern int bcm_udf_get_all(
    int unit, 
    int max, 
    bcm_udf_id_t *udf_id_list, 
    int *actual);

/* Destroys the UDF object */
extern int bcm_udf_destroy(
    int unit, 
    bcm_udf_id_t udf_id);

/* Create a packet format entry */
extern int bcm_udf_pkt_format_create(
    int unit, 
    bcm_udf_pkt_format_options_t options, 
    bcm_udf_pkt_format_info_t *pkt_format, 
    bcm_udf_pkt_format_id_t *pkt_format_id);

/* Retrieve packet format info given the packet format Id */
extern int bcm_udf_pkt_format_info_get(
    int unit, 
    bcm_udf_pkt_format_id_t pkt_format_id, 
    bcm_udf_pkt_format_info_t *pkt_format);

/* Destroy existing packet format entry */
extern int bcm_udf_pkt_format_destroy(
    int unit, 
    bcm_udf_pkt_format_id_t pkt_format_id);

/* Adds packet format entry to UDF object */
extern int bcm_udf_pkt_format_add(
    int unit, 
    bcm_udf_id_t udf_id, 
    bcm_udf_pkt_format_id_t pkt_format_id);

/* Deletes packet format spec associated with the UDF */
extern int bcm_udf_pkt_format_get(
    int unit, 
    bcm_udf_pkt_format_id_t pkt_format_id, 
    int max, 
    bcm_udf_id_t *udf_id_list, 
    int *actual);

/* Deletes packet format spec associated with the UDF */
extern int bcm_udf_pkt_format_delete(
    int unit, 
    bcm_udf_id_t udf_id, 
    bcm_udf_pkt_format_id_t pkt_format_id);

/* Retrieves the user defined format specification configuration from UDF */
extern int bcm_udf_pkt_format_get_all(
    int unit, 
    bcm_udf_id_t udf_id, 
    int max, 
    bcm_udf_pkt_format_id_t *pkt_format_id_list, 
    int *actual);

/* Deletes all packet format specs associated with the UDF */
extern int bcm_udf_pkt_format_delete_all(
    int unit, 
    bcm_udf_id_t udf_id);

#endif /* BCM_HIDE_DISPATCHABLE */

#endif /* __BCM_UDF_H__ */
