/*
 * $Id: c014474370a90eda08d7baa446a3ff70fab6e1dc $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __BCM_VXLAN_H__
#define __BCM_VXLAN_H__

#if defined(INCLUDE_L3)

#include <bcm/types.h>
#include <bcm/l3.h>
#include <bcm/tunnel.h>
#include <bcm/vlan.h>

#if defined(INCLUDE_L3)
/* BCM_VXLAN_VPN_* flags for VXLAN VPN Create. */
#define BCM_VXLAN_VPN_ELINE                 0x00000001 
#define BCM_VXLAN_VPN_ELAN                  0x00000002 
#define BCM_VXLAN_VPN_WITH_ID               0x00000004 
#define BCM_VXLAN_VPN_WITH_VPNID            0x00000008 
#define BCM_VXLAN_VPN_SERVICE_TAGGED        0x00000010 
#define BCM_VXLAN_VPN_SERVICE_VLAN_ADD      0x00000020 
#define BCM_VXLAN_VPN_SERVICE_VLAN_REPLACE  0x00000040 
#define BCM_VXLAN_VPN_SERVICE_VLAN_DELETE   0x00000080 
#define BCM_VXLAN_VPN_SERVICE_VLAN_TPID_REPLACE 0x00000100 
#define BCM_VXLAN_VPN_SERVICE_VLAN_PRI_TPID_REPLACE 0x00000200 
#define BCM_VXLAN_VPN_SERVICE_VLAN_PRI_REPLACE 0x00000400 
#define BCM_VXLAN_VPN_SERVICE_PRI_REPLACE   0x00000800 
#define BCM_VXLAN_VPN_SERVICE_TPID_REPLACE  0x00001000 
#define BCM_VXLAN_VPN_REPLACE               0x00002000 
#define BCM_VXLAN_VPN_UNKNOWN_UCAST_REPLACE 0x00004000 
#define BCM_VXLAN_VPN_UNKNOWN_MCAST_REPLACE 0x00008000 
#define BCM_VXLAN_VPN_BCAST_REPLACE         0x00010000 
#endif

#if defined(INCLUDE_L3)
/* BCM_VXLAN_MULTICAST_TUNNEL_STATE_BUD_* flags. */
#define BCM_VXLAN_MULTICAST_TUNNEL_STATE_BUD_ENABLE 0x00000001 
#define BCM_VXLAN_MULTICAST_TUNNEL_STATE_BUD_DISABLE 0x00000002 
#endif

#if defined(INCLUDE_L3)
/* VXLAN VPN Definitions. */
#define BCM_VXLAN_VPN_INVALID   0xFFFF     /* Invalid VXLAN VPN */
#endif

#if defined(INCLUDE_L3)
/* VXLAN VPN Config Structure. */
typedef struct bcm_vxlan_vpn_config_s {
    uint32 flags;                       /* BCM_VXLAN_VPN_xxx. */
    bcm_vpn_t vpn;                      /* VXLAN VPN */
    uint32 vnid;                        /* VNID */
    uint8 pkt_pri;                      /* Packet Priority */
    uint8 pkt_cfi;                      /* Packet CFI */
    uint16 egress_service_tpid;         /* Service TPID */
    bcm_vlan_t egress_service_vlan;     /* Service VLAN */
    bcm_multicast_t broadcast_group; 
    bcm_multicast_t unknown_unicast_group; 
    bcm_multicast_t unknown_multicast_group; 
    bcm_vlan_protocol_packet_ctrl_t protocol_pkt; 
} bcm_vxlan_vpn_config_t;
#endif

#if defined(INCLUDE_L3)
/* Initialize VXLAN VPN config structure. */
extern void bcm_vxlan_vpn_config_t_init(
    bcm_vxlan_vpn_config_t *info);
#endif

#ifndef BCM_HIDE_DISPATCHABLE

#if defined(INCLUDE_L3)
/* Create VXLAN-VPN instance */
extern int bcm_vxlan_vpn_create(
    int unit, 
    bcm_vxlan_vpn_config_t *info);
#endif

#if defined(INCLUDE_L3)
/* Delete VXLAN_VPN Instance */
extern int bcm_vxlan_vpn_destroy(
    int unit, 
    bcm_vpn_t l2vpn);
#endif

#if defined(INCLUDE_L3)
/* Delete all VXLAN-VPN instances */
extern int bcm_vxlan_vpn_destroy_all(
    int unit);
#endif

#if defined(INCLUDE_L3)
/* Get VXLAN-VPN instance by ID */
extern int bcm_vxlan_vpn_get(
    int unit, 
    bcm_vpn_t l2vpn, 
    bcm_vxlan_vpn_config_t *info);
#endif

#endif /* BCM_HIDE_DISPATCHABLE */

/* VXLAN vpn callback function prototype */
#if defined(INCLUDE_L3)
typedef int(*bcm_vxlan_vpn_traverse_cb)(
    int unit, 
    bcm_vxlan_vpn_config_t *info, 
    void *user_data);
#endif

#ifndef BCM_HIDE_DISPATCHABLE

#if defined(INCLUDE_L3)
/* Traverse VXLAN-VPN */
extern int bcm_vxlan_vpn_traverse(
    int unit, 
    bcm_vxlan_vpn_traverse_cb cb, 
    void *user_data);
#endif

#endif /* BCM_HIDE_DISPATCHABLE */

#if defined(INCLUDE_L3)
/* VXLAN port match criteria. */
typedef enum bcm_vxlan_port_match_e {
    BCM_VXLAN_PORT_MATCH_INVALID = 0,   /* Illegal. */
    BCM_VXLAN_PORT_MATCH_NONE = 1,      /* No source match criteria. */
    BCM_VXLAN_PORT_MATCH_PORT = 2,      /* {Module, Port} or Trunk. */
    BCM_VXLAN_PORT_MATCH_PORT_VLAN = 3, /* Mod/port/trunk + outer VLAN. */
    BCM_VXLAN_PORT_MATCH_PORT_INNER_VLAN = 4, /* Mod/port/trunk + inner VLAN. */
    BCM_VXLAN_PORT_MATCH_PORT_VLAN_STACKED = 5, /* Mod/port/trunk + outer/inner VLAN. */
    BCM_VXLAN_PORT_MATCH_VLAN_PRI = 6,  /* Mod/port/trunk + VLAN-PRI + VLAN-CFI. */
    BCM_VXLAN_PORT_MATCH_VN_ID = 7,     /* Match VXLAN VN_ID */
    BCM_VXLAN_PORT_MATCH_COUNT = 10     /* Must be last. */
} bcm_vxlan_port_match_t;
#endif

#if defined(INCLUDE_L3)
/* BCM_VXLAN_* flags. */
#define BCM_VXLAN_PORT_WITH_ID              (1 << 0)   /* create VXLAN port with
                                                          specified ID */
#define BCM_VXLAN_PORT_DROP                 (1 << 1)   /* Drop matching packets */
#define BCM_VXLAN_PORT_NETWORK              (1 << 2)   /* Network facing
                                                          interface */
#define BCM_VXLAN_PORT_COUNTED              (1 << 3)   /* Maintain packet/byte
                                                          counts */
#define BCM_VXLAN_PORT_REPLACE              (1 << 4)   /* Replace existing entry */
#define BCM_VXLAN_PORT_INT_PRI_SET          (1 << 5)   /* Use Specified pri for
                                                          internal priority */
#define BCM_VXLAN_PORT_INT_PRI_MAP          (1 << 6)   /* Use specified exp_map
                                                          for internal priority */
#define BCM_VXLAN_PORT_EGRESS_TUNNEL        (1 << 7)   /* Specified Egress
                                                          tunnel is valid */
#define BCM_VXLAN_PORT_SERVICE_TAGGED       (1 << 8)   /* Service tag mode */
#define BCM_VXLAN_PORT_SERVICE_VLAN_ADD     (1 << 9)   /* Add SD-tag */
#define BCM_VXLAN_PORT_SERVICE_VLAN_REPLACE (1 << 10)  /* Replace VLAN not TPID */
#define BCM_VXLAN_PORT_SERVICE_VLAN_DELETE  (1 << 11)  /* Delete VLAN Tag */
#define BCM_VXLAN_PORT_SERVICE_VLAN_TPID_REPLACE (1 << 12)  /* Replace VLAN and TPID */
#define BCM_VXLAN_PORT_SERVICE_VLAN_PRI_TPID_REPLACE (1 << 13)  /* Replace VLAN, VLAN-PRI
                                                          and TPID */
#define BCM_VXLAN_PORT_SERVICE_VLAN_PRI_REPLACE (1 << 14)  /* Replace VLAN and
                                                          VLAN-PRI */
#define BCM_VXLAN_PORT_SERVICE_PRI_REPLACE  (1 << 15)  /* Replace VLAN-PRI only */
#define BCM_VXLAN_PORT_SERVICE_TPID_REPLACE (1 << 16)  /* Replace TPID only */
#define BCM_VXLAN_PORT_MULTICAST            (1 << 19)  /* Create Multicast-only
                                                          VXLAN Tunnel */
#define BCM_VXLAN_PORT_DEFAULT              (1 << 20)  /* Create VXLAN Default
                                                          Network Port */
#define BCM_VXLAN_PORT_ENABLE_VLAN_CHECKS   (1 << 21)  /* Enable VLAN Checks for
                                                          VXLAN Port */
#endif

#if defined(INCLUDE_L3)
/* VXLAN Gport */
typedef struct bcm_vxlan_port_s {
    bcm_gport_t vxlan_port_id;          /* GPORT identifier. */
    uint32 flags;                       /* BCM_VXLAN_PORT_xxx. */
    uint32 if_class;                    /* Interface class ID. */
    uint16 int_pri;                     /* Internal Priority */
    uint8 pkt_pri;                      /* Packet Priority */
    uint8 pkt_cfi;                      /* Packet CFI */
    uint16 egress_service_tpid;         /* Service Vlan TPID Value */
    bcm_vlan_t egress_service_vlan;     /* SD-TAG Vlan ID. */
    uint16 mtu;                         /* MTU */
    bcm_gport_t match_port;             /* Match port / trunk */
    bcm_vxlan_port_match_t criteria;    /* Match criteria */
    bcm_vlan_t match_vlan;              /* Outer VLAN ID to match. */
    bcm_vlan_t match_inner_vlan;        /* Inner VLAN ID to match. */
    bcm_gport_t egress_tunnel_id;       /* Tunnel Initiator ID */
    bcm_gport_t match_tunnel_id;        /* Tunnel Terminator ID */
    bcm_if_t egress_if;                 /* VXLAN egress object. */
} bcm_vxlan_port_t;
#endif

#if defined(INCLUDE_L3)
/* Initialize the VXLAN port structure. */
extern void bcm_vxlan_port_t_init(
    bcm_vxlan_port_t *vxlan_port);
#endif

#ifndef BCM_HIDE_DISPATCHABLE

#if defined(INCLUDE_L3)
/* Initialize vxlan module. */
extern int bcm_vxlan_init(
    int unit);
#endif

#if defined(INCLUDE_L3)
/* Detach vxlan module. */
extern int bcm_vxlan_cleanup(
    int unit);
#endif

#if defined(INCLUDE_L3)
/* Add Access/Network VXLAN port */
extern int bcm_vxlan_port_add(
    int unit, 
    bcm_vpn_t l2vpn, 
    bcm_vxlan_port_t *vxlan_port);
#endif

#if defined(INCLUDE_L3)
/* Delete Access/Network VXLAN port */
extern int bcm_vxlan_port_delete(
    int unit, 
    bcm_vpn_t l2vpn, 
    bcm_gport_t vxlan_port_id);
#endif

#if defined(INCLUDE_L3)
/* bcm_vxlan_port_delete_all */
extern int bcm_vxlan_port_delete_all(
    int unit, 
    bcm_vpn_t l2vpn);
#endif

#if defined(INCLUDE_L3)
/* Get Access/Network VXLAN port */
extern int bcm_vxlan_port_get(
    int unit, 
    bcm_vpn_t l2vpn, 
    bcm_vxlan_port_t *vxlan_port);
#endif

#if defined(INCLUDE_L3)
/* Get all Access/Network VXLAN port */
extern int bcm_vxlan_port_get_all(
    int unit, 
    bcm_vpn_t l2vpn, 
    int port_max, 
    bcm_vxlan_port_t *port_array, 
    int *port_count);
#endif

#if defined(INCLUDE_L3)
/* Create VXLAN Tunnel Initiator */
extern int bcm_vxlan_tunnel_initiator_create(
    int unit, 
    bcm_tunnel_initiator_t *info);
#endif

#if defined(INCLUDE_L3)
/* Destroy VXLAN Tunnel Initiator */
extern int bcm_vxlan_tunnel_initiator_destroy(
    int unit, 
    bcm_gport_t vxlan_tunnel_id);
#endif

#if defined(INCLUDE_L3)
/* Destroy all VXLAN Tunnel Initiators */
extern int bcm_vxlan_tunnel_initiator_destroy_all(
    int unit);
#endif

#if defined(INCLUDE_L3)
/* Get VXLAN Tunnel Initiator Info */
extern int bcm_vxlan_tunnel_initiator_get(
    int unit, 
    bcm_tunnel_initiator_t *info);
#endif

#if defined(INCLUDE_L3)
/* Traverse VXLAN Tunnel Initiator Info */
extern int bcm_vxlan_tunnel_initiator_traverse(
    int unit, 
    bcm_tunnel_initiator_traverse_cb cb, 
    void *user_data);
#endif

#if defined(INCLUDE_L3)
/* Create VXLAN Tunnel Terminator */
extern int bcm_vxlan_tunnel_terminator_create(
    int unit, 
    bcm_tunnel_terminator_t *info);
#endif

#if defined(INCLUDE_L3)
/* Update VXLAN Tunnel Terminator */
extern int bcm_vxlan_tunnel_terminator_update(
    int unit, 
    bcm_tunnel_terminator_t *info);
#endif

#if defined(INCLUDE_L3)
/* Destroy VXLAN Tunnel terminator */
extern int bcm_vxlan_tunnel_terminator_destroy(
    int unit, 
    bcm_gport_t vxlan_tunnel_id);
#endif

#if defined(INCLUDE_L3)
/* Destroy all VXLAN Tunnel terminators */
extern int bcm_vxlan_tunnel_terminator_destroy_all(
    int unit);
#endif

#if defined(INCLUDE_L3)
/* Get VXLAN Tunnel terminator Info */
extern int bcm_vxlan_tunnel_terminator_get(
    int unit, 
    bcm_tunnel_terminator_t *info);
#endif

#if defined(INCLUDE_L3)
/* Traverse VXLAN Tunnel Terminator Info */
extern int bcm_vxlan_tunnel_terminator_traverse(
    int unit, 
    bcm_tunnel_terminator_traverse_cb cb, 
    void *user_data);
#endif

#endif /* BCM_HIDE_DISPATCHABLE */

/* Ingress and Egress statistics maintained per Vxlan. */
typedef enum bcm_vxlan_stat_e {
    bcmVxlanInPackets = 0,  /* Packets that ingress on the vxlan */
    bcmVxlanOutPackets = 1, /* Packets that egress on the vxlan */
    bcmVxlanInBytes = 2,    /* Bytes that ingress on the vxlan */
    bcmVxlanOutBytes = 3    /* Bytes that egress on the vxlan */
} bcm_vxlan_stat_t;

/* Ingress statistics maintained per Vxlan Dip. */
typedef enum bcm_vxlan_dip_stat_e {
    bcmVxlanDipInPackets = 0,   /* Packets that ingress on the Vxlan Dip . */
    bcmVxlanDipInBytes = 1      /* Bytes that ingress on the Vxlan Dip . */
} bcm_vxlan_dip_stat_t;

#ifndef BCM_HIDE_DISPATCHABLE

/* Attach counter entries to the given vxlan port and vpn. */
extern int bcm_vxlan_stat_attach(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    uint32 stat_counter_id);

/* Detach counter entries to the given vxlan port and vpn. */
extern int bcm_vxlan_stat_detach(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn);

/* Get Vxlan counter value for specified vxlan port and vpn */
extern int bcm_vxlan_stat_counter_get(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    bcm_vxlan_stat_t stat, 
    uint32 num_entries, 
    uint32 *counter_indexes, 
    bcm_stat_value_t *counter_values);

/* Get Vxlan counter value for specified vxlan port and vpn */
extern int bcm_vxlan_stat_counter_sync_get(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    bcm_vxlan_stat_t stat, 
    uint32 num_entries, 
    uint32 *counter_indexes, 
    bcm_stat_value_t *counter_values);

/* Set Vxlan counter value for specified vxlan port and vpn */
extern int bcm_vxlan_stat_counter_set(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    bcm_vxlan_stat_t stat, 
    uint32 num_entries, 
    uint32 *counter_indexes, 
    bcm_stat_value_t *counter_values);

/* Get 64-bit counter value for multiple vxlan statistic types. */
extern int bcm_vxlan_stat_multi_get(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    int nstat, 
    bcm_vxlan_stat_t *stat_arr, 
    uint64 *value_arr);

/* Get lower 32-bit counter value for multiple Vxlan statistic types. */
extern int bcm_vxlan_stat_multi_get32(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    int nstat, 
    bcm_vxlan_stat_t *stat_arr, 
    uint32 *value_arr);

/* Set 64-bit counter value for multiple vxlan statistic types. */
extern int bcm_vxlan_stat_multi_set(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    int nstat, 
    bcm_vxlan_stat_t *stat_arr, 
    uint64 *value_arr);

/* Set lower 32-bit counter value for multiple Vxlan statistic types. */
extern int bcm_vxlan_stat_multi_set32(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    int nstat, 
    bcm_vxlan_stat_t *stat_arr, 
    uint32 *value_arr);

/* Provide stat counter ids associated with given vxlan port and vpn */
extern int bcm_vxlan_stat_id_get(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    bcm_vxlan_stat_t stat, 
    uint32 *stat_counter_id);

/* 
 * Enable/disable collection of statistics on the indicated vxlan port
 * and vpn.
 */
extern int bcm_vxlan_stat_enable_set(
    int unit, 
    bcm_gport_t port, 
    bcm_vpn_t vpn, 
    int enable);

/* Attach counters entries to the given VXLAN DIP. */
extern int bcm_vxlan_dip_stat_attach(
    int unit, 
    bcm_ip_t vxlan_dip, 
    uint32 stat_counter_id);

/* Detach counters entries to the given VXLAN DIP. */
extern int bcm_vxlan_dip_stat_detach(
    int unit, 
    bcm_ip_t vxlan_dip);

/* Get the specified counter statistic for an VXLAN DIP. */
extern int bcm_vxlan_dip_stat_counter_get(
    int unit, 
    bcm_ip_t vxlan_dip, 
    bcm_vxlan_dip_stat_t stat, 
    uint32 num_entries, 
    uint32 *counter_indexes, 
    bcm_stat_value_t *counter_values);

/* Set the specified counter statistic for an VXLAN DIP. */
extern int bcm_vxlan_dip_stat_counter_set(
    int unit, 
    bcm_ip_t vxlan_dip, 
    bcm_vxlan_dip_stat_t stat, 
    uint32 num_entries, 
    uint32 *counter_indexes, 
    bcm_stat_value_t *counter_values);

/* Get 64-bit counter value for multiple VXLAN DIP statistic types. */
extern int bcm_vxlan_dip_stat_multi_get(
    int unit, 
    bcm_ip_t vxlan_dip, 
    int nstat, 
    bcm_vxlan_dip_stat_t *stat_arr, 
    uint64 *value_arr);

/* Get 32-bit counter value for multiple VXLAN DIP statistic types. */
extern int bcm_vxlan_dip_stat_multi_get32(
    int unit, 
    bcm_ip_t vxlan_dip, 
    int nstat, 
    bcm_vxlan_dip_stat_t *stat_arr, 
    uint32 *value_arr);

/* Set 64-bit counter value for multiple VXLAN DIP statistic types. */
extern int bcm_vxlan_dip_stat_multi_set(
    int unit, 
    bcm_ip_t vxlan_dip, 
    int nstat, 
    bcm_vxlan_dip_stat_t *stat_arr, 
    uint64 *value_arr);

/* Set 32-bit counter value for multiple VXLAN DIP statistic types. */
extern int bcm_vxlan_dip_stat_multi_set32(
    int unit, 
    bcm_ip_t vxlan_dip, 
    int nstat, 
    bcm_vxlan_dip_stat_t *stat_arr, 
    uint32 *value_arr);

/* Retrieve associated stat counter for given VXLAN DIP. */
extern int bcm_vxlan_dip_stat_id_get(
    int unit, 
    bcm_ip_t vxlan_dip, 
    bcm_vxlan_dip_stat_t stat, 
    uint32 *stat_counter_id);

#endif /* defined(INCLUDE_L3) */

#endif /* BCM_HIDE_DISPATCHABLE */

#endif /* __BCM_VXLAN_H__ */
