/*
 * $Id: module.h 1.56 Broadcom SDK $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __BCM_MODULE_H__
#define __BCM_MODULE_H__

#include <bcm/types.h>

#define BCM_MODULE_PORT         0          
#define BCM_MODULE_L2           1          
#define BCM_MODULE_VLAN         2          
#define BCM_MODULE_TRUNK        3          
#define BCM_MODULE_COSQ         4          
#define BCM_MODULE_MCAST        5          
#define BCM_MODULE_LINKSCAN     6          
#define BCM_MODULE_STAT         7          
#define BCM_MODULE_VIRTUAL      8          
#define BCM_MODULE_COMMON       9          
#define BCM_MODULE_MIRROR       10         
#define BCM_MODULE_L3           11         
#define BCM_MODULE_STACK        12         
#define BCM_MODULE_IPMC         13         
#define BCM_MODULE_STG          14         
#define BCM_MODULE_TX           15         
#define BCM_MODULE_L2GRE        16         
#define BCM_MODULE_AUTH         17         
#define BCM_MODULE_RX           18         
#define BCM_MODULE_FIELD        19         
#define BCM_MODULE_TIME         20         
#define BCM_MODULE_SUBPORT      21         
#define BCM_MODULE_MPLS         22         
#define BCM_MODULE_FABRIC       23         
#define BCM_MODULE_MIM          24         
#define BCM_MODULE_POLICER      25         
#define BCM_MODULE_OAM          26         
#define BCM_MODULE_FAILOVER     27         
#define BCM_MODULE_VSWITCH      28         
#define BCM_MODULE_WLAN         29         
#define BCM_MODULE_QOS          30         
#define BCM_MODULE_MULTICAST    31         
#define BCM_MODULE_TRILL        32         
#define BCM_MODULE_IPFIX        33         
#define BCM_MODULE_NIV          34         
#define BCM_MODULE_CES          35         
#define BCM_MODULE_PTP          36         
#define BCM_MODULE_BFD          37         
#define BCM_MODULE_REGEX        38         
#define BCM_MODULE_VXLAN        39         
#define BCM_MODULE_EXTENDER     40         
#define BCM_MODULE_FCOE         41         
#define BCM_MODULE__COUNT       42         /* Always last plus one. */

#define BCM_MODULE_NAMES_INITIALIZER    \
{ \
    "port", \
    "l2", \
    "vlan", \
    "trunk", \
    "cosq", \
    "mcast", \
    "linkscan", \
    "stat", \
    "virtual", \
    "common", \
    "mirror", \
    "l3", \
    "stack", \
    "ipmc", \
    "stg", \
    "tx", \
    "l2gre", \
    "auth", \
    "rx", \
    "field", \
    "rcpu", \
    "subport", \
    "mpls", \
    "fabric", \
    "mim", \
    "policer", \
    "oam", \
    "failover", \
    "vswitch", \
    "wlan", \
    "qos", \
    "multicast", \
    "trill", \
    "ipfix", \
    "niv", \
    "ces", \
    "ptp", \
    "bfd", \
    "regex", \
    "vxlan", \
    "extender", \
    "fcoe" \
} 

/* bcm_module_name */
extern char *bcm_module_name(
    int unit, 
    int bcm_module);

#endif /* __BCM_MODULE_H__ */
