/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: 0daac40a3d695d0ee2bc0d98229d62f04b854336 $
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * File:	traverse_client.c
 * Purpose:	BCM API Traverse Server routines for remote units
 * Generator:	mkdispatch 1.54
 * Generated:	Tue May 13 21:13:44 2014
 */

#include <shared/alloc.h>
#include <bcm/types.h>
#include <bcm/bregex.h>
#include <bcm/ces.h>
#include <bcm/cosq.h>
#include <bcm/extender.h>
#include <bcm/fabric.h>
#include <bcm/fcoe.h>
#include <bcm/field.h>
#include <bcm/ipfix.h>
#include <bcm/ipmc.h>
#include <bcm/l2.h>
#include <bcm/l2gre.h>
#include <bcm/l3.h>
#include <bcm/mim.h>
#include <bcm/mirror.h>
#include <bcm/mpls.h>
#include <bcm/multicast.h>
#include <bcm/nat.h>
#include <bcm/niv.h>
#include <bcm/oam.h>
#include <bcm/policer.h>
#include <bcm/proxy.h>
#include <bcm/sat.h>
#include <bcm/subport.h>
#include <bcm/time.h>
#include <bcm/trill.h>
#include <bcm/trunk.h>
#include <bcm/tunnel.h>
#include <bcm/vlan.h>
#include <bcm/vswitch.h>
#include <bcm/vxlan.h>
#include <bcm/wlan.h>

#include <bcm_int/rpc/pack.h>
#include "traverse.h"

#ifdef	BCM_RPC_SUPPORT


#ifdef	INCLUDE_CES

int
bcm_client_ces_services_traverse(
	int	unit,
	uint32	flags,
	bcm_ces_service_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x90e65d9e,0xcf643c0b,0x5ba55c9c,0x4bf8ba92,0xd6b819e9 };

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */

			r_rv = cb(unit, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_CES */

int
bcm_client_cosq_gport_traverse(
	int	unit,
	bcm_cosq_gport_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xcdd16376,0x9b8ac79f,0xd0b2074a,0x456f0101,0xb667687c };
	bcm_gport_t	r_port;
	int	r_numq;
	uint32	r_flags;
	bcm_gport_t	r_gport;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U32(r_req.rx_ptr, r_numq);
			BCM_UNPACK_U32(r_req.rx_ptr, r_flags);
			BCM_UNPACK_U32(r_req.rx_ptr, r_gport);

			r_rv = cb(unit, r_port, r_numq, r_flags, r_gport, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_cosq_subscriber_traverse(
	int	unit,
	bcm_cosq_subscriber_map_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x7eaa044b,0x4739ff12,0x82703193,0x8bc6a763,0x26eb7aae };
	bcm_cosq_subscriber_map_t	r_map;
	bcm_cosq_subscriber_map_t *	r_p_map;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_map = NULL;
			} else {
				r_p_map = &r_map;
				r_req.rx_ptr = _bcm_unpack_cosq_subscriber_map(r_req.rx_ptr, r_p_map);
			}

			r_rv = cb(unit, r_p_map, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_extender_encap_traverse(
	int	unit,
	bcm_extender_encap_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xf016ce91,0xe1f3dfdd,0xcc2bf4a3,0x8d6c6965,0x051ef3b5 };
	bcm_extender_encap_t	r_extender_encap;
	bcm_extender_encap_t *	r_p_extender_encap;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_extender_encap = NULL;
			} else {
				r_p_extender_encap = &r_extender_encap;
				r_req.rx_ptr = _bcm_unpack_extender_encap(r_req.rx_ptr, r_p_extender_encap);
			}

			r_rv = cb(unit, r_p_extender_encap, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_extender_forward_traverse(
	int	unit,
	bcm_extender_forward_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x3e5a5367,0xd7207b54,0x4aeac8c6,0x13cc01c5,0xb2b2c801 };
	bcm_extender_forward_t	r_extender_forward_entry;
	bcm_extender_forward_t *	r_p_extender_forward_entry;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_extender_forward_entry = NULL;
			} else {
				r_p_extender_forward_entry = &r_extender_forward_entry;
				r_req.rx_ptr = _bcm_unpack_extender_forward(r_req.rx_ptr, r_p_extender_forward_entry);
			}

			r_rv = cb(unit, r_p_extender_forward_entry, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_extender_port_traverse(
	int	unit,
	bcm_extender_port_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x7e9ac770,0xd851ab92,0x9977eecf,0x07c509f4,0xe57e5cd0 };
	bcm_extender_port_t	r_extender_port;
	bcm_extender_port_t *	r_p_extender_port;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_extender_port = NULL;
			} else {
				r_p_extender_port = &r_extender_port;
				r_req.rx_ptr = _bcm_unpack_extender_port(r_req.rx_ptr, r_p_extender_port);
			}

			r_rv = cb(unit, r_p_extender_port, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */

int
bcm_client_fabric_action_traverse(
	int	unit,
	bcm_fabric_action_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xd09547e4,0x74756cf0,0x892ce5f5,0x73a3ea6c,0xff536521 };
	bcm_fabric_action_t	r_action_id;
	bcm_fabric_action_info_t	r_action_info;
	bcm_fabric_action_info_t *	r_p_action_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_action_id);
			if (*r_req.rx_ptr++ == 1) {
				r_p_action_info = NULL;
			} else {
				r_p_action_info = &r_action_info;
				r_req.rx_ptr = _bcm_unpack_fabric_action_info(r_req.rx_ptr, r_p_action_info);
			}

			r_rv = cb(unit, r_action_id, r_p_action_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fabric_predicate_action_traverse(
	int	unit,
	bcm_fabric_predicate_action_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xe3e74fd8,0x96476661,0x8047f5a8,0x117c2bbf,0xeabeaf58 };
	bcm_fabric_predicate_action_t	r_predicate_action_id;
	bcm_fabric_predicate_action_info_t	r_predicate_action_info;
	bcm_fabric_predicate_action_info_t *	r_p_predicate_action_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_predicate_action_id);
			if (*r_req.rx_ptr++ == 1) {
				r_p_predicate_action_info = NULL;
			} else {
				r_p_predicate_action_info = &r_predicate_action_info;
				r_req.rx_ptr = _bcm_unpack_fabric_predicate_action_info(r_req.rx_ptr, r_p_predicate_action_info);
			}

			r_rv = cb(unit, r_predicate_action_id, r_p_predicate_action_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fabric_predicate_traverse(
	int	unit,
	bcm_fabric_predicate_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x9b5315c0,0xb0c3eeb2,0x69dcd64b,0x615311d9,0x84425616 };
	bcm_fabric_predicate_t	r_pred_id;
	bcm_fabric_predicate_info_t	r_pred_info;
	bcm_fabric_predicate_info_t *	r_p_pred_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_pred_id);
			if (*r_req.rx_ptr++ == 1) {
				r_p_pred_info = NULL;
			} else {
				r_p_pred_info = &r_pred_info;
				r_req.rx_ptr = _bcm_unpack_fabric_predicate_info(r_req.rx_ptr, r_p_pred_info);
			}

			r_rv = cb(unit, r_pred_id, r_p_pred_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fabric_qsel_entry_traverse(
	int	unit,
	bcm_fabric_qsel_t	qsel_id,
	bcm_fabric_qsel_entry_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x295c9feb,0x8c75e357,0x8c42628e,0x49db7cf4,0x39540b43 };
	bcm_fabric_qsel_t	r_qsel_id;
	int	r_offset;
	bcm_gport_t	r_queue;
	bcm_fabric_qsel_offset_t	r_qsel_offset;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, qsel_id);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_qsel_id);
			BCM_UNPACK_U32(r_req.rx_ptr, r_offset);
			BCM_UNPACK_U32(r_req.rx_ptr, r_queue);
			BCM_UNPACK_U32(r_req.rx_ptr, r_qsel_offset);

			r_rv = cb(unit, r_qsel_id, r_offset, r_queue, r_qsel_offset, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fabric_qsel_offset_entry_traverse(
	int	unit,
	bcm_fabric_qsel_offset_t	qsel_offset_id,
	bcm_fabric_qsel_offset_entry_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xb00d7a12,0xfbe0dca1,0x4a6e8f4d,0xa249d050,0x792767aa };
	bcm_fabric_qsel_offset_t	r_qsel_offset_id;
	bcm_cos_t	r_int_pri;
	int	r_offset;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, qsel_offset_id);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_qsel_offset_id);
			BCM_UNPACK_U32(r_req.rx_ptr, r_int_pri);
			BCM_UNPACK_U32(r_req.rx_ptr, r_offset);

			r_rv = cb(unit, r_qsel_offset_id, r_int_pri, r_offset, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fabric_qsel_offset_traverse(
	int	unit,
	bcm_fabric_qsel_offset_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x23b0dc69,0x3a9bee91,0x30cb05d4,0x7dc2246d,0x09b7ad84 };
	bcm_fabric_qsel_offset_t	r_qsel_offset_id;
	uint32	r_flags;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_qsel_offset_id);
			BCM_UNPACK_U32(r_req.rx_ptr, r_flags);

			r_rv = cb(unit, r_qsel_offset_id, r_flags, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fabric_qsel_traverse(
	int	unit,
	bcm_fabric_qsel_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x2428b5d0,0x909f54aa,0xf64a8cee,0x9b352323,0x7e3273ef };
	bcm_fabric_qsel_t	r_qsel_id;
	uint32	r_flags;
	int	r_base;
	int	r_count;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_qsel_id);
			BCM_UNPACK_U32(r_req.rx_ptr, r_flags);
			BCM_UNPACK_U32(r_req.rx_ptr, r_base);
			BCM_UNPACK_U32(r_req.rx_ptr, r_count);

			r_rv = cb(unit, r_qsel_id, r_flags, r_base, r_count, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fcoe_route_traverse(
	int	unit,
	uint32	flags,
	bcm_fcoe_route_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x11f430d4,0x77be922f,0xe6ae6c0c,0x93c6aad5,0xbe032cc2 };
	bcm_fcoe_route_t	r_route;
	bcm_fcoe_route_t *	r_p_route;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_route = NULL;
			} else {
				r_p_route = &r_route;
				r_req.rx_ptr = _bcm_unpack_fcoe_route(r_req.rx_ptr, r_p_route);
			}

			r_rv = trav_fn(unit, r_p_route, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fcoe_vsan_traverse(
	int	unit,
	uint32	flags,
	bcm_fcoe_vsan_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x1d2f1ea4,0xe2d4a29a,0x5e48b834,0xf3e30cd0,0xe11a1ff4 };
	bcm_fcoe_vsan_id_t	r_vsan_id;
	bcm_fcoe_vsan_t	r_vsan;
	bcm_fcoe_vsan_t *	r_p_vsan;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_vsan_id);
			if (*r_req.rx_ptr++ == 1) {
				r_p_vsan = NULL;
			} else {
				r_p_vsan = &r_vsan;
				r_req.rx_ptr = _bcm_unpack_fcoe_vsan(r_req.rx_ptr, r_p_vsan);
			}

			r_rv = trav_fn(unit, r_vsan_id, r_p_vsan, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_fcoe_zone_traverse(
	int	unit,
	uint32	flags,
	bcm_fcoe_zone_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x3fde7d72,0x13dca9fb,0x26a6e5f6,0x808ef4a4,0x0b11388b };
	bcm_fcoe_zone_entry_t	r_zone;
	bcm_fcoe_zone_entry_t *	r_p_zone;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_zone = NULL;
			} else {
				r_p_zone = &r_zone;
				r_req.rx_ptr = _bcm_unpack_fcoe_zone_entry(r_req.rx_ptr, r_p_zone);
			}

			r_rv = trav_fn(unit, r_p_zone, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_field_group_traverse(
	int	unit,
	bcm_field_group_traverse_cb	callback,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xabd27cfb,0x948c6a65,0x086d4a58,0x4f1490e8,0x6e2aa45d };
	bcm_field_group_t	r_group;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_group);

			r_rv = callback(unit, r_group, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_ipfix_rate_traverse(
	int	unit,
	bcm_ipfix_rate_traverse_cb	cb,
	void *	userdata)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x46a4972e,0x92ec830b,0x9b8f6d89,0x04fc1820,0x272f503f };
	bcm_ipfix_rate_t	r_rate_info;
	bcm_ipfix_rate_t *	r_p_rate_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_rate_info = NULL;
			} else {
				r_p_rate_info = &r_rate_info;
				r_req.rx_ptr = _bcm_unpack_ipfix_rate(r_req.rx_ptr, r_p_rate_info);
			}

			r_rv = cb(unit, r_p_rate_info, userdata);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_ipmc_traverse(
	int	unit,
	uint32	flags,
	bcm_ipmc_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xe6cd13ba,0x125638c6,0xbbe75b93,0x7e25925e,0x0d8b8c42 };
	bcm_ipmc_addr_t	r_info;
	bcm_ipmc_addr_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_ipmc_addr(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */

int
bcm_client_l2_auth_traverse(
	int	unit,
	bcm_l2_auth_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x9ec5f6e7,0x2f479259,0xc3625b7f,0xc9630cc7,0x2b8f401f };
	bcm_l2_auth_addr_t	r_info;
	bcm_l2_auth_addr_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l2_auth_addr(r_req.rx_ptr, r_p_info);
			}

			r_rv = trav_fn(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l2_egress_traverse(
	int	unit,
	bcm_l2_egress_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xb8c6c76d,0x66647c41,0xaaf33868,0x35da5d0a,0x53e675bb };
	bcm_l2_egress_t	r_egr;
	bcm_l2_egress_t *	r_p_egr;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_egr = NULL;
			} else {
				r_p_egr = &r_egr;
				r_req.rx_ptr = _bcm_unpack_l2_egress(r_req.rx_ptr, r_p_egr);
			}

			r_rv = trav_fn(unit, r_p_egr, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l2_mac_port_traverse(
	int	unit,
	bcm_l2_mac_port_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xe62643c8,0x8af78de7,0x9b5abb3c,0x5831fc7b,0x4ef6b3bc };
	bcm_l2_mac_port_t	r_mac_port;
	bcm_l2_mac_port_t *	r_p_mac_port;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_mac_port = NULL;
			} else {
				r_p_mac_port = &r_mac_port;
				r_req.rx_ptr = _bcm_unpack_l2_mac_port(r_req.rx_ptr, r_p_mac_port);
			}

			r_rv = cb(unit, r_p_mac_port, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l2_match_masked_traverse(
	int	unit,
	uint32	flags,
	bcm_l2_addr_t *	match_addr,
	bcm_l2_addr_t *	mask_addr,
	bcm_l2_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
#ifndef	BCM_RPC_PBMP_64
		0xb864fc74,0x84b3a477,0x8ad9b6bd,0x82245fc1,0x7c321b35
#else
		0xc35ac4ad,0x9fcee29e,0x6acef176,0xc563f7b6,0xdaa53f8a
#endif	/* BCM_RPC_PBMP_64 */
	};
	bcm_l2_addr_t	r_info;
	bcm_l2_addr_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);
		if (match_addr == NULL) {
			BCM_PACK_U8(r_req.tx_ptr, 1);
		} else {
			BCM_PACK_U8(r_req.tx_ptr, 0);
			r_req.tx_ptr = _bcm_pack_l2_addr(r_req.tx_ptr, match_addr);
		}
		if (mask_addr == NULL) {
			BCM_PACK_U8(r_req.tx_ptr, 1);
		} else {
			BCM_PACK_U8(r_req.tx_ptr, 0);
			r_req.tx_ptr = _bcm_pack_l2_addr(r_req.tx_ptr, mask_addr);
		}

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l2_addr(r_req.rx_ptr, r_p_info);
			}

			r_rv = trav_fn(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l2_matched_traverse(
	int	unit,
	uint32	flags,
	bcm_l2_addr_t *	match_addr,
	bcm_l2_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
#ifndef	BCM_RPC_PBMP_64
		0xc05d7a35,0xc47454ce,0x86beb6e5,0x390f70d0,0x93520750
#else
		0x646827e9,0xc91aeb6b,0x590f1919,0x33950171,0x756e4b75
#endif	/* BCM_RPC_PBMP_64 */
	};
	bcm_l2_addr_t	r_info;
	bcm_l2_addr_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);
		if (match_addr == NULL) {
			BCM_PACK_U8(r_req.tx_ptr, 1);
		} else {
			BCM_PACK_U8(r_req.tx_ptr, 0);
			r_req.tx_ptr = _bcm_pack_l2_addr(r_req.tx_ptr, match_addr);
		}

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l2_addr(r_req.rx_ptr, r_p_info);
			}

			r_rv = trav_fn(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l2_traverse(
	int	unit,
	bcm_l2_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x60a22b31,0x6ec6ca4f,0xe1b0ce78,0xee3264b2,0x1e544bd4 };
	bcm_l2_addr_t	r_info;
	bcm_l2_addr_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l2_addr(r_req.rx_ptr, r_p_info);
			}

			r_rv = trav_fn(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_l2gre_tunnel_initiator_traverse(
	int	unit,
	bcm_tunnel_initiator_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x5930b6da,0xe0ea0015,0x7ec8c0bd,0xe95b013f,0x856bac4c };
	bcm_tunnel_initiator_t	r_info;
	bcm_tunnel_initiator_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_tunnel_initiator(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l2gre_tunnel_terminator_traverse(
	int	unit,
	bcm_tunnel_terminator_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x4e505a92,0x21e818f4,0x37e0072f,0xd5c79292,0x4a7a67a2 };
	bcm_tunnel_terminator_t	r_info;
	bcm_tunnel_terminator_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_tunnel_terminator(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l2gre_vpn_traverse(
	int	unit,
	bcm_l2gre_vpn_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x0a1e5cfa,0x9f4444e7,0xb2958c32,0x3a17c284,0x98f9394a };
	bcm_l2gre_vpn_config_t	r_info;
	bcm_l2gre_vpn_config_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l2gre_vpn_config(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_egress_ecmp_resilient_traverse(
	int	unit,
	uint32	flags,
	bcm_l3_egress_ecmp_resilient_entry_t *	match_entry,
	bcm_l3_egress_ecmp_resilient_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x3c49a37b,0x95ea392d,0xcf03bd38,0xa5fec04d,0xd1308799 };
	bcm_l3_egress_ecmp_resilient_entry_t	r_entry;
	bcm_l3_egress_ecmp_resilient_entry_t *	r_p_entry;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);
		if (match_entry == NULL) {
			BCM_PACK_U8(r_req.tx_ptr, 1);
		} else {
			BCM_PACK_U8(r_req.tx_ptr, 0);
			r_req.tx_ptr = _bcm_pack_l3_egress_ecmp_resilient_entry(r_req.tx_ptr, match_entry);
		}

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_entry = NULL;
			} else {
				r_p_entry = &r_entry;
				r_req.rx_ptr = _bcm_unpack_l3_egress_ecmp_resilient_entry(r_req.rx_ptr, r_p_entry);
			}

			r_rv = trav_fn(unit, r_p_entry, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_egress_ecmp_traverse(
	int	unit,
	bcm_l3_egress_ecmp_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	int	r_i;
	uint32	r_key[] = {
		0x6e067c6f,0xe832c80e,0x240868d6,0x83302b31,0x92c7a1e7 };
	bcm_l3_egress_ecmp_t	r_ecmp;
	int	r_intf_count;
	bcm_l3_egress_ecmp_t *	r_p_ecmp;
	bcm_if_t *	r_p_intf_array;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			r_rv = BCM_E_NONE;
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_ecmp = NULL;
			} else {
				r_p_ecmp = &r_ecmp;
				r_req.rx_ptr = _bcm_unpack_l3_egress_ecmp(r_req.rx_ptr, r_p_ecmp);
			}
			BCM_UNPACK_U32(r_req.rx_ptr, r_intf_count);
			if (*r_req.rx_ptr++ == 1) {
				r_p_intf_array = NULL;
			} else {
				r_p_intf_array = sal_alloc(r_intf_count*sizeof(bcm_if_t), "traverse r_intf_array");
				if (r_p_intf_array == NULL) {
					r_rv = BCM_E_MEMORY;
				} else {
					for (r_i = 0; r_i < r_intf_count; r_i++) {
						BCM_UNPACK_U32(r_req.rx_ptr, *(r_p_intf_array+r_i));
					}
				}
			}

			if (BCM_SUCCESS(r_rv)) {
				r_rv = trav_fn(unit, r_p_ecmp, r_intf_count, r_p_intf_array, user_data);
			}

			if (r_p_intf_array != NULL) {
				sal_free(r_p_intf_array);
			}

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_egress_multipath_traverse(
	int	unit,
	bcm_l3_egress_multipath_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	int	r_i;
	uint32	r_key[] = {
		0x22876dbb,0x559c93df,0x84dcc649,0x6d3fe0ae,0x14dbec70 };
	bcm_if_t	r_mpintf;
	int	r_intf_count;
	bcm_if_t *	r_p_intf_array;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			r_rv = BCM_E_NONE;
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_mpintf);
			BCM_UNPACK_U32(r_req.rx_ptr, r_intf_count);
			if (*r_req.rx_ptr++ == 1) {
				r_p_intf_array = NULL;
			} else {
				r_p_intf_array = sal_alloc(r_intf_count*sizeof(bcm_if_t), "traverse r_intf_array");
				if (r_p_intf_array == NULL) {
					r_rv = BCM_E_MEMORY;
				} else {
					for (r_i = 0; r_i < r_intf_count; r_i++) {
						BCM_UNPACK_U32(r_req.rx_ptr, *(r_p_intf_array+r_i));
					}
				}
			}

			if (BCM_SUCCESS(r_rv)) {
				r_rv = trav_fn(unit, r_mpintf, r_intf_count, r_p_intf_array, user_data);
			}

			if (r_p_intf_array != NULL) {
				sal_free(r_p_intf_array);
			}

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_egress_traverse(
	int	unit,
	bcm_l3_egress_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x5ab66d8d,0x122fdf0c,0x33bd285e,0x1f8c56ed,0x1ad886d3 };
	bcm_if_t	r_intf;
	bcm_l3_egress_t	r_info;
	bcm_l3_egress_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_intf);
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l3_egress(r_req.rx_ptr, r_p_info);
			}

			r_rv = trav_fn(unit, r_intf, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_host_traverse(
	int	unit,
	uint32	flags,
	uint32	start,
	uint32	end,
	bcm_l3_host_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x65fa4078,0x7c353975,0xc28647e2,0x1d35a278,0xcbaeef5d };
	int	r_index;
	bcm_l3_host_t	r_info;
	bcm_l3_host_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);
		BCM_PACK_U32(r_req.tx_ptr, start);
		BCM_PACK_U32(r_req.tx_ptr, end);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_index);
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l3_host(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_index, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_ingress_traverse(
	int	unit,
	bcm_l3_ingress_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x167de67a,0x4556a271,0xdc2c824a,0x9422f096,0x666e0a05 };
	bcm_if_t	r_intf_id;
	bcm_l3_ingress_t	r_ing_intf;
	bcm_l3_ingress_t *	r_p_ing_intf;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_intf_id);
			if (*r_req.rx_ptr++ == 1) {
				r_p_ing_intf = NULL;
			} else {
				r_p_ing_intf = &r_ing_intf;
				r_req.rx_ptr = _bcm_unpack_l3_ingress(r_req.rx_ptr, r_p_ing_intf);
			}

			r_rv = trav_fn(unit, r_intf_id, r_p_ing_intf, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_nat_egress_traverse(
	int	unit,
	uint32	flags,
	uint32	start,
	uint32	end,
	bcm_l3_nat_egress_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xa1121fdb,0x44050e85,0x65ebc921,0xb733a73a,0xf5017ada };
	int	r_index;
	bcm_l3_nat_egress_t	r_nat_info;
	bcm_l3_nat_egress_t *	r_p_nat_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);
		BCM_PACK_U32(r_req.tx_ptr, start);
		BCM_PACK_U32(r_req.tx_ptr, end);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_index);
			if (*r_req.rx_ptr++ == 1) {
				r_p_nat_info = NULL;
			} else {
				r_p_nat_info = &r_nat_info;
				r_req.rx_ptr = _bcm_unpack_l3_nat_egress(r_req.rx_ptr, r_p_nat_info);
			}

			r_rv = cb(unit, r_index, r_p_nat_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_nat_ingress_traverse(
	int	unit,
	uint32	flags,
	uint32	start,
	uint32	end,
	bcm_l3_nat_ingress_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xd28cc963,0xe38b1845,0xd4394a78,0xc171d148,0x12286049 };
	int	r_index;
	bcm_l3_nat_ingress_t	r_nat_info;
	bcm_l3_nat_ingress_t *	r_p_nat_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);
		BCM_PACK_U32(r_req.tx_ptr, start);
		BCM_PACK_U32(r_req.tx_ptr, end);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_index);
			if (*r_req.rx_ptr++ == 1) {
				r_p_nat_info = NULL;
			} else {
				r_p_nat_info = &r_nat_info;
				r_req.rx_ptr = _bcm_unpack_l3_nat_ingress(r_req.rx_ptr, r_p_nat_info);
			}

			r_rv = cb(unit, r_index, r_p_nat_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_route_traverse(
	int	unit,
	uint32	flags,
	uint32	start,
	uint32	end,
	bcm_l3_route_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x3abb9ca2,0x9b9849d1,0x3fa6df34,0x889a975e,0xf18da8c9 };
	int	r_index;
	bcm_l3_route_t	r_info;
	bcm_l3_route_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);
		BCM_PACK_U32(r_req.tx_ptr, start);
		BCM_PACK_U32(r_req.tx_ptr, end);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_index);
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l3_route(r_req.rx_ptr, r_p_info);
			}

			r_rv = trav_fn(unit, r_index, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_l3_source_bind_traverse(
	int	unit,
	bcm_l3_source_bind_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xd2779d49,0xa91716ef,0xd4db8d97,0x5419c650,0xceaaa2c9 };
	bcm_l3_source_bind_t	r_info;
	bcm_l3_source_bind_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_l3_source_bind(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_mim_vpn_traverse(
	int	unit,
	bcm_mim_vpn_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x532bf474,0x5fc8a40c,0x05cfbef4,0x927b5787,0x09fc1173 };
	bcm_mim_vpn_config_t	r_info;
	bcm_mim_vpn_config_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_mim_vpn_config(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */

int
bcm_client_mirror_destination_traverse(
	int	unit,
	bcm_mirror_destination_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xdcd8d11e,0x2fee11c8,0xfdc6b378,0x9fefee8c,0x8980f333 };
	bcm_mirror_destination_t	r_mirror_dest;
	bcm_mirror_destination_t *	r_p_mirror_dest;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_mirror_dest = NULL;
			} else {
				r_p_mirror_dest = &r_mirror_dest;
				r_req.rx_ptr = _bcm_unpack_mirror_destination(r_req.rx_ptr, r_p_mirror_dest);
			}

			r_rv = cb(unit, r_p_mirror_dest, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_mpls_tunnel_switch_traverse(
	int	unit,
	bcm_mpls_tunnel_switch_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xe78321d1,0x5f8959d3,0x6b5dc068,0x3bd16a35,0x8fa5673f };
	bcm_mpls_tunnel_switch_t	r_info;
	bcm_mpls_tunnel_switch_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_mpls_tunnel_switch(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_mpls_vpn_traverse(
	int	unit,
	bcm_mpls_vpn_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xa6b62e4d,0xf0357ad3,0x3eb5c1f8,0xc1112545,0xff607622 };
	bcm_mpls_vpn_config_t	r_info;
	bcm_mpls_vpn_config_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_mpls_vpn_config(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */

int
bcm_client_multicast_group_traverse(
	int	unit,
	bcm_multicast_group_traverse_cb_t	trav_fn,
	uint32	flags,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x609d585a,0x28d1d4b4,0x9dafcc73,0x0600d68f,0x56fdedd2 };
	bcm_multicast_t	r_group;
	uint32	r_flags;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_group);
			BCM_UNPACK_U32(r_req.rx_ptr, r_flags);

			r_rv = trav_fn(unit, r_group, r_flags, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_niv_forward_traverse(
	int	unit,
	bcm_niv_forward_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xdff5e37c,0x63f8f445,0x7eb5490d,0xae8f690c,0x87f6eec7 };
	bcm_niv_forward_t	r_iv_fwd_entry;
	bcm_niv_forward_t *	r_p_iv_fwd_entry;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_iv_fwd_entry = NULL;
			} else {
				r_p_iv_fwd_entry = &r_iv_fwd_entry;
				r_req.rx_ptr = _bcm_unpack_niv_forward(r_req.rx_ptr, r_p_iv_fwd_entry);
			}

			r_rv = cb(unit, r_p_iv_fwd_entry, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_niv_port_traverse(
	int	unit,
	bcm_niv_port_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xf576f989,0xe875babe,0xdc063963,0xedd55a31,0xd47ff86a };
	bcm_niv_port_t	r_niv_port;
	bcm_niv_port_t *	r_p_niv_port;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_niv_port = NULL;
			} else {
				r_p_niv_port = &r_niv_port;
				r_req.rx_ptr = _bcm_unpack_niv_port(r_req.rx_ptr, r_p_niv_port);
			}

			r_rv = cb(unit, r_p_niv_port, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */

int
bcm_client_oam_endpoint_traverse(
	int	unit,
	bcm_oam_group_t	group,
	bcm_oam_endpoint_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x84d3139b,0x63882899,0x779a64f2,0x780bebd5,0x7c6293da };
	bcm_oam_endpoint_info_t	r_endpoint_info;
	bcm_oam_endpoint_info_t *	r_p_endpoint_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, group);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_endpoint_info = NULL;
			} else {
				r_p_endpoint_info = &r_endpoint_info;
				r_req.rx_ptr = _bcm_unpack_oam_endpoint_info(r_req.rx_ptr, r_p_endpoint_info);
			}

			r_rv = cb(unit, r_p_endpoint_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_oam_group_traverse(
	int	unit,
	bcm_oam_group_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xc0d84a55,0xb28f41a5,0xa3f7be33,0x6c24dde9,0x98e0eccb };
	bcm_oam_group_info_t	r_group_info;
	bcm_oam_group_info_t *	r_p_group_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_group_info = NULL;
			} else {
				r_p_group_info = &r_group_info;
				r_req.rx_ptr = _bcm_unpack_oam_group_info(r_req.rx_ptr, r_p_group_info);
			}

			r_rv = cb(unit, r_p_group_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_policer_traverse(
	int	unit,
	bcm_policer_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xf1700d39,0x5240c888,0x4932cc67,0xdfa88306,0x7424edf3 };
	bcm_policer_t	r_policer_id;
	bcm_policer_config_t	r_info;
	bcm_policer_config_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_policer_id);
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_policer_config(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_policer_id, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_proxy_egress_traverse(
	int	unit,
	bcm_proxy_egress_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x991de8b3,0xd507f533,0x79a88425,0x85992902,0xc42c48e8 };
	bcm_if_t	r_proxy_if_id;
	bcm_proxy_egress_t	r_info;
	bcm_proxy_egress_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_proxy_if_id);
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_proxy_egress(r_req.rx_ptr, r_p_info);
			}

			r_rv = trav_fn(unit, r_proxy_if_id, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */
#ifdef	INCLUDE_REGEX

int
bcm_client_regex_session_traverse(
	int	unit,
	int	flags,
	bcm_regex_session_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x97881531,0x3f638671,0x091072ca,0x638d7506,0xa71444d4 };
	bcm_regex_session_key_t	r_session_key;
	bcm_regex_session_t	r_session_data;
	bcm_regex_session_key_t *	r_p_session_key;
	bcm_regex_session_t *	r_p_session_data;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_session_key = NULL;
			} else {
				r_p_session_key = &r_session_key;
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_key->flags);
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_key->sip);
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_key->dip);
				r_req.rx_ptr = _bcm_unpack_ip6(r_req.rx_ptr, (*r_p_session_key).sip6);
				r_req.rx_ptr = _bcm_unpack_ip6(r_req.rx_ptr, (*r_p_session_key).dip6);
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_key->dst_port);
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_key->src_port);
				BCM_UNPACK_U8(r_req.rx_ptr, r_p_session_key->protocol);
			}
			if (*r_req.rx_ptr++ == 1) {
				r_p_session_data = NULL;
			} else {
				r_p_session_data = &r_session_data;
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_data->flags);
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_data->policy);
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_data->inactivity_timeout);
				BCM_UNPACK_U32(r_req.rx_ptr, r_p_session_data->timestamp);
			}

			r_rv = cb(unit, r_p_session_key, r_p_session_data, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_REGEX */

int
bcm_client_sat_endpoint_traverse(
	int	unit,
	uint32	flags,
	bcm_sat_endpoint_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xb59cc366,0xe824ff05,0xe18f2431,0xb51aeeaf,0xc0300b33 };
	bcm_sat_endpoint_info_t	r_endpoint_info;
	bcm_sat_endpoint_info_t *	r_p_endpoint_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_endpoint_info = NULL;
			} else {
				r_p_endpoint_info = &r_endpoint_info;
				r_req.rx_ptr = _bcm_unpack_sat_endpoint_info(r_req.rx_ptr, r_p_endpoint_info);
			}

			r_rv = cb(unit, r_p_endpoint_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_subport_group_traverse(
	int	unit,
	bcm_gport_t	subport_group,
	bcm_subport_port_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xb50c8de4,0x0eedad4b,0x4f656714,0x62ed3ed6,0xecbc999a };
	bcm_gport_t	r_port;
	bcm_subport_config_t	r_config;
	bcm_subport_config_t *	r_p_config;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, subport_group);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			if (*r_req.rx_ptr++ == 1) {
				r_p_config = NULL;
			} else {
				r_p_config = &r_config;
				r_req.rx_ptr = _bcm_unpack_subport_config(r_req.rx_ptr, r_p_config);
			}

			r_rv = cb(unit, r_port, r_p_config, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_subport_port_traverse(
	int	unit,
	bcm_subport_port_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x36115c4e,0x15b39040,0xea52c661,0x326f8213,0x13b775b1 };
	bcm_gport_t	r_port;
	bcm_subport_config_t	r_config;
	bcm_subport_config_t *	r_p_config;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			if (*r_req.rx_ptr++ == 1) {
				r_p_config = NULL;
			} else {
				r_p_config = &r_config;
				r_req.rx_ptr = _bcm_unpack_subport_config(r_req.rx_ptr, r_p_config);
			}

			r_rv = cb(unit, r_port, r_p_config, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_time_interface_traverse(
	int	unit,
	bcm_time_interface_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xb7e7bce3,0xf36ec46a,0x4b1c9ac0,0x8c196613,0x6f327905 };
	bcm_time_interface_t	r_intf;
	bcm_time_interface_t *	r_p_intf;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_intf = NULL;
			} else {
				r_p_intf = &r_intf;
				r_req.rx_ptr = _bcm_unpack_time_interface(r_req.rx_ptr, r_p_intf);
			}

			r_rv = cb(unit, r_p_intf, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_trill_multicast_adjacency_traverse(
	int	unit,
	bcm_trill_multicast_adjacency_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x0ac4451b,0x1b679cf5,0xc07134b4,0xf9190f9a,0x404d3762 };
	bcm_trill_multicast_adjacency_t	r_info;
	bcm_trill_multicast_adjacency_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_trill_multicast_adjacency(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_trill_multicast_entry_traverse(
	int	unit,
	bcm_trill_multicast_entry_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x69e11ce7,0x630dfe6f,0x2da8206d,0x0a0a6755,0x3b399ed8 };
	bcm_trill_multicast_entry_t	r_trill_mc_entry;
	bcm_trill_multicast_entry_t *	r_p_trill_mc_entry;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_trill_mc_entry = NULL;
			} else {
				r_p_trill_mc_entry = &r_trill_mc_entry;
				r_req.rx_ptr = _bcm_unpack_trill_multicast_entry(r_req.rx_ptr, r_p_trill_mc_entry);
			}

			r_rv = cb(unit, r_p_trill_mc_entry, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_trill_multicast_source_traverse(
	int	unit,
	bcm_trill_multicast_source_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x08f576a7,0x7bddad71,0xdc08b493,0x2359ce15,0x9ba1b582 };
	bcm_trill_name_t	r_root_name;
	bcm_trill_name_t	r_source_rbridge_name;
	bcm_gport_t	r_port;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_root_name);
			BCM_UNPACK_U32(r_req.rx_ptr, r_source_rbridge_name);
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);

			r_rv = cb(unit, r_root_name, r_source_rbridge_name, r_port, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_trill_vpn_traverse(
	int	unit,
	bcm_trill_vpn_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xef0ba6f2,0x2f1be987,0xd6790ddb,0xc641032e,0x477b06a0 };
	bcm_trill_vpn_config_t	r_info;
	bcm_trill_vpn_config_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_trill_vpn_config(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */

int
bcm_client_trunk_resilient_traverse(
	int	unit,
	uint32	flags,
	bcm_trunk_resilient_entry_t *	match_entry,
	bcm_trunk_resilient_traverse_cb	trav_fn,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x3fd77f9c,0x943876b9,0x08bf8215,0xb92f2fbb,0x1fcdbfa2 };
	bcm_trunk_resilient_entry_t	r_entry;
	bcm_trunk_resilient_entry_t *	r_p_entry;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U32(r_req.tx_ptr, flags);
		if (match_entry == NULL) {
			BCM_PACK_U8(r_req.tx_ptr, 1);
		} else {
			BCM_PACK_U8(r_req.tx_ptr, 0);
			r_req.tx_ptr = _bcm_pack_trunk_resilient_entry(r_req.tx_ptr, match_entry);
		}

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_entry = NULL;
			} else {
				r_p_entry = &r_entry;
				r_req.rx_ptr = _bcm_unpack_trunk_resilient_entry(r_req.rx_ptr, r_p_entry);
			}

			r_rv = trav_fn(unit, r_p_entry, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_tunnel_initiator_traverse(
	int	unit,
	bcm_tunnel_initiator_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x90aa59df,0x23e558c0,0x152679e9,0xbfdc8a62,0x05e3ca52 };
	bcm_tunnel_initiator_t	r_info;
	bcm_tunnel_initiator_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_tunnel_initiator(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_tunnel_terminator_traverse(
	int	unit,
	bcm_tunnel_terminator_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xebac6b51,0x4b5e8c2d,0xfd8326cf,0x1e467ef5,0x97a852bd };
	bcm_tunnel_terminator_t	r_info;
	bcm_tunnel_terminator_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_tunnel_terminator(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */

int
bcm_client_vlan_cross_connect_traverse(
	int	unit,
	bcm_vlan_cross_connect_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x9b81a1e3,0x30e13ed8,0x2c88e0b6,0x806061d6,0x2d25b128 };
	bcm_vlan_t	r_outer_vlan;
	bcm_vlan_t	r_inner_vlan;
	bcm_gport_t	r_port_1;
	bcm_gport_t	r_port_2;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U16(r_req.rx_ptr, r_outer_vlan);
			BCM_UNPACK_U16(r_req.rx_ptr, r_inner_vlan);
			BCM_UNPACK_U32(r_req.rx_ptr, r_port_1);
			BCM_UNPACK_U32(r_req.rx_ptr, r_port_2);

			r_rv = cb(unit, r_outer_vlan, r_inner_vlan, r_port_1, r_port_2, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_dtag_range_traverse(
	int	unit,
	bcm_vlan_dtag_range_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xecace45d,0x604f598a,0x2bd096c2,0x08717feb,0x18c78766 };
	bcm_gport_t	r_port;
	bcm_vlan_t	r_old_vlan_low;
	bcm_vlan_t	r_old_vlan_high;
	bcm_vlan_t	r_new_vlan;
	int	r_prio;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U16(r_req.rx_ptr, r_old_vlan_low);
			BCM_UNPACK_U16(r_req.rx_ptr, r_old_vlan_high);
			BCM_UNPACK_U16(r_req.rx_ptr, r_new_vlan);
			BCM_UNPACK_U32(r_req.rx_ptr, r_prio);

			r_rv = cb(unit, r_port, r_old_vlan_low, r_old_vlan_high, r_new_vlan, r_prio, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_dtag_traverse(
	int	unit,
	bcm_vlan_dtag_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x9463324c,0x9c4abd42,0xd58d3258,0x97c563e2,0xb4754ba3 };
	bcm_gport_t	r_port;
	bcm_vlan_t	r_old_vlan;
	bcm_vlan_t	r_new_vlan;
	int	r_prio;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U16(r_req.rx_ptr, r_old_vlan);
			BCM_UNPACK_U16(r_req.rx_ptr, r_new_vlan);
			BCM_UNPACK_U32(r_req.rx_ptr, r_prio);

			r_rv = cb(unit, r_port, r_old_vlan, r_new_vlan, r_prio, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_ip_action_traverse(
	int	unit,
	bcm_vlan_ip_action_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xefbb89d5,0x4a559662,0xde80ed51,0x4c007b8f,0x0974bb66 };
	bcm_vlan_ip_t	r_vlan_ip;
	bcm_vlan_action_set_t	r_action;
	bcm_vlan_ip_t *	r_p_vlan_ip;
	bcm_vlan_action_set_t *	r_p_action;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_vlan_ip = NULL;
			} else {
				r_p_vlan_ip = &r_vlan_ip;
				r_req.rx_ptr = _bcm_unpack_vlan_ip(r_req.rx_ptr, r_p_vlan_ip);
			}
			if (*r_req.rx_ptr++ == 1) {
				r_p_action = NULL;
			} else {
				r_p_action = &r_action;
				r_req.rx_ptr = _bcm_unpack_vlan_action_set(r_req.rx_ptr, r_p_action);
			}

			r_rv = cb(unit, r_p_vlan_ip, r_p_action, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_mac_action_traverse(
	int	unit,
	bcm_vlan_mac_action_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xa3ed9bb5,0x865fc75a,0xa70b17e5,0x985c5995,0x70c760f8 };
	bcm_mac_t	r_mac;
	bcm_vlan_action_set_t	r_action;
	bcm_vlan_action_set_t *	r_p_action;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			r_req.rx_ptr = _bcm_unpack_mac(r_req.rx_ptr, r_mac);
			if (*r_req.rx_ptr++ == 1) {
				r_p_action = NULL;
			} else {
				r_p_action = &r_action;
				r_req.rx_ptr = _bcm_unpack_vlan_action_set(r_req.rx_ptr, r_p_action);
			}

			r_rv = cb(unit, r_mac, r_p_action, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_port_protocol_action_traverse(
	int	unit,
	bcm_vlan_port_protocol_action_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x05e54e9f,0xdb836cfa,0xe46d5689,0x89bcfb19,0xff0ee886 };
	bcm_port_t	r_port;
	bcm_port_frametype_t	r_frame;
	bcm_port_ethertype_t	r_ether;
	bcm_vlan_action_set_t	r_action;
	bcm_vlan_action_set_t *	r_p_action;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U32(r_req.rx_ptr, r_frame);
			BCM_UNPACK_U16(r_req.rx_ptr, r_ether);
			if (*r_req.rx_ptr++ == 1) {
				r_p_action = NULL;
			} else {
				r_p_action = &r_action;
				r_req.rx_ptr = _bcm_unpack_vlan_action_set(r_req.rx_ptr, r_p_action);
			}

			r_rv = cb(unit, r_port, r_frame, r_ether, r_p_action, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_translate_action_range_traverse(
	int	unit,
	bcm_vlan_translate_action_range_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x31fa6e34,0xacb376f6,0xc54b4087,0xf40b84c4,0x11d6c6d8 };
	bcm_gport_t	r_port;
	bcm_vlan_t	r_outer_vlan_low;
	bcm_vlan_t	r_outer_vlan_high;
	bcm_vlan_t	r_inner_vlan_low;
	bcm_vlan_t	r_inner_vlan_high;
	bcm_vlan_action_set_t	r_action;
	bcm_vlan_action_set_t *	r_p_action;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U16(r_req.rx_ptr, r_outer_vlan_low);
			BCM_UNPACK_U16(r_req.rx_ptr, r_outer_vlan_high);
			BCM_UNPACK_U16(r_req.rx_ptr, r_inner_vlan_low);
			BCM_UNPACK_U16(r_req.rx_ptr, r_inner_vlan_high);
			if (*r_req.rx_ptr++ == 1) {
				r_p_action = NULL;
			} else {
				r_p_action = &r_action;
				r_req.rx_ptr = _bcm_unpack_vlan_action_set(r_req.rx_ptr, r_p_action);
			}

			r_rv = cb(unit, r_port, r_outer_vlan_low, r_outer_vlan_high, r_inner_vlan_low, r_inner_vlan_high, r_p_action, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_translate_action_traverse(
	int	unit,
	bcm_vlan_translate_action_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x6994f48d,0x4364f04f,0x0c31cf30,0x5487894a,0xccc734a1 };
	bcm_gport_t	r_port;
	bcm_vlan_translate_key_t	r_key_type;
	bcm_vlan_t	r_outer_vlan;
	bcm_vlan_t	r_inner_vlan;
	bcm_vlan_action_set_t	r_action;
	bcm_vlan_action_set_t *	r_p_action;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U32(r_req.rx_ptr, r_key_type);
			BCM_UNPACK_U16(r_req.rx_ptr, r_outer_vlan);
			BCM_UNPACK_U16(r_req.rx_ptr, r_inner_vlan);
			if (*r_req.rx_ptr++ == 1) {
				r_p_action = NULL;
			} else {
				r_p_action = &r_action;
				r_req.rx_ptr = _bcm_unpack_vlan_action_set(r_req.rx_ptr, r_p_action);
			}

			r_rv = cb(unit, r_port, r_key_type, r_outer_vlan, r_inner_vlan, r_p_action, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_translate_egress_action_traverse(
	int	unit,
	bcm_vlan_translate_egress_action_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xc13ddf2f,0xfb47b82d,0x4cda9795,0xc016496d,0xd6ec48fd };
	int	r_port_class;
	bcm_vlan_t	r_outer_vlan;
	bcm_vlan_t	r_inner_vlan;
	bcm_vlan_action_set_t	r_action;
	bcm_vlan_action_set_t *	r_p_action;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port_class);
			BCM_UNPACK_U16(r_req.rx_ptr, r_outer_vlan);
			BCM_UNPACK_U16(r_req.rx_ptr, r_inner_vlan);
			if (*r_req.rx_ptr++ == 1) {
				r_p_action = NULL;
			} else {
				r_p_action = &r_action;
				r_req.rx_ptr = _bcm_unpack_vlan_action_set(r_req.rx_ptr, r_p_action);
			}

			r_rv = cb(unit, r_port_class, r_outer_vlan, r_inner_vlan, r_p_action, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_translate_egress_traverse(
	int	unit,
	bcm_vlan_translate_egress_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x2d222e96,0x2f3ca059,0x8b18e874,0xa3c14190,0xf4512a5b };
	bcm_gport_t	r_port;
	bcm_vlan_t	r_old_vlan;
	bcm_vlan_t	r_new_vlan;
	int	r_prio;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U16(r_req.rx_ptr, r_old_vlan);
			BCM_UNPACK_U16(r_req.rx_ptr, r_new_vlan);
			BCM_UNPACK_U32(r_req.rx_ptr, r_prio);

			r_rv = cb(unit, r_port, r_old_vlan, r_new_vlan, r_prio, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_translate_range_traverse(
	int	unit,
	bcm_vlan_translate_range_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x1fc89dd9,0xc16c9083,0x4aeb7b35,0x1b8d0c83,0x4f104003 };
	bcm_gport_t	r_port;
	bcm_vlan_t	r_old_vlan_low;
	bcm_vlan_t	r_old_vlan_high;
	bcm_vlan_t	r_new_vlan;
	int	r_prio;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U16(r_req.rx_ptr, r_old_vlan_low);
			BCM_UNPACK_U16(r_req.rx_ptr, r_old_vlan_high);
			BCM_UNPACK_U16(r_req.rx_ptr, r_new_vlan);
			BCM_UNPACK_U32(r_req.rx_ptr, r_prio);

			r_rv = cb(unit, r_port, r_old_vlan_low, r_old_vlan_high, r_new_vlan, r_prio, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vlan_translate_traverse(
	int	unit,
	bcm_vlan_translate_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x0640d32f,0x4f1e5c31,0xcdf1e172,0xae1e6445,0x9ce22c65 };
	bcm_gport_t	r_port;
	bcm_vlan_t	r_old_vlan;
	bcm_vlan_t	r_new_vlan;
	int	r_prio;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);
			BCM_UNPACK_U16(r_req.rx_ptr, r_old_vlan);
			BCM_UNPACK_U16(r_req.rx_ptr, r_new_vlan);
			BCM_UNPACK_U32(r_req.rx_ptr, r_prio);

			r_rv = cb(unit, r_port, r_old_vlan, r_new_vlan, r_prio, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vswitch_cross_connect_traverse(
	int	unit,
	bcm_vswitch_cross_connect_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x9e2f0a59,0x55f5b476,0x79588357,0x0d51da96,0x143c212f };
	bcm_vswitch_cross_connect_t	r_gports;
	bcm_vswitch_cross_connect_t *	r_p_gports;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_gports = NULL;
			} else {
				r_p_gports = &r_gports;
				r_req.rx_ptr = _bcm_unpack_vswitch_cross_connect(r_req.rx_ptr, r_p_gports);
			}

			r_rv = cb(unit, r_p_gports, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vswitch_port_traverse(
	int	unit,
	bcm_vlan_t	vsi,
	bcm_vswitch_port_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x49d835d6,0xa0e649e4,0xe5ccb8a1,0x5528cc10,0x2111ef4a };
	bcm_vlan_t	r_vsi;
	bcm_gport_t	r_port;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */
		BCM_PACK_U16(r_req.tx_ptr, vsi);

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			BCM_UNPACK_U16(r_req.rx_ptr, r_vsi);
			BCM_UNPACK_U32(r_req.rx_ptr, r_port);

			r_rv = cb(unit, r_vsi, r_port, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#ifdef	INCLUDE_L3

int
bcm_client_vxlan_tunnel_initiator_traverse(
	int	unit,
	bcm_tunnel_initiator_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xbc51e59b,0x398a74d7,0x01f51080,0x586f40a7,0xd7b07863 };
	bcm_tunnel_initiator_t	r_info;
	bcm_tunnel_initiator_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_tunnel_initiator(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vxlan_tunnel_terminator_traverse(
	int	unit,
	bcm_tunnel_terminator_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x5662fadf,0xfce47da3,0x34b7cd10,0xec6b5a16,0x9f0c27e7 };
	bcm_tunnel_terminator_t	r_info;
	bcm_tunnel_terminator_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_tunnel_terminator(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_vxlan_vpn_traverse(
	int	unit,
	bcm_vxlan_vpn_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0x45431813,0x968e724f,0x056b3aa5,0xb5103248,0x701ce63a };
	bcm_vxlan_vpn_config_t	r_info;
	bcm_vxlan_vpn_config_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_vxlan_vpn_config(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_wlan_client_traverse(
	int	unit,
	bcm_wlan_client_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xa128eb0b,0xefa0c614,0x0584f855,0xfe95099e,0x95ad77ea };
	bcm_wlan_client_t	r_info;
	bcm_wlan_client_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_wlan_client(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

int
bcm_client_wlan_port_traverse(
	int	unit,
	bcm_wlan_port_traverse_cb	cb,
	void *	user_data)
{
	bcm_rlink_traverse_data_t	r_req;
	int	r_rv;
	uint32	r_key[] = {
		0xc5c947cb,0xcb5fa2e9,0x62b91776,0x5327848f,0x5208fc54 };
	bcm_wlan_port_t	r_info;
	bcm_wlan_port_t *	r_p_info;

	sal_memset(&r_req, 0, sizeof(r_req));
	r_rv = bcm_rlink_traverse_request_start(unit, &r_req, r_key);
	if (BCM_SUCCESS(r_rv)) {
		/* Pack request */
		/* Skip unit */

		while (bcm_rlink_traverse_reply_get(unit, &r_req)) {
			/* Unpack reply */
			/* Skip unit */
			if (*r_req.rx_ptr++ == 1) {
				r_p_info = NULL;
			} else {
				r_p_info = &r_info;
				r_req.rx_ptr = _bcm_unpack_wlan_port(r_req.rx_ptr, r_p_info);
			}

			r_rv = cb(unit, r_p_info, user_data);

			if (BCM_FAILURE(r_rv)) {
				break;
			}
		}
		r_rv = bcm_rlink_traverse_request_done(unit, r_rv, &r_req);
	}

	return r_rv;
}

#endif	/* INCLUDE_L3 */

#endif	/* BCM_RPC_SUPPORT */
