/*
 * $Id: mdebug.h 1.5 Broadcom SDK $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __SOC_MDEBUG_H__
#define __SOC_MDEBUG_H__

#include <soc/cmmdebug.h>

#define SOC_DBG_PORT            SOC_CM_MDEBUG_OPT_ENC(0)
#define SOC_DBG_PKT_DATA        SOC_CM_MDEBUG_OPT_ENC(1)
#define SOC_DBG_LINK            SOC_CM_MDEBUG_OPT_ENC(2)
#define SOC_DBG_PCI             SOC_CM_MDEBUG_OPT_ENC(3)
#define SOC_DBG_SCHAN           SOC_CM_MDEBUG_OPT_ENC(4)
#define SOC_DBG_INTR            SOC_CM_MDEBUG_OPT_ENC(5)
#define SOC_DBG_ARL             SOC_CM_MDEBUG_OPT_ENC(6)
#define SOC_DBG_DMA             SOC_CM_MDEBUG_OPT_ENC(7)
#define SOC_DBG_MIIM            SOC_CM_MDEBUG_OPT_ENC(8)
#define SOC_DBG_PHY             SOC_CM_MDEBUG_OPT_ENC(9)
#define SOC_DBG_COUNTER         SOC_CM_MDEBUG_OPT_ENC(10)
#define SOC_DBG_I2C             SOC_CM_MDEBUG_OPT_ENC(11)
#define SOC_DBG_REG             SOC_CM_MDEBUG_OPT_ENC(12)
#define SOC_DBG_MEM             SOC_CM_MDEBUG_OPT_ENC(13)
#define SOC_DBG_100G            SOC_CM_MDEBUG_OPT_ENC(14)
#define SOC_DBG_10G             SOC_CM_MDEBUG_OPT_ENC(15)
#define SOC_DBG_GE              SOC_CM_MDEBUG_OPT_ENC(16)
#define SOC_DBG_TCAM            SOC_CM_MDEBUG_OPT_ENC(17)
#define SOC_DBG_DDR             SOC_CM_MDEBUG_OPT_ENC(18)
#define SOC_DBG_FABRIC          SOC_CM_MDEBUG_OPT_ENC(19)
#define SOC_DBG_INIT            SOC_CM_MDEBUG_OPT_ENC(20)
#define SOC_DBG_STAT            SOC_CM_MDEBUG_OPT_ENC(21)
#define SOC_DBG_MCAST           SOC_CM_MDEBUG_OPT_ENC(22)
#define SOC_DBG_TDM             SOC_CM_MDEBUG_OPT_ENC(23)
#define SOC_DBG_RCPU            SOC_CM_MDEBUG_OPT_ENC(24)
#define SOC_DBG_COSQ            SOC_CM_MDEBUG_OPT_ENC(25)

#define SOC_DBG_COUNT           26

#define SOC_DBG_ERR             SOC_CM_DBG_ERR
#define SOC_DBG_WARN            SOC_CM_DBG_WARN
#define SOC_DBG_NORMAL          SOC_CM_DBG_NORMAL
#define SOC_DBG_VERBOSE         SOC_CM_DBG_VERBOSE
#define SOC_DBG_VVERBOSE        SOC_CM_DBG_VVERBOSE

#define SOC_DBG_NAMES   \
    "POrt",             \
    "PKTdata",          \
    "LInk",             \
    "PCI",              \
    "SChan",            \
    "INTr",             \
    "ARL",              \
    "DMA",              \
    "MIIm",             \
    "PHY",              \
    "CounTeR",          \
    "I2C",              \
    "REG",              \
    "MEM",              \
    "100G",             \
    "10G",              \
    "GE",               \
    "TCAM",             \
    "DDR",              \
    "FABRIC",           \
    "INIT",             \
    "STAT",             \
    "MultiCAST",        \
    "TDM",              \
    "RCPU",             \
    "CosQ",             \
    ""

/*
 * Proper use of debug print macros requires parentheses, e.g.:
 *
 *     SOC_OPT_WARN(("Problem %d with unit %d\n", pr, unit));
 *     SOC_WARN(("Problem %d with unit %d\n", pr, unit));
 *     SOC_DEBUG(SOC_DBG_FOO, ("Problem %d with unit %d\n", pr, unit));
 */

extern soc_cm_mdebug_config_t soc_mdebug_config;

extern int (*soc_mdebug_print)(const char *format, ...)
    COMPILER_ATTRIBUTE_FUNCTION_POINTER ((format (printf, 1, 2)));

#if defined(BROADCOM_DEBUG)

#define SOC_DEBUG_CHECK(enc_) \
    soc_cm_mdebug_check(&soc_mdebug_config, enc_)

#define SOC_DEBUG(enc_, stuff_) \
    if (SOC_DEBUG_CHECK(enc_) && soc_mdebug_print != 0) \
	(*soc_mdebug_print) stuff_

/*
 * Option-specific debug print macros.
 * Source file must define SOC_DEBUG_OPTION to the desired debug
 * option before using these macros, e.g.:
 *
 * #define SOC_DEBUG_OPTION SOC_DBG_PORT
 */

#define SOC_OPT_ERR(stuff_) \
    SOC_DEBUG(SOC_DEBUG_OPTION | SOC_DBG_ERR, stuff_)
#define SOC_OPT_WARN(stuff_) \
    SOC_DEBUG(SOC_DEBUG_OPTION | SOC_DBG_WARN, stuff_)
#define SOC_OPT_NORM(stuff_) \
    SOC_DEBUG(SOC_DEBUG_OPTION | SOC_DBG_NORMAL, stuff_)
#define SOC_OPT_VERB(stuff_) \
    SOC_DEBUG(SOC_DEBUG_OPTION | SOC_DBG_VERBOSE, stuff_)
#define SOC_OPT_VVERB(stuff_) \
    SOC_DEBUG(SOC_DEBUG_OPTION | SOC_DBG_VVERBOSE, stuff_)

/* Module-wide debug print macros (do not require any options enabled) */
#define SOC_ERR(stuff_) \
    SOC_DEBUG(SOC_DBG_ERR, stuff_)
#define SOC_WARN(stuff_) \
    SOC_DEBUG(SOC_DBG_WARN, stuff_)
#define SOC_NORM(stuff_) \
    SOC_DEBUG(SOC_DBG_NORMAL, stuff_)
#define SOC_VERB(stuff_) \
    SOC_DEBUG(SOC_DBG_VERBOSE, stuff_)
#define SOC_VVERB(stuff_) \
    SOC_DEBUG(SOC_DBG_VVERBOSE, stuff_)

extern int soc_mdebug_init(void);

#else

#define SOC_DEBUG_CHECK(enc_) 0
#define SOC_DEBUG(flags_, stuff_)

#define SOC_OPT_ERR(stuff_)
#define SOC_OPT_WARN(stuff_)
#define SOC_OPT_NORM(stuff_)
#define SOC_OPT_VERB(stuff_)
#define SOC_OPT_VVERB(stuff_)

#define SOC_ERR(stuff_)
#define SOC_WARN(stuff_)
#define SOC_NORM(stuff_)
#define SOC_VERB(stuff_)
#define SOC_VVERB(stuff_)

#endif /* defined(BROADCOM_DEBUG) */

#endif /* __SOC_MDEBUG_H__ */
