#!/bin/sh
# $Copyright: Copyright 2012 Broadcom Corporation.
# This program is the proprietary software of Broadcom Corporation
# and/or its licensors, and may only be used, duplicated, modified
# or distributed pursuant to the terms and conditions of a separate,
# written license agreement executed between you and Broadcom
# (an "Authorized License").  Except as set forth in an Authorized
# License, Broadcom grants no license (express or implied), right
# to use, or waiver of any kind with respect to the Software, and
# Broadcom expressly reserves all rights in and to the Software
# and all intellectual property rights therein.  IF YOU HAVE
# NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
# IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
# ALL USE OF THE SOFTWARE.  
#  
# Except as expressly set forth in the Authorized License,
#  
# 1.     This program, including its structure, sequence and organization,
# constitutes the valuable trade secrets of Broadcom, and you shall use
# all reasonable efforts to protect the confidentiality thereof,
# and to use this information only in connection with your use of
# Broadcom integrated circuit products.
#  
# 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
# PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
# REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
# OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
# DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
# NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
# ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
# CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
# OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
# 
# 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
# BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
# INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
# ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
# TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
# THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
# WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
# ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
# $Id$

export DOXYGENVER=1.8.2

# Save start directory
CURDIR=`pwd`

# Allow overrides for PHYMOD and build directories
if [ "$PHYMOD" == "" ]; then
    PHYMOD=$CURDIR/..
fi
if [ "$BLDDIR" == "" ]; then
    BLDDIR=$PHYMOD/doc
fi

# Create Doxygen source directory
DOXYDIR=$BLDDIR/dox
rm -rf $DOXYDIR
mkdir -p $DOXYDIR

# Populate Doxygen source directory
cd $DOXYDIR
ln -s $PHYMOD/include/phymod/phymod_doc.h .
ln -s $PHYMOD/chip/tscf/tier1/tefmod_doc.h .
ln -s $PHYMOD/chip/tscf/tier1/tefmod_cfg_seq.c .
ln -s $PHYMOD/chip/tscf/tier1/tefmod_sc_lkup_table.h .
ln -s $PHYMOD/chip/tscf/tier1/tefmod_enum_defines.c .
ln -s $PHYMOD/chip/tscf/tier1/tefmod_enum_defines.h .
ln -s $PHYMOD/chip/tscf/tier1/tefmod.h .
ln -s $PHYMOD/chip/tsce/tier1/temod.h .
ln -s $PHYMOD/chip/tsce/tier1/temod_enum_defines.h .
ln -s $PHYMOD/chip/tsce/tier1/temod_sc_lkup_table.h .
ln -s $PHYMOD/chip/tsce/tier1/temod_sc_lkup_table.c .
ln -s $PHYMOD/chip/tsce/tier1/temod_diagnostics.c .
ln -s $PHYMOD/chip/tsce/tier1/temod_doc.h .
ln -s $PHYMOD/chip/tsce/tier1/temod_enum_defines.c .
ln -s $PHYMOD/chip/tsce/tier1/temod_cfg_seq.c .
ln -s $PHYMOD/chip/eagle/tier1/eagle_tsc_interface.h
ln -s $PHYMOD/chip/falcon/tier1/falcon_tsc_functions.h
ln -s $PHYMOD/chip/falcon/tier1/falcon_tsc_interface.h
ln -s $PHYMOD/include/phymod/phymod.h .
ln -s $PHYMOD/include/phymod/phymod_diagnostics.h .
ln -s $PHYMOD/include/phymod/all_doc.h .
cd $BLDDIR

# Do the magic
doxygen

# Remove Doxygen source directory
#rm -rf $DOXYDIR

# Return to start
cd $CURDIR
