/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#if defined(INCLUDE_LIB_CINT)

#include <cint_config.h>
#include <cint_types.h>
#include <cint_porting.h>

#if defined(PHYMOD_SUPPORT)

#include <phymod/phymod_diagnostics.h>
#include <phymod/phymod.h>

/* Macros section */

/* Functions section */
CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_core_probe,
                         phymod_access_t*, phymod_access_t, access, 1, 0,
                         phymod_dispatch_type_t*, phymod_dispatch_type_t, type, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_core_identify,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         uint32_t, uint32_t, core_id, 0, 0,
                         uint32_t*, uint32_t, is_identified, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_core_info_get,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         phymod_core_info_t*, phymod_core_info_t, info, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_core_lane_map_get,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         phymod_lane_map_t*, phymod_lane_map_t, lane_map, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_core_lane_map_set,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         phymod_lane_map_t*, phymod_lane_map_t, lane_map, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_core_reset_get,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         phymod_reset_mode_t, phymod_reset_mode_t, reset_mode, 0, 0,
                         phymod_reset_direction_t*, phymod_reset_direction_t, direction, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_core_reset_set,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         phymod_reset_mode_t, phymod_reset_mode_t, reset_mode, 0, 0,
                         phymod_reset_direction_t, phymod_reset_direction_t, direction, 0, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_core_firmware_info_get,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         phymod_core_firmware_info_t*, phymod_core_firmware_info_t, fw_info, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_firmware_core_config_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_firmware_core_config_t*, phymod_firmware_core_config_t, fw_core_config, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_firmware_core_config_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_firmware_core_config_t, phymod_firmware_core_config_t, fw_core_config, 0, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_firmware_lane_config_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_firmware_lane_config_t*, phymod_firmware_lane_config_t, fw_lane_config, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_firmware_lane_config_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_firmware_lane_config_t, phymod_firmware_lane_config_t, fw_lane_config, 0, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_core_pll_sequencer_restart,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         uint32_t, uint32_t, flags, 0, 0,
                         phymod_sequencer_operation_t, phymod_sequencer_operation_t, operation, 0, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_core_wait_event,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         phymod_core_event_t, phymod_core_event_t, event, 0, 0,
                         uint32_t, uint32_t, timeout, 0, 0);

CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0,
                         phymod_phy_rx_restart,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_polarity_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_polarity_t*, phymod_polarity_t, polarity, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_polarity_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_polarity_t*, phymod_polarity_t, polarity, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_tx_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_tx_t*, phymod_tx_t, tx, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_tx_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_tx_t*, phymod_tx_t, tx, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_phy_media_type_tx_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_media_typed_t, phymod_media_typed_t, media, 0, 0,
                         phymod_tx_t*, phymod_tx_t, tx, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_tx_override_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_tx_override_t*, phymod_tx_override_t, tx_override, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_tx_override_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_tx_override_t*, phymod_tx_override_t, tx_override, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_rx_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_rx_t*, phymod_rx_t, rx, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_rx_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_rx_t*, phymod_rx_t, rx, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_reset_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_phy_reset_t*, phymod_phy_reset_t, reset, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_reset_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_phy_reset_t*, phymod_phy_reset_t, reset, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_power_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_phy_power_t*, phymod_phy_power_t, power, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_power_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_phy_power_t*, phymod_phy_power_t, power, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_tx_lane_control_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_tx_lane_control_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_rx_lane_control_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_rx_lane_control_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_fec_enable_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_fec_enable_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_phy_interface_config_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t, uint32_t, flags, 0, 0,
                         phymod_phy_inf_config_t*, phymod_phy_inf_config_t, config, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_phy_interface_config_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t, uint32_t, flags, 0, 0,
                         phymod_phy_inf_config_t*, phymod_phy_inf_config_t, config, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_cl72_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t*, uint32_t, cl72_en, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_cl72_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t, uint32_t, cl72_en, 0, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_cl72_status_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_cl72_status_t*, phymod_cl72_status_t, status, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_autoneg_ability_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_autoneg_ability_t*, phymod_autoneg_ability_t, an_ability_get_type, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_autoneg_ability_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_autoneg_ability_t*, phymod_autoneg_ability_t, an_ability_set_type, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_autoneg_remote_ability_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_autoneg_ability_t*, phymod_autoneg_ability_t, an_ability_get_type, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_phy_autoneg_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_autoneg_control_t*, phymod_autoneg_control_t, an, 1, 0,
                         uint32_t*, uint32_t, an_done, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_autoneg_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_autoneg_control_t*, phymod_autoneg_control_t, an, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_autoneg_status_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_autoneg_status_t*, phymod_autoneg_status_t, status, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_core_init,
                         phymod_core_access_t*, phymod_core_access_t, core, 1, 0,
                         phymod_core_init_config_t*, phymod_core_init_config_t, init_config, 1, 0,
                         phymod_core_status_t*, phymod_core_status_t, core_status, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_init,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_phy_init_config_t*, phymod_phy_init_config_t, init_config, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_phy_loopback_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_loopback_mode_t, phymod_loopback_mode_t, loopback, 0, 0,
                         uint32_t*, uint32_t, enable, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_phy_loopback_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_loopback_mode_t, phymod_loopback_mode_t, loopback, 0, 0,
                         uint32_t, uint32_t, enable, 0, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_rx_pmd_locked_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t*, uint32_t, rx_pmd_locked, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_link_status_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t*, uint32_t, link_status, 1, 0);

CINT_FWRAPPER_CREATE_RP1(int, int, 0, 0,
                         phymod_phy_status_dump,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_pcs_userspeed_get,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_pcs_userspeed_config_t*, phymod_pcs_userspeed_config_t, config, 1, 0);

CINT_FWRAPPER_CREATE_RP2(int, int, 0, 0,
                         phymod_phy_pcs_userspeed_set,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         phymod_pcs_userspeed_config_t*, phymod_pcs_userspeed_config_t, config, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_phy_reg_read,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t, uint32_t, reg_addr, 0, 0,
                         uint32_t*, uint32_t, val, 1, 0);

CINT_FWRAPPER_CREATE_RP3(int, int, 0, 0,
                         phymod_phy_reg_write,
                         phymod_phy_access_t*, phymod_phy_access_t, phy, 1, 0,
                         uint32_t, uint32_t, reg_addr, 0, 0,
                         uint32_t, uint32_t, val, 0, 0);


/* Functions and Macros mapping */
static cint_function_t __cint_functions[] =
{
    CINT_FWRAPPER_ENTRY(phymod_core_probe),
    CINT_FWRAPPER_ENTRY(phymod_core_identify),
    CINT_FWRAPPER_ENTRY(phymod_core_info_get),
    CINT_FWRAPPER_ENTRY(phymod_core_lane_map_get),
    CINT_FWRAPPER_ENTRY(phymod_core_lane_map_set),
    CINT_FWRAPPER_ENTRY(phymod_core_reset_get),
    CINT_FWRAPPER_ENTRY(phymod_core_reset_set),
    CINT_FWRAPPER_ENTRY(phymod_core_firmware_info_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_firmware_core_config_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_firmware_core_config_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_firmware_lane_config_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_firmware_lane_config_set),
    CINT_FWRAPPER_ENTRY(phymod_core_pll_sequencer_restart),
    CINT_FWRAPPER_ENTRY(phymod_core_wait_event),
    CINT_FWRAPPER_ENTRY(phymod_phy_rx_restart),
    CINT_FWRAPPER_ENTRY(phymod_phy_polarity_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_polarity_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_tx_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_tx_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_media_type_tx_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_tx_override_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_tx_override_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_rx_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_rx_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_reset_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_reset_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_power_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_power_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_tx_lane_control_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_tx_lane_control_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_rx_lane_control_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_rx_lane_control_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_fec_enable_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_fec_enable_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_interface_config_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_interface_config_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_cl72_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_cl72_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_cl72_status_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_autoneg_ability_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_autoneg_ability_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_autoneg_remote_ability_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_autoneg_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_autoneg_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_autoneg_status_get),
    CINT_FWRAPPER_ENTRY(phymod_core_init),
    CINT_FWRAPPER_ENTRY(phymod_phy_init),
    CINT_FWRAPPER_ENTRY(phymod_phy_loopback_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_loopback_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_rx_pmd_locked_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_link_status_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_status_dump),
    CINT_FWRAPPER_ENTRY(phymod_phy_pcs_userspeed_get),
    CINT_FWRAPPER_ENTRY(phymod_phy_pcs_userspeed_set),
    CINT_FWRAPPER_ENTRY(phymod_phy_reg_read),
    CINT_FWRAPPER_ENTRY(phymod_phy_reg_write),
    { NULL }
};

/* Functions pointers section */
static cint_function_pointer_t __cint_function_pointers[6];

static int
__cint_fpointer__phymod_bus_read_f(void* user_acc, uint32_t core_addr, uint32_t reg_addr, uint32_t* val)
{
    int returnval;

    cint_interpreter_callback(__cint_function_pointers+0, 4, 1, &user_acc, &core_addr, &reg_addr, &val, &returnval);
    return returnval;
}

static int
__cint_fpointer__phymod_bus_write_f(void* user_acc, uint32_t core_addr, uint32_t reg_addr, uint32_t val)
{
    int returnval;

    cint_interpreter_callback(__cint_function_pointers+1, 4, 1, &user_acc, &core_addr, &reg_addr, &val, &returnval);
    return returnval;
}

static int
__cint_fpointer__phymod_bus_mutex_take_f(void* user_acc)
{
    int returnval;

    cint_interpreter_callback(__cint_function_pointers+2, 1, 1, &user_acc, &returnval);
    return returnval;
}

static int
__cint_fpointer__phymod_bus_mutex_give_f(void* user_acc)
{
    int returnval;

    cint_interpreter_callback(__cint_function_pointers+3, 1, 1, &user_acc, &returnval);
    return returnval;
}

static int
__cint_fpointer__phymod_firmware_loader_f(const phymod_core_access_t* core, uint32_t length, const uint8_t* data)
{
    int returnval;

    cint_interpreter_callback(__cint_function_pointers+4, 3, 1, &core, &length, &data, &returnval);
    return returnval;
}


static cint_parameter_desc_t __cint_parameters_phymod_bus_read_f[] =
{
    {"int", "r", 0, 0},
    {"void", "user_acc", 1, 0},
    {"uint32_t", "core_addr", 0, 0},
    {"uint32_t", "reg_addr", 0, 0},
    {"uint32_t", "val", 1, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_parameters_phymod_bus_write_f[] =
{
    {"int", "r", 0, 0},
    {"void", "user_acc", 1, 0},
    {"uint32_t", "core_addr", 0, 0},
    {"uint32_t", "reg_addr", 0, 0},
    {"uint32_t", "val", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_parameters_phymod_bus_mutex_take_f[] =
{
    {"int", "r", 0, 0},
    {"void", "user_acc", 1, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_parameters_phymod_bus_mutex_give_f[] =
{
    {"int", "r", 0, 0},
    {"void", "user_acc", 1, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_parameters_phymod_firmware_loader_f[] =
{
    {"int", "r", 0, 0},
    {"const phymod_core_access_t", "core", 1, 0},
    {"uint32_t", "length", 0, 0},
    {"const uint8_t", "data", 1, 0},
    { NULL }
};


static cint_function_pointer_t __cint_function_pointers[] = 
{
    {
    "phymod_bus_read_f",
    (cint_fpointer_t) __cint_fpointer__phymod_bus_read_f,
    __cint_parameters_phymod_bus_read_f
    },
    {
    "phymod_bus_write_f",
    (cint_fpointer_t) __cint_fpointer__phymod_bus_write_f,
    __cint_parameters_phymod_bus_write_f
    },
    {
    "phymod_bus_mutex_take_f",
    (cint_fpointer_t) __cint_fpointer__phymod_bus_mutex_take_f,
    __cint_parameters_phymod_bus_mutex_take_f
    },
    {
    "phymod_bus_mutex_give_f",
    (cint_fpointer_t) __cint_fpointer__phymod_bus_mutex_give_f,
    __cint_parameters_phymod_bus_mutex_give_f
    },
    {
    "phymod_firmware_loader_f",
    (cint_fpointer_t) __cint_fpointer__phymod_firmware_loader_f,
    __cint_parameters_phymod_firmware_loader_f
    },
    { NULL }
};

/* Structs section */
static void*
__cint_maddr__phymod_bus_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_bus_t* s = (phymod_bus_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->bus_name);break;
        case 1: rv = &(s->read);break;
        case 2: rv = &(s->write);break;
        case 3: rv = &(s->mutex_take);break;
        case 4: rv = &(s->mutex_give);break;
        case 5: rv = &(s->bus_capabilities);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_access_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_access_t* s = (phymod_access_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->user_acc);break;
        case 1: rv = &(s->bus);break;
        case 2: rv = &(s->flags);break;
        case 3: rv = &(s->lane);break;
        case 4: rv = &(s->addr);break;
        case 5: rv = &(s->devad);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_core_access_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_core_access_t* s = (phymod_core_access_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->access);break;
        case 1: rv = &(s->type);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_phy_access_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_phy_access_t* s = (phymod_phy_access_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->access);break;
        case 1: rv = &(s->type);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_value_override_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_value_override_t* s = (phymod_value_override_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->enable);break;
        case 1: rv = &(s->value);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_core_info_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_core_info_t* s = (phymod_core_info_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->core_version);break;
        case 1: rv = &(s->serdes_id);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_lane_map_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_lane_map_t* s = (phymod_lane_map_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->num_of_lanes);break;
        case 1: rv = &(s->lane_map_rx);break;
        case 2: rv = &(s->lane_map_tx);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_core_firmware_info_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_core_firmware_info_t* s = (phymod_core_firmware_info_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->fw_version);break;
        case 1: rv = &(s->fw_crc);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_firmware_core_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_firmware_core_config_t* s = (phymod_firmware_core_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->CoreConfigFromPCS);break;
        case 1: rv = &(s->VcoRate);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_firmware_lane_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_firmware_lane_config_t* s = (phymod_firmware_lane_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->LaneConfigFromPCS);break;
        case 1: rv = &(s->AnEnabled);break;
        case 2: rv = &(s->DfeOn);break;
        case 3: rv = &(s->ForceBrDfe);break;
        case 4: rv = &(s->MediaType);break;
        case 5: rv = &(s->UnreliableLos);break;
        case 6: rv = &(s->ScramblingDisable);break;
        case 7: rv = &(s->Cl72Enable);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_polarity_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_polarity_t* s = (phymod_polarity_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->rx_polarity);break;
        case 1: rv = &(s->tx_polarity);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_tx_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_tx_t* s = (phymod_tx_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->pre);break;
        case 1: rv = &(s->main);break;
        case 2: rv = &(s->post);break;
        case 3: rv = &(s->post2);break;
        case 4: rv = &(s->post3);break;
        case 5: rv = &(s->amp);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_tx_override_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_tx_override_t* s = (phymod_tx_override_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->phase_interpolator);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_rx_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_rx_t* s = (phymod_rx_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->vga);break;
        case 1: rv = &(s->num_of_dfe_taps);break;
        case 2: rv = &(s->dfe);break;
        case 3: rv = &(s->peaking_filter);break;
        case 4: rv = &(s->low_freq_peaking_filter);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_phy_reset_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_phy_reset_t* s = (phymod_phy_reset_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->rx);break;
        case 1: rv = &(s->tx);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_phy_power_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_phy_power_t* s = (phymod_phy_power_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->rx);break;
        case 1: rv = &(s->tx);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_phy_inf_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_phy_inf_config_t* s = (phymod_phy_inf_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->interface_type);break;
        case 1: rv = &(s->data_rate);break;
        case 2: rv = &(s->interface_modes);break;
        case 3: rv = &(s->ref_clock);break;
        case 4: rv = &(s->pll_divider_req);break;
        case 5: rv = &(s->device_aux_modes);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_cl72_status_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_cl72_status_t* s = (phymod_cl72_status_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->enabled);break;
        case 1: rv = &(s->locked);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_autoneg_ability_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_autoneg_ability_t* s = (phymod_autoneg_ability_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->an_tech_ability);break;
        case 1: rv = &(s->cl73bam_ability);break;
        case 2: rv = &(s->cl37bam_ability);break;
        case 3: rv = &(s->an_fec);break;
        case 4: rv = &(s->an_cl72);break;
        case 5: rv = &(s->an_hg2);break;
        case 6: rv = &(s->capabilities);break;
        case 7: rv = &(s->sgmii_speed);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_autoneg_control_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_autoneg_control_t* s = (phymod_autoneg_control_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->an_mode);break;
        case 1: rv = &(s->num_lane_adv);break;
        case 2: rv = &(s->flags);break;
        case 3: rv = &(s->enable);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_autoneg_status_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_autoneg_status_t* s = (phymod_autoneg_status_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->enabled);break;
        case 1: rv = &(s->locked);break;
        case 2: rv = &(s->data_rate);break;
        case 3: rv = &(s->interface);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_core_init_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_core_init_config_t* s = (phymod_core_init_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->lane_map);break;
        case 1: rv = &(s->firmware_load_method);break;
        case 2: rv = &(s->firmware_loader);break;
        case 3: rv = &(s->firmware_core_config);break;
        case 4: rv = &(s->interface);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_core_status_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_core_status_t* s = (phymod_core_status_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->pmd_active);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_phy_init_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_phy_init_config_t* s = (phymod_phy_init_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->polarity);break;
        case 1: rv = &(s->tx);break;
        case 2: rv = &(s->cl72_en);break;
        case 3: rv = &(s->an_en);break;
        default: rv = NULL; break;
    }
    return rv;
}

static void*
__cint_maddr__phymod_pcs_userspeed_config_t(void* p, int mnum, cint_struct_type_t* parent)
{
    void* rv;
    phymod_pcs_userspeed_config_t* s = (phymod_pcs_userspeed_config_t*) p;
    switch(mnum)
    {
        case 0: rv = &(s->mode);break;
        case 1: rv = &(s->param);break;
        case 2: rv = &(s->value);break;
        case 3: rv = &(s->current_entry);break;
        default: rv = NULL; break;
    }
    return rv;
}


static cint_parameter_desc_t __cint_struct_members__phymod_bus_t[] = 
{
    {"char", "bus_name", 1, 0},
    {"phymod_bus_read_f", "read", 0, 0},
    {"phymod_bus_write_f", "write", 0, 0},
    {"phymod_bus_mutex_take_f", "mutex_take", 0, 0},
    {"phymod_bus_mutex_give_f", "mutex_give", 0, 0},
    {"uint32_t", "bus_capabilities", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_access_t[] = 
{
    {"void", "user_acc", 1, 0},
    {"phymod_bus_t", "bus", 1, 0},
    {"uint32_t", "flags", 0, 0},
    {"uint32_t", "lane", 0, 0},
    {"uint32_t", "addr", 0, 0},
    {"uint32_t", "devad", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_core_access_t[] = 
{
    {"phymod_access_t", "access", 0, 0},
    {"phymod_dispatch_type_t", "type", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_phy_access_t[] = 
{
    {"phymod_access_t", "access", 0, 0},
    {"phymod_dispatch_type_t", "type", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_value_override_t[] = 
{
    {"uint32_t", "enable", 0, 0},
    {"uint32_t", "value", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_core_info_t[] = 
{
    {"phymod_core_version_t", "core_version", 0, 0},
    {"uint32_t", "serdes_id", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_lane_map_t[] = 
{
    {"uint32_t", "num_of_lanes", 0, 0},
    {"uint32_t", "lane_map_rx", 0, PHYMOD_MAX_LANES_PER_CORE},
    {"uint32_t", "lane_map_tx", 0, PHYMOD_MAX_LANES_PER_CORE},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_core_firmware_info_t[] = 
{
    {"uint32_t", "fw_version", 0, 0},
    {"uint32_t", "fw_crc", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_firmware_core_config_t[] = 
{
    {"uint32_t", "CoreConfigFromPCS", 0, 0},
    {"uint32_t", "VcoRate", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_firmware_lane_config_t[] = 
{
    {"uint32_t", "LaneConfigFromPCS", 0, 0},
    {"uint32_t", "AnEnabled", 0, 0},
    {"uint32_t", "DfeOn", 0, 0},
    {"uint32_t", "ForceBrDfe", 0, 0},
    {"phymod_firmware_media_type_t", "MediaType", 0, 0},
    {"uint32_t", "UnreliableLos", 0, 0},
    {"uint32_t", "ScramblingDisable", 0, 0},
    {"uint32_t", "Cl72Enable", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_polarity_t[] = 
{
    {"uint32_t", "rx_polarity", 0, 0},
    {"uint32_t", "tx_polarity", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_tx_t[] = 
{
    {"int8_t", "pre", 0, 0},
    {"int8_t", "main", 0, 0},
    {"int8_t", "post", 0, 0},
    {"int8_t", "post2", 0, 0},
    {"int8_t", "post3", 0, 0},
    {"int8_t", "amp", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_tx_override_t[] = 
{
    {"phymod_value_override_t", "phase_interpolator", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_rx_t[] = 
{
    {"phymod_value_override_t", "vga", 0, 0},
    {"uint32_t", "num_of_dfe_taps", 0, 0},
    {"phymod_value_override_t", "dfe", 0, PHYMOD_NUM_DFE_TAPS},
    {"phymod_value_override_t", "peaking_filter", 0, 0},
    {"phymod_value_override_t", "low_freq_peaking_filter", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_phy_reset_t[] = 
{
    {"phymod_reset_direction_t", "rx", 0, 0},
    {"phymod_reset_direction_t", "tx", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_phy_power_t[] = 
{
    {"phymod_power_t", "rx", 0, 0},
    {"phymod_power_t", "tx", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_phy_inf_config_t[] = 
{
    {"phymod_interface_t", "interface_type", 0, 0},
    {"uint32_t", "data_rate", 0, 0},
    {"uint32_t", "interface_modes", 0, 0},
    {"phymod_ref_clk_t", "ref_clock", 0, 0},
    {"uint16_t", "pll_divider_req", 0, 0},
    {"void *", "device_aux_modes", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_cl72_status_t[] = 
{
    {"uint32_t", "enabled", 0, 0},
    {"uint32_t", "locked", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_autoneg_ability_t[] = 
{
    {"uint32_t", "an_tech_ability", 0, 0},
    {"uint32_t", "cl73bam_ability", 0, 0},
    {"uint32_t", "cl37bam_ability", 0, 0},
    {"uint32_t", "an_fec", 0, 0},
    {"uint32_t", "an_cl72", 0, 0},
    {"uint32_t", "an_hg2", 0, 0},
    {"uint32_t", "capabilities", 0, 0},
    {"phymod_cl37_sgmii_speed_t", "sgmii_speed", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_autoneg_control_t[] = 
{
    {"phymod_an_mode_type_t", "an_mode", 0, 0},
    {"uint32_t", "num_lane_adv", 0, 0},
    {"uint32_t", "flags", 0, 0},
    {"uint32_t", "enable", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_autoneg_status_t[] = 
{
    {"uint32_t", "enabled", 0, 0},
    {"uint32_t", "locked", 0, 0},
    {"uint32_t", "data_rate", 0, 0},
    {"phymod_interface_t", "interface", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_core_init_config_t[] = 
{
    {"phymod_lane_map_t", "lane_map", 0, 0},
    {"phymod_firmware_load_method_t", "firmware_load_method", 0, 0},
    {"phymod_firmware_loader_f", "firmware_loader", 0, 0},
    {"phymod_firmware_core_config_t", "firmware_core_config", 0, 0},
    {"phymod_phy_inf_config_t", "interface", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_core_status_t[] = 
{
    {"uint32_t", "pmd_active", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_phy_init_config_t[] = 
{
    {"phymod_polarity_t", "polarity", 0, 0},
    {"phymod_tx_t", "tx", 0, PHYMOD_MAX_LANES_PER_CORE},
    {"uint32_t", "cl72_en", 0, 0},
    {"uint32_t", "an_en", 0, 0},
    { NULL }
};

static cint_parameter_desc_t __cint_struct_members__phymod_pcs_userspeed_config_t[] = 
{
    {"phymod_pcs_userspeed_mode_t", "mode", 0, 0},
    {"phymod_pcs_userspeed_param_t", "param", 0, 0},
    {"uint32_t", "value", 0, 0},
    {"uint16_t", "current_entry", 0, 0},
    { NULL }
};


static cint_struct_type_t __cint_structures[] =
{
    {
    "phymod_bus_t",
    sizeof(phymod_bus_t),
    __cint_struct_members__phymod_bus_t,
    __cint_maddr__phymod_bus_t
    },
    {
    "phymod_access_t",
    sizeof(phymod_access_t),
    __cint_struct_members__phymod_access_t,
    __cint_maddr__phymod_access_t
    },
    {
    "phymod_core_access_t",
    sizeof(phymod_core_access_t),
    __cint_struct_members__phymod_core_access_t,
    __cint_maddr__phymod_core_access_t
    },
    {
    "phymod_phy_access_t",
    sizeof(phymod_phy_access_t),
    __cint_struct_members__phymod_phy_access_t,
    __cint_maddr__phymod_phy_access_t
    },
    {
    "phymod_value_override_t",
    sizeof(phymod_value_override_t),
    __cint_struct_members__phymod_value_override_t,
    __cint_maddr__phymod_value_override_t
    },
    {
    "phymod_core_info_t",
    sizeof(phymod_core_info_t),
    __cint_struct_members__phymod_core_info_t,
    __cint_maddr__phymod_core_info_t
    },
    {
    "phymod_lane_map_t",
    sizeof(phymod_lane_map_t),
    __cint_struct_members__phymod_lane_map_t,
    __cint_maddr__phymod_lane_map_t
    },
    {
    "phymod_core_firmware_info_t",
    sizeof(phymod_core_firmware_info_t),
    __cint_struct_members__phymod_core_firmware_info_t,
    __cint_maddr__phymod_core_firmware_info_t
    },
    {
    "phymod_firmware_core_config_t",
    sizeof(phymod_firmware_core_config_t),
    __cint_struct_members__phymod_firmware_core_config_t,
    __cint_maddr__phymod_firmware_core_config_t
    },
    {
    "phymod_firmware_lane_config_t",
    sizeof(phymod_firmware_lane_config_t),
    __cint_struct_members__phymod_firmware_lane_config_t,
    __cint_maddr__phymod_firmware_lane_config_t
    },
    {
    "phymod_polarity_t",
    sizeof(phymod_polarity_t),
    __cint_struct_members__phymod_polarity_t,
    __cint_maddr__phymod_polarity_t
    },
    {
    "phymod_tx_t",
    sizeof(phymod_tx_t),
    __cint_struct_members__phymod_tx_t,
    __cint_maddr__phymod_tx_t
    },
    {
    "phymod_tx_override_t",
    sizeof(phymod_tx_override_t),
    __cint_struct_members__phymod_tx_override_t,
    __cint_maddr__phymod_tx_override_t
    },
    {
    "phymod_rx_t",
    sizeof(phymod_rx_t),
    __cint_struct_members__phymod_rx_t,
    __cint_maddr__phymod_rx_t
    },
    {
    "phymod_phy_reset_t",
    sizeof(phymod_phy_reset_t),
    __cint_struct_members__phymod_phy_reset_t,
    __cint_maddr__phymod_phy_reset_t
    },
    {
    "phymod_phy_power_t",
    sizeof(phymod_phy_power_t),
    __cint_struct_members__phymod_phy_power_t,
    __cint_maddr__phymod_phy_power_t
    },
    {
    "phymod_phy_inf_config_t",
    sizeof(phymod_phy_inf_config_t),
    __cint_struct_members__phymod_phy_inf_config_t,
    __cint_maddr__phymod_phy_inf_config_t
    },
    {
    "phymod_cl72_status_t",
    sizeof(phymod_cl72_status_t),
    __cint_struct_members__phymod_cl72_status_t,
    __cint_maddr__phymod_cl72_status_t
    },
    {
    "phymod_autoneg_ability_t",
    sizeof(phymod_autoneg_ability_t),
    __cint_struct_members__phymod_autoneg_ability_t,
    __cint_maddr__phymod_autoneg_ability_t
    },
    {
    "phymod_autoneg_control_t",
    sizeof(phymod_autoneg_control_t),
    __cint_struct_members__phymod_autoneg_control_t,
    __cint_maddr__phymod_autoneg_control_t
    },
    {
    "phymod_autoneg_status_t",
    sizeof(phymod_autoneg_status_t),
    __cint_struct_members__phymod_autoneg_status_t,
    __cint_maddr__phymod_autoneg_status_t
    },
    {
    "phymod_core_init_config_t",
    sizeof(phymod_core_init_config_t),
    __cint_struct_members__phymod_core_init_config_t,
    __cint_maddr__phymod_core_init_config_t
    },
    {
    "phymod_core_status_t",
    sizeof(phymod_core_status_t),
    __cint_struct_members__phymod_core_status_t,
    __cint_maddr__phymod_core_status_t
    },
    {
    "phymod_phy_init_config_t",
    sizeof(phymod_phy_init_config_t),
    __cint_struct_members__phymod_phy_init_config_t,
    __cint_maddr__phymod_phy_init_config_t
    },
    {
    "phymod_pcs_userspeed_config_t",
    sizeof(phymod_pcs_userspeed_config_t),
    __cint_struct_members__phymod_pcs_userspeed_config_t,
    __cint_maddr__phymod_pcs_userspeed_config_t
    },
    { NULL }
};


/* Enums section */
static cint_enum_map_t __cint_enum_map__phymod_dispatch_type_t[] =
{
#ifdef PHYMOD_EAGLE_SUPPORT
    { "phymodDispatchTypeEagle", phymodDispatchTypeEagle },
#endif /*PHYMOD_EAGLE_SUPPORT  */
#ifdef PHYMOD_FALCON_SUPPORT
    { "phymodDispatchTypeFalcon", phymodDispatchTypeFalcon },
#endif /*PHYMOD_FALCON_SUPPORT  */
#ifdef PHYMOD_QSGMIIE_SUPPORT
    { "phymodDispatchTypeQsgmiie", phymodDispatchTypeQsgmiie },
#endif /*PHYMOD_QSGMIIE_SUPPORT  */
#ifdef PHYMOD_TSCE_SUPPORT
    { "phymodDispatchTypeTsce", phymodDispatchTypeTsce },
#endif /*PHYMOD_TSCE_SUPPORT  */
#ifdef PHYMOD_TSCF_SUPPORT
    { "phymodDispatchTypeTscf", phymodDispatchTypeTscf },
#endif /*PHYMOD_TSCF_SUPPORT  */
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_core_version_t[] =
{
    { "phymodCoreVersionFalconA0", phymodCoreVersionFalconA0 },
    { "phymodCoreVersionEagleA0", phymodCoreVersionEagleA0 },
    { "phymodCoreVersionQsgmiieA0", phymodCoreVersionQsgmiieA0 },
    { "phymodCoreVersionTsce4A0", phymodCoreVersionTsce4A0 },
    { "phymodCoreVersionTsce12A0", phymodCoreVersionTsce12A0 },
    { "phymodCoreVersionTscfA0", phymodCoreVersionTscfA0 },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_reset_mode_t[] =
{
    { "phymodResetModeHard", phymodResetModeHard },
    { "phymodResetModeSoft", phymodResetModeSoft },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_reset_direction_t[] =
{
    { "phymodResetDirectionIn", phymodResetDirectionIn },
    { "phymodResetDirectionOut", phymodResetDirectionOut },
    { "phymodResetDirectionInOut", phymodResetDirectionInOut },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_firmware_media_type_t[] =
{
    { "phymodFirmwareMediaTypePcbTraceBackPlane", phymodFirmwareMediaTypePcbTraceBackPlane },
    { "phymodFirmwareMediaTypeCopperCable", phymodFirmwareMediaTypeCopperCable },
    { "phymodFirmwareMediaTypeOptics", phymodFirmwareMediaTypeOptics },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_sequencer_operation_t[] =
{
    { "phymodSeqOpStop", phymodSeqOpStop },
    { "phymodSeqOpStart", phymodSeqOpStart },
    { "phymodSeqOpRestart", phymodSeqOpRestart },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_core_event_t[] =
{
    { "phymodCoreEventPllLock", phymodCoreEventPllLock },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_media_typed_t[] =
{
    { "phymodMediaTypeChipToChip", phymodMediaTypeChipToChip },
    { "phymodMediaTypeShort", phymodMediaTypeShort },
    { "phymodMediaTypeMid", phymodMediaTypeMid },
    { "phymodMediaTypeLong", phymodMediaTypeLong },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_power_t[] =
{
    { "phymodPowerOff", phymodPowerOff },
    { "phymodPowerOn", phymodPowerOn },
    { "phymodPowerOffOn", phymodPowerOffOn },
    { "phymodPowerNoChange", phymodPowerNoChange },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_interface_t[] =
{
    { "phymodInterfaceBypass", phymodInterfaceBypass },
    { "phymodInterfaceSR", phymodInterfaceSR },
    { "phymodInterfaceKX", phymodInterfaceKX },
    { "phymodInterfaceKX4", phymodInterfaceKX4 },
    { "phymodInterfaceKR", phymodInterfaceKR },
    { "phymodInterfaceKR2", phymodInterfaceKR2 },
    { "phymodInterfaceKR4", phymodInterfaceKR4 },
    { "phymodInterfaceCX", phymodInterfaceCX },
    { "phymodInterfaceCX2", phymodInterfaceCX2 },
    { "phymodInterfaceCX4", phymodInterfaceCX4 },
    { "phymodInterfaceCR", phymodInterfaceCR },
    { "phymodInterfaceCR2", phymodInterfaceCR2 },
    { "phymodInterfaceCR4", phymodInterfaceCR4 },
    { "phymodInterfaceCR10", phymodInterfaceCR10 },
    { "phymodInterfaceXFI", phymodInterfaceXFI },
    { "phymodInterfaceSFI", phymodInterfaceSFI },
    { "phymodInterfaceXGMII", phymodInterfaceXGMII },
    { "phymodInterface1000X", phymodInterface1000X },
    { "phymodInterfaceSGMII", phymodInterfaceSGMII },
    { "phymodInterfaceRXAUI", phymodInterfaceRXAUI },
    { "phymodInterfaceX2", phymodInterfaceX2 },
    { "phymodInterfaceXLAUI", phymodInterfaceXLAUI },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_ref_clk_t[] =
{
    { "phymodRefClk156Mhz", phymodRefClk156Mhz },
    { "phymodRefClk125Mhz", phymodRefClk125Mhz },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_an_mode_type_t[] =
{
    { "phymod_AN_MODE_CL73", phymod_AN_MODE_CL73 },
    { "phymod_AN_MODE_CL37", phymod_AN_MODE_CL37 },
    { "phymod_AN_MODE_CL73BAM", phymod_AN_MODE_CL73BAM },
    { "phymod_AN_MODE_CL37BAM", phymod_AN_MODE_CL37BAM },
    { "phymod_AN_MODE_HPAM", phymod_AN_MODE_HPAM },
    { "phymod_AN_MODE_SGMII", phymod_AN_MODE_SGMII },
    { "phymod_AN_MODE_NONE", phymod_AN_MODE_NONE },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_cl37_sgmii_speed_t[] =
{
    { "phymod_CL37_SGMII_10M", phymod_CL37_SGMII_10M },
    { "phymod_CL37_SGMII_100M", phymod_CL37_SGMII_100M },
    { "phymod_CL37_SGMII_1000M", phymod_CL37_SGMII_1000M },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_firmware_load_method_t[] =
{
    { "phymodFirmwareLoadMethodNone", phymodFirmwareLoadMethodNone },
    { "phymodFirmwareLoadMethodInternal", phymodFirmwareLoadMethodInternal },
    { "phymodFirmwareLoadMethodExternal", phymodFirmwareLoadMethodExternal },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_loopback_mode_t[] =
{
    { "phymodLoopbackGlobal", phymodLoopbackGlobal },
    { "phymodLoopbackGlobalPMD", phymodLoopbackGlobalPMD },
    { "phymodLoopbackRemotePMD", phymodLoopbackRemotePMD },
    { "phymodLoopbackRemotePCS", phymodLoopbackRemotePCS },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_pcs_userspeed_mode_t[] =
{
    { "phymodPcsUserSpeedModeST", phymodPcsUserSpeedModeST },
    { "phymodPcsUserSpeedModeHTO", phymodPcsUserSpeedModeHTO },
    { NULL }
};

static cint_enum_map_t __cint_enum_map__phymod_pcs_userspeed_param_t[] =
{
    { "phymodPcsUserSpeedParamEntry", phymodPcsUserSpeedParamEntry },
    { "phymodPcsUserSpeedParamHCD", phymodPcsUserSpeedParamHCD },
    { "phymodPcsUserSpeedParamClear", phymodPcsUserSpeedParamClear },
    { "phymodPcsUserSpeedParamPllDiv", phymodPcsUserSpeedParamPllDiv },
    { "phymodPcsUserSpeedParamPmaOS", phymodPcsUserSpeedParamPmaOS },
    { "phymodPcsUserSpeedParamScramble", phymodPcsUserSpeedParamScramble },
    { "phymodPcsUserSpeedParamEncode", phymodPcsUserSpeedParamEncode },
    { "phymodPcsUserSpeedParamCl48CheckEnd", phymodPcsUserSpeedParamCl48CheckEnd },
    { "phymodPcsUserSpeedParamBlkSync", phymodPcsUserSpeedParamBlkSync },
    { "phymodPcsUserSpeedParamReorder", phymodPcsUserSpeedParamReorder },
    { "phymodPcsUserSpeedParamCl36Enable", phymodPcsUserSpeedParamCl36Enable },
    { "phymodPcsUserSpeedParamDescr1", phymodPcsUserSpeedParamDescr1 },
    { "phymodPcsUserSpeedParamDecode1", phymodPcsUserSpeedParamDecode1 },
    { "phymodPcsUserSpeedParamDeskew", phymodPcsUserSpeedParamDeskew },
    { "phymodPcsUserSpeedParamDescr2", phymodPcsUserSpeedParamDescr2 },
    { "phymodPcsUserSpeedParamDescr2ByteDel", phymodPcsUserSpeedParamDescr2ByteDel },
    { "phymodPcsUserSpeedParamBrcm64B66", phymodPcsUserSpeedParamBrcm64B66 },
    { "phymodPcsUserSpeedParamSgmii", phymodPcsUserSpeedParamSgmii },
    { "phymodPcsUserSpeedParamClkcnt0", phymodPcsUserSpeedParamClkcnt0 },
    { "phymodPcsUserSpeedParamClkcnt1", phymodPcsUserSpeedParamClkcnt1 },
    { "phymodPcsUserSpeedParamLpcnt0", phymodPcsUserSpeedParamLpcnt0 },
    { "phymodPcsUserSpeedParamLpcnt1", phymodPcsUserSpeedParamLpcnt1 },
    { "phymodPcsUserSpeedParamMacCGC", phymodPcsUserSpeedParamMacCGC },
    { "phymodPcsUserSpeedParamRepcnt", phymodPcsUserSpeedParamRepcnt },
    { "phymodPcsUserSpeedParamCrdtEn", phymodPcsUserSpeedParamCrdtEn },
    { "phymodPcsUserSpeedParamPcsClkcnt", phymodPcsUserSpeedParamPcsClkcnt },
    { "phymodPcsUserSpeedParamPcsCGC", phymodPcsUserSpeedParamPcsCGC },
    { "phymodPcsUserSpeedParamCl72En", phymodPcsUserSpeedParamCl72En },
    { "phymodPcsUserSpeedParamNumOfLanes", phymodPcsUserSpeedParamNumOfLanes },
    { NULL }
};


static cint_enum_type_t __cint_enums[] =
{
    {"phymod_dispatch_type_t", __cint_enum_map__phymod_dispatch_type_t },
    {"phymod_core_version_t", __cint_enum_map__phymod_core_version_t },
    {"phymod_reset_mode_t", __cint_enum_map__phymod_reset_mode_t },
    {"phymod_reset_direction_t", __cint_enum_map__phymod_reset_direction_t },
    {"phymod_firmware_media_type_t", __cint_enum_map__phymod_firmware_media_type_t },
    {"phymod_sequencer_operation_t", __cint_enum_map__phymod_sequencer_operation_t },
    {"phymod_core_event_t", __cint_enum_map__phymod_core_event_t },
    {"phymod_media_typed_t", __cint_enum_map__phymod_media_typed_t },
    {"phymod_power_t", __cint_enum_map__phymod_power_t },
    {"phymod_interface_t", __cint_enum_map__phymod_interface_t },
    {"phymod_ref_clk_t", __cint_enum_map__phymod_ref_clk_t },
    {"phymod_an_mode_type_t", __cint_enum_map__phymod_an_mode_type_t },
    {"phymod_cl37_sgmii_speed_t", __cint_enum_map__phymod_cl37_sgmii_speed_t },
    {"phymod_firmware_load_method_t", __cint_enum_map__phymod_firmware_load_method_t },
    {"phymod_loopback_mode_t", __cint_enum_map__phymod_loopback_mode_t },
    {"phymod_pcs_userspeed_mode_t", __cint_enum_map__phymod_pcs_userspeed_mode_t },
    {"phymod_pcs_userspeed_param_t", __cint_enum_map__phymod_pcs_userspeed_param_t },
    { NULL }
};

/* Defines section */
static cint_constants_t __cint_constants[] =
{
    { "PHYMOD_MAX_LANES_PER_CORE", PHYMOD_MAX_LANES_PER_CORE },
    { "PHYMOD_BUS_CA_WR_MODIFY", PHYMOD_BUS_CA_WR_MODIFY },
    { "PHYMOD_BUS_CA_LANE_CTRL", PHYMOD_BUS_CA_LANE_CTRL },
    { "PHYMOD_PHYMOD_ACC_F_CLAUSE45", PHYMOD_PHYMOD_ACC_F_CLAUSE45 },
    { "PHYMOD_SEQ_FLAGS_WAIT_UNTIL_DONE", PHYMOD_SEQ_FLAGS_WAIT_UNTIL_DONE },
    { "PHYMOD_TIMEOUT_DEFAULT", PHYMOD_TIMEOUT_DEFAULT },
    { "PHYMOD_TX_DO_NOT_CHANGE_VAL", PHYMOD_TX_DO_NOT_CHANGE_VAL },
    { "PHYMOD_NUM_DFE_TAPS", PHYMOD_NUM_DFE_TAPS },
    { "PHYMOD_DEFAULT_RATE", PHYMOD_DEFAULT_RATE },
    { "PHYMOD_INTERFACE_MODES_HIGIG", PHYMOD_INTERFACE_MODES_HIGIG },
    { "PHYMOD_INTERFACE_MODES_OS2", PHYMOD_INTERFACE_MODES_OS2 },
    { "PHYMOD_INTERFACE_MODES_SCR", PHYMOD_INTERFACE_MODES_SCR },
    { "PHYMOD_INTERFACE_MODES_HALF_DUPLEX", PHYMOD_INTERFACE_MODES_HALF_DUPLEX },
    { "PHYMOD_INTERFACE_MODES_FIBER", PHYMOD_INTERFACE_MODES_FIBER },
    { "PHYMOD_IF_FLAGS_DONT_TURN_OFF_PLL", PHYMOD_IF_FLAGS_DONT_TURN_OFF_PLL },
    { "PHYMOD_IF_FLAGS_DONT_OVERIDE_FW_MODE", PHYMOD_IF_FLAGS_DONT_OVERIDE_FW_MODE },
    { "PHYMOD_IF_FLAGS_DONT_OVERIDE_TX_PARAMS", PHYMOD_IF_FLAGS_DONT_OVERIDE_TX_PARAMS },
    { "PHYMOD_IF_FLAGS_PLL_DIVIDER_OVERRIDE", PHYMOD_IF_FLAGS_PLL_DIVIDER_OVERRIDE },
    { "PHYMOD_IF_FLAGS_PCS_TABLE_OVERRIDE", PHYMOD_IF_FLAGS_PCS_TABLE_OVERRIDE },
    { "PHYMOD_AN_TECH_ABILITY_1G_KX", PHYMOD_AN_TECH_ABILITY_1G_KX },
    { "PHYMOD_AN_TECH_ABILITY_10G_KX4", PHYMOD_AN_TECH_ABILITY_10G_KX4 },
    { "PHYMOD_AN_TECH_ABILITY_10G_KR", PHYMOD_AN_TECH_ABILITY_10G_KR },
    { "PHYMOD_AN_TECH_ABILITY_40G_KR4", PHYMOD_AN_TECH_ABILITY_40G_KR4 },
    { "PHYMOD_AN_TECH_ABILITY_40G_CR4", PHYMOD_AN_TECH_ABILITY_40G_CR4 },
    { "PHYMOD_AN_TECH_ABILITY_100G_CR10", PHYMOD_AN_TECH_ABILITY_100G_CR10 },
    { "PHYMOD_AN_TECH_ABILITY_100G_CR4", PHYMOD_AN_TECH_ABILITY_100G_CR4 },
    { "PHYMOD_AN_TECH_ABILITY_100G_KR4", PHYMOD_AN_TECH_ABILITY_100G_KR4 },
    { "PHYMOD_BAM_CL73_ABL_20G_KR2", PHYMOD_BAM_CL73_ABL_20G_KR2 },
    { "PHYMOD_BAM_CL73_ABL_20G_CR2", PHYMOD_BAM_CL73_ABL_20G_CR2 },
    { "PHYMOD_BAM_CL73_ABL_40G_KR2", PHYMOD_BAM_CL73_ABL_40G_KR2 },
    { "PHYMOD_BAM_CL73_ABL_40G_CR2", PHYMOD_BAM_CL73_ABL_40G_CR2 },
    { "PHYMOD_BAM_CL73_ABL_50G_KR2", PHYMOD_BAM_CL73_ABL_50G_KR2 },
    { "PHYMOD_BAM_CL73_ABL_50G_CR2", PHYMOD_BAM_CL73_ABL_50G_CR2 },
    { "PHYMOD_BAM_CL73_ABL_50G_KR4", PHYMOD_BAM_CL73_ABL_50G_KR4 },
    { "PHYMOD_BAM_CL73_ABL_50G_CR4", PHYMOD_BAM_CL73_ABL_50G_CR4 },
    { "PHYMOD_BAM_CL73_ABL_20G_KR1", PHYMOD_BAM_CL73_ABL_20G_KR1 },
    { "PHYMOD_BAM_CL73_ABL_20G_CR1", PHYMOD_BAM_CL73_ABL_20G_CR1 },
    { "PHYMOD_BAM_CL73_ABL_25G_KR1", PHYMOD_BAM_CL73_ABL_25G_KR1 },
    { "PHYMOD_BAM_CL73_ABL_25G_CR1", PHYMOD_BAM_CL73_ABL_25G_CR1 },
    { "PHYMOD_BAM_CL37_ABL_2P5G", PHYMOD_BAM_CL37_ABL_2P5G },
    { "PHYMOD_BAM_CL37_ABL_5G_X4", PHYMOD_BAM_CL37_ABL_5G_X4 },
    { "PHYMOD_BAM_CL37_ABL_6G_X4", PHYMOD_BAM_CL37_ABL_6G_X4 },
    { "PHYMOD_BAM_CL37_ABL_10G_HIGIG", PHYMOD_BAM_CL37_ABL_10G_HIGIG },
    { "PHYMOD_BAM_CL37_ABL_10G_CX4", PHYMOD_BAM_CL37_ABL_10G_CX4 },
    { "PHYMOD_BAM_CL37_ABL_12G_X4", PHYMOD_BAM_CL37_ABL_12G_X4 },
    { "PHYMOD_BAM_CL37_ABL_12P5_X4", PHYMOD_BAM_CL37_ABL_12P5_X4 },
    { "PHYMOD_BAM_CL37_ABL_13G_X4", PHYMOD_BAM_CL37_ABL_13G_X4 },
    { "PHYMOD_BAM_CL37_ABL_15G_X4", PHYMOD_BAM_CL37_ABL_15G_X4 },
    { "PHYMOD_BAM_CL37_ABL_16G_X4", PHYMOD_BAM_CL37_ABL_16G_X4 },
    { "PHYMOD_BAM_CL37_ABL_20G_X4_CX4", PHYMOD_BAM_CL37_ABL_20G_X4_CX4 },
    { "PHYMOD_BAM_CL37_ABL_20G_X4", PHYMOD_BAM_CL37_ABL_20G_X4 },
    { "PHYMOD_BAM_CL37_ABL_21G_X4", PHYMOD_BAM_CL37_ABL_21G_X4 },
    { "PHYMOD_BAM_CL37_ABL_25P455G", PHYMOD_BAM_CL37_ABL_25P455G },
    { "PHYMOD_BAM_CL37_ABL_31P5G", PHYMOD_BAM_CL37_ABL_31P5G },
    { "PHYMOD_BAM_CL37_ABL_32P7G", PHYMOD_BAM_CL37_ABL_32P7G },
    { "PHYMOD_BAM_CL37_ABL_40G", PHYMOD_BAM_CL37_ABL_40G },
    { "PHYMOD_BAM_CL37_ABL_10G_X2_CX4", PHYMOD_BAM_CL37_ABL_10G_X2_CX4 },
    { "PHYMOD_BAM_CL37_ABL_10G_DXGXS", PHYMOD_BAM_CL37_ABL_10G_DXGXS },
    { "PHYMOD_BAM_CL37_ABL_10P5G_DXGXS", PHYMOD_BAM_CL37_ABL_10P5G_DXGXS },
    { "PHYMOD_BAM_CL37_ABL_12P7_DXGXS", PHYMOD_BAM_CL37_ABL_12P7_DXGXS },
    { "PHYMOD_BAM_CL37_ABL_15P75G_R2", PHYMOD_BAM_CL37_ABL_15P75G_R2 },
    { "PHYMOD_BAM_CL37_ABL_20G_X2_CX4", PHYMOD_BAM_CL37_ABL_20G_X2_CX4 },
    { "PHYMOD_BAM_CL37_ABL_20G_X2", PHYMOD_BAM_CL37_ABL_20G_X2 },
    { "PHYMOD_AN_CAPABILITIES_CL37", PHYMOD_AN_CAPABILITIES_CL37 },
    { "PHYMOD_AN_CAPABILITIES_CL73", PHYMOD_AN_CAPABILITIES_CL73 },
    { "PHYMOD_AN_CAPABILITIES_CL37BAM", PHYMOD_AN_CAPABILITIES_CL37BAM },
    { "PHYMOD_AN_CAPABILITIES_CL73BAM", PHYMOD_AN_CAPABILITIES_CL73BAM },
    { "PHYMOD_AN_CAPABILITIES_HPAM", PHYMOD_AN_CAPABILITIES_HPAM },
    { "PHYMOD_AN_CAPABILITIES_SGMII", PHYMOD_AN_CAPABILITIES_SGMII },
    { "PHYMOD_AN_CAPABILITIES_SYMM_PAUSE", PHYMOD_AN_CAPABILITIES_SYMM_PAUSE },
    { "PHYMOD_AN_CAPABILITIES_ASYM_PAUSE", PHYMOD_AN_CAPABILITIES_ASYM_PAUSE },
    { "PHYMOD_AN_FLAGS_ALLOW_PLL_CHANGE", PHYMOD_AN_FLAGS_ALLOW_PLL_CHANGE },
    { NULL }
};


/* Typedefs section */
static cint_parameter_desc_t __cint_typedefs[] =
{
    { NULL }
};


cint_data_t phymod_cint_data =
{    
    NULL,
    __cint_functions,
    __cint_structures,
    __cint_enums,
    __cint_typedefs,
    __cint_constants,
    __cint_function_pointers,
};


#endif /* defined(PHYMOD_SUPPORT) */

#endif /* defined(INCLUDE_LIB_CINT) */
