/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * File:        allmems_x.i
 * Purpose:     Independent memory descriptions.
 */

#if defined(BCM_56840_A0)
    { /* SOC_MEM_INT_XLPORT_WC_UCMEM_DATAm */ 
        /* mem            XLPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 4095,
        /* minblock    */ 9,
        /* maxblock    */ 26,
        /* blocks      */ 0x7fffe00,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_XLPORT_WC_UCMEM_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_2801PM_A0)
    { /* SOC_MEM_INT_XLPORT_WC_UCMEM_DATA_BCM2801PM_A0m */ 
        /* mem            XLPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 2047,
        /* minblock    */ 0,
        /* maxblock    */ 0,
        /* blocks      */ 0x1,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_CLPORT_WC_UCMEM_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_53400_A0)
    { /* SOC_MEM_INT_XLPORT_WC_UCMEM_DATA_BCM53400_A0m */ 
        /* mem            XLPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 2047,
        /* minblock    */ 12,
        /* maxblock    */ 17,
        /* blocks      */ 0x3f000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_XLPORT_WC_UCMEM_DATA_BCM53400_A0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56150_A0)
    { /* SOC_MEM_INT_XLPORT_WC_UCMEM_DATA_BCM56150_A0m */ 
        /* mem            XLPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 2047,
        /* minblock    */ 11,
        /* maxblock    */ 12,
        /* blocks      */ 0x1800,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_PORT_WC_UCMEM_DATA_BCM88030_A0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56840_B0)
    { /* SOC_MEM_INT_XLPORT_WC_UCMEM_DATA_BCM56840_B0m */ 
        /* mem            XLPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 4095,
        /* minblock    */ 9,
        /* maxblock    */ 28,
        /* blocks      */ 0x1ffffe00,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_XLPORT_WC_UCMEM_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56850_A0)
    { /* SOC_MEM_INT_XLPORT_WC_UCMEM_DATA_BCM56850_A0m */ 
        /* mem            XLPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 2047,
        /* minblock    */ 23,
        /* maxblock    */ 54,
        /* blocks      */ 0xff800000,
        /* blocks_hi   */ 0x7fffff,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_PORT_WC_UCMEM_DATA_BCM88030_A0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88670_A0)
    { /* SOC_MEM_INT_XLPORT_WC_UCMEM_DATA_BCM88670_A0m */ 
        /* mem            XLPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 2047,
        /* minblock    */ 119,
        /* maxblock    */ 125,
        /* blocks      */ 0,
        /* blocks_hi   */ 0xffffffff,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_CLPORT_WC_UCMEM_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88732_A0)
    { /* SOC_MEM_INT_XLPORT_WC_UCMEM_DATA_BCM88732_A0m */ 
        /* mem            XLPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 4095,
        /* minblock    */ 11,
        /* maxblock    */ 16,
        /* blocks      */ 0x1f800,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_XLPORT_WC_UCMEM_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56634_A0) || defined(BCM_56634_B0)
    { /* SOC_MEM_INT_XPORT_EHG_RX_TUNNEL_DATAm */ 
        /* mem            XPORT_EHG_RX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 5,
        /* maxblock    */ 8,
        /* blocks      */ 0x1e0,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56524_A0) || defined(BCM_56524_B0)
    { /* SOC_MEM_INT_XPORT_EHG_RX_TUNNEL_DATA_BCM56524_A0m */ 
        /* mem            XPORT_EHG_RX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 4,
        /* maxblock    */ 7,
        /* blocks      */ 0xf0,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56685_A0) || defined(BCM_56685_B0)
    { /* SOC_MEM_INT_XPORT_EHG_RX_TUNNEL_DATA_BCM56685_A0m */ 
        /* mem            XPORT_EHG_RX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 2,
        /* maxblock    */ 5,
        /* blocks      */ 0x3c,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_XPORT_EHG_RX_TUNNEL_DATA_BCM88230_A0m */ 
        /* mem            XPORT_EHG_RX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 19,
        /* maxblock    */ 19,
        /* blocks      */ 0x80000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_XPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56634_A0) || defined(BCM_56634_B0)
    { /* SOC_MEM_INT_XPORT_EHG_RX_TUNNEL_MASKm */ 
        /* mem            XPORT_EHG_RX_TUNNEL_MASKm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 5,
        /* maxblock    */ 8,
        /* blocks      */ 0x1e0,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000100,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_MASKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56524_A0) || defined(BCM_56524_B0)
    { /* SOC_MEM_INT_XPORT_EHG_RX_TUNNEL_MASK_BCM56524_A0m */ 
        /* mem            XPORT_EHG_RX_TUNNEL_MASKm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 4,
        /* maxblock    */ 7,
        /* blocks      */ 0xf0,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000100,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_MASKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56685_A0) || defined(BCM_56685_B0)
    { /* SOC_MEM_INT_XPORT_EHG_RX_TUNNEL_MASK_BCM56685_A0m */ 
        /* mem            XPORT_EHG_RX_TUNNEL_MASKm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 2,
        /* maxblock    */ 5,
        /* blocks      */ 0x3c,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000100,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_MASKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_XPORT_EHG_RX_TUNNEL_MASK_BCM88230_A0m */ 
        /* mem            XPORT_EHG_RX_TUNNEL_MASKm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 19,
        /* maxblock    */ 19,
        /* blocks      */ 0x80000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000100,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_XPORT_EHG_RX_TUNNEL_MASKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56634_A0) || defined(BCM_56634_B0)
    { /* SOC_MEM_INT_XPORT_EHG_TX_TUNNEL_DATAm */ 
        /* mem            XPORT_EHG_TX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 5,
        /* maxblock    */ 8,
        /* blocks      */ 0x1e0,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000200,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56524_A0) || defined(BCM_56524_B0)
    { /* SOC_MEM_INT_XPORT_EHG_TX_TUNNEL_DATA_BCM56524_A0m */ 
        /* mem            XPORT_EHG_TX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 4,
        /* maxblock    */ 7,
        /* blocks      */ 0xf0,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000200,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56685_A0) || defined(BCM_56685_B0)
    { /* SOC_MEM_INT_XPORT_EHG_TX_TUNNEL_DATA_BCM56685_A0m */ 
        /* mem            XPORT_EHG_TX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 2,
        /* maxblock    */ 5,
        /* blocks      */ 0x3c,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000200,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_SPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_XPORT_EHG_TX_TUNNEL_DATA_BCM88230_A0m */ 
        /* mem            XPORT_EHG_TX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 19,
        /* maxblock    */ 19,
        /* blocks      */ 0x80000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000200,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_XPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56440_A0) || defined(BCM_56440_B0)
    { /* SOC_MEM_INT_XPORT_WC_UCMEM_DATAm */ 
        /* mem            XPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 4095,
        /* minblock    */ 12,
        /* maxblock    */ 15,
        /* blocks      */ 0xf000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_XLPORT_WC_UCMEM_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56450_A0) || defined(BCM_56450_B0)
    { /* SOC_MEM_INT_XPORT_WC_UCMEM_DATA_BCM56450_A0m */ 
        /* mem            XPORT_WC_UCMEM_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 2047,
        /* minblock    */ 12,
        /* maxblock    */ 22,
        /* blocks      */ 0x7ff000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 16,
        /* nFields     */ 1,
        /* *fields     */ soc_PORT_WC_UCMEM_DATA_BCM88030_A0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56634_A0) || defined(BCM_56634_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_RX_TUNNEL_DATAm */ 
        /* mem            XQPORT_EHG_RX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 12,
        /* maxblock    */ 17,
        /* blocks      */ 0x3f000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56334_A0) || defined(BCM_56334_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_RX_TUNNEL_DATA_BCM56334_A0m */ 
        /* mem            XQPORT_EHG_RX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 7,
        /* maxblock    */ 10,
        /* blocks      */ 0x780,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56524_A0) || defined(BCM_56524_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_RX_TUNNEL_DATA_BCM56524_A0m */ 
        /* mem            XQPORT_EHG_RX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 11,
        /* maxblock    */ 16,
        /* blocks      */ 0x1f800,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56685_A0) || defined(BCM_56685_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_RX_TUNNEL_DATA_BCM56685_A0m */ 
        /* mem            XQPORT_EHG_RX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 9,
        /* maxblock    */ 14,
        /* blocks      */ 0x7e00,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56634_A0) || defined(BCM_56634_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_RX_TUNNEL_MASKm */ 
        /* mem            XQPORT_EHG_RX_TUNNEL_MASKm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 12,
        /* maxblock    */ 17,
        /* blocks      */ 0x3f000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000100,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_MASKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56334_A0) || defined(BCM_56334_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_RX_TUNNEL_MASK_BCM56334_A0m */ 
        /* mem            XQPORT_EHG_RX_TUNNEL_MASKm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 7,
        /* maxblock    */ 10,
        /* blocks      */ 0x780,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000100,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_MASKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56524_A0) || defined(BCM_56524_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_RX_TUNNEL_MASK_BCM56524_A0m */ 
        /* mem            XQPORT_EHG_RX_TUNNEL_MASKm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 11,
        /* maxblock    */ 16,
        /* blocks      */ 0x1f800,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000100,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_MASKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56685_A0) || defined(BCM_56685_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_RX_TUNNEL_MASK_BCM56685_A0m */ 
        /* mem            XQPORT_EHG_RX_TUNNEL_MASKm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 9,
        /* maxblock    */ 14,
        /* blocks      */ 0x7e00,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000100,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_MASKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56634_A0) || defined(BCM_56634_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_TX_TUNNEL_DATAm */ 
        /* mem            XQPORT_EHG_TX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 12,
        /* maxblock    */ 17,
        /* blocks      */ 0x3f000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000200,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56334_A0) || defined(BCM_56334_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_TX_TUNNEL_DATA_BCM56334_A0m */ 
        /* mem            XQPORT_EHG_TX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 7,
        /* maxblock    */ 10,
        /* blocks      */ 0x780,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000200,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56524_A0) || defined(BCM_56524_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_TX_TUNNEL_DATA_BCM56524_A0m */ 
        /* mem            XQPORT_EHG_TX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 11,
        /* maxblock    */ 16,
        /* blocks      */ 0x1f800,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000200,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56685_A0) || defined(BCM_56685_B0)
    { /* SOC_MEM_INT_XQPORT_EHG_TX_TUNNEL_DATA_BCM56685_A0m */ 
        /* mem            XQPORT_EHG_TX_TUNNEL_DATAm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE |
                          SOC_MEM_FLAG_SER_ECC_CORRECTABLE,     /* 0x122 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 9,
        /* maxblock    */ 14,
        /* blocks      */ 0x7e00,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000200,
        /* gran        */ 1,
        /* bytes       */ 18,
        /* nFields     */ 4,
        /* *fields     */ soc_GPORT_EHG_RX_TUNNEL_DATAm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_56725_A0) || defined(BCM_56820_A0)
    { /* SOC_MEM_INT_X_ARB_TDM_TABLEm */ 
        /* mem            X_ARB_TDM_TABLEm */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 4,
        /* maxblock    */ 4,
        /* blocks      */ 0x10,
        /* blocks_hi   */ 0,
        /* base        */ 0x06000000,
        /* gran        */ 1,
        /* bytes       */ 1,
        /* nFields     */ 2,
        /* *fields     */ soc_X_ARB_TDM_TABLEm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

