/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * File:        allmems_q.i
 * Purpose:     Independent memory descriptions.
 */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QBUFFSPROFILEm */ 
        /* mem            QBUFFSPROFILEm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 65535,
        /* minblock    */ 27,
        /* maxblock    */ 27,
        /* blocks      */ 0x8000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 4,
        /* *fields     */ soc_QBUFFSPROFILEm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QDEPTH_THRESH0m */ 
        /* mem            QDEPTH_THRESH0m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 8191,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x06000000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 6,
        /* *fields     */ soc_QDEPTH_THRESH0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QDEPTH_THRESH1m */ 
        /* mem            QDEPTH_THRESH1m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 8191,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x05000000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 6,
        /* *fields     */ soc_QDEPTH_THRESH1m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QDESCm */ 
        /* mem            QDESCm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 32767,
        /* minblock    */ 23,
        /* maxblock    */ 23,
        /* blocks      */ 0x800000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00050000,
        /* gran        */ 1,
        /* bytes       */ 4,
        /* nFields     */ 7,
        /* *fields     */ soc_QDESCm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QDRDLLMEMm */ 
        /* mem            QDRDLLMEMm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 55,
        /* maxblock    */ 55,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x800000,
        /* base        */ 0x20000000,
        /* gran        */ 1,
        /* bytes       */ 4,
        /* nFields     */ 1,
        /* *fields     */ soc_QDRDLLMEMm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QDRMEMm */ 
        /* mem            QDRMEMm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 4194303,
        /* minblock    */ 55,
        /* maxblock    */ 55,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x800000,
        /* base        */ 0x10000000,
        /* gran        */ 1,
        /* bytes       */ 4,
        /* nFields     */ 1,
        /* *fields     */ soc_QDRMEMm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88732_A0)
    { /* SOC_MEM_INT_QL_TABLE0m */ 
        /* mem            QL_TABLE0m */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 5,
        /* maxblock    */ 5,
        /* blocks      */ 0x20,
        /* blocks_hi   */ 0,
        /* base        */ 0x06080000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 1,
        /* *fields     */ soc_QL_TABLE0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88732_A0)
    { /* SOC_MEM_INT_QL_TABLE1m */ 
        /* mem            QL_TABLE1m */
        /* flags       */ SOC_MEM_FLAG_VALID |
                          SOC_MEM_FLAG_CACHABLE,        /* 0x22 */
        /* cmp_fn      */ _soc_mem_cmp_undef,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 5,
        /* maxblock    */ 5,
        /* blocks      */ 0x20,
        /* blocks_hi   */ 0,
        /* base        */ 0x06090000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 1,
        /* *fields     */ soc_QL_TABLE0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QMm */ 
        /* mem            QMm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 639,
        /* minblock    */ 14,
        /* maxblock    */ 14,
        /* blocks      */ 0x4000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00220000,
        /* gran        */ 1,
        /* bytes       */ 8,
        /* nFields     */ 9,
        /* *fields     */ soc_QMm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_ALLOCATION_WATERMARKm */ 
        /* mem            QM_ALLOCATION_WATERMARKm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00060000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 2,
        /* *fields     */ soc_QM_ALLOCATION_WATERMARKm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_BUFFER_STATE0m */ 
        /* mem            QM_BUFFER_STATE0m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00070000,
        /* gran        */ 1,
        /* bytes       */ 5,
        /* nFields     */ 8,
        /* *fields     */ soc_QM_BUFFER_STATE0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_BUFFER_STATE2m */ 
        /* mem            QM_BUFFER_STATE2m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x000a0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 5,
        /* *fields     */ soc_QM_BUFFER_STATE2m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_BUFFER_STATE3m */ 
        /* mem            QM_BUFFER_STATE3m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x000b0000,
        /* gran        */ 1,
        /* bytes       */ 6,
        /* nFields     */ 6,
        /* *fields     */ soc_QM_BUFFER_STATE3m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_BUFFER_STATE_AGEm */ 
        /* mem            QM_BUFFER_STATE_AGEm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x000c0000,
        /* gran        */ 1,
        /* bytes       */ 1,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_BUFFER_STATE_AGEm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_DEQUEUE_CONTEXT0m */ 
        /* mem            QM_DEQUEUE_CONTEXT0m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x001e0000,
        /* gran        */ 1,
        /* bytes       */ 6,
        /* nFields     */ 11,
        /* *fields     */ soc_QM_DEQUEUE_CONTEXT0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_DEQUEUE_CONTEXT1m */ 
        /* mem            QM_DEQUEUE_CONTEXT1m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x001f0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_DEQUEUE_CONTEXT1m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_DEST_QUEUE_HEADPTRm */ 
        /* mem            QM_DEST_QUEUE_HEADPTRm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00050000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_DEST_QUEUE_HEADPTRm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_DEST_QUEUE_STATEm */ 
        /* mem            QM_DEST_QUEUE_STATEm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00040000,
        /* gran        */ 1,
        /* bytes       */ 8,
        /* nFields     */ 8,
        /* *fields     */ soc_QM_DEST_QUEUE_STATEm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_DQ_NEXT_BUFFERm */ 
        /* mem            QM_DQ_NEXT_BUFFERm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x000e0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_DQ_NEXT_BUFFERm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_EGRESS_BUFFER_STATE1m */ 
        /* mem            QM_EGRESS_BUFFER_STATE1m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00090000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 5,
        /* *fields     */ soc_QM_EGRESS_BUFFER_STATE1m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_FREE_PAGE_FIFO0m */ 
        /* mem            QM_FREE_PAGE_FIFO0m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 3327,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00190000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_FREE_PAGE_FIFO0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_FREE_PAGE_FIFO1m */ 
        /* mem            QM_FREE_PAGE_FIFO1m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 3327,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x001a0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_FREE_PAGE_FIFO0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_FREE_PAGE_FIFO2m */ 
        /* mem            QM_FREE_PAGE_FIFO2m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 3327,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x001b0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_FREE_PAGE_FIFO0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_FREE_PAGE_FIFO3m */ 
        /* mem            QM_FREE_PAGE_FIFO3m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 3327,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x001c0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_FREE_PAGE_FIFO0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_FREE_PAGE_FIFO4m */ 
        /* mem            QM_FREE_PAGE_FIFO4m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 3327,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x001d0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_FREE_PAGE_FIFO0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_INGRESS_BUFFER_STATE1m */ 
        /* mem            QM_INGRESS_BUFFER_STATE1m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00080000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 5,
        /* *fields     */ soc_QM_EGRESS_BUFFER_STATE1m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_NEXT_PAGEm */ 
        /* mem            QM_NEXT_PAGEm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00150000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_DEQUEUE_CONTEXT1m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_PAGE_ROTATIONm */ 
        /* mem            QM_PAGE_ROTATIONm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00160000,
        /* gran        */ 1,
        /* bytes       */ 1,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_PAGE_ROTATIONm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_REPLICATION_CONTEXTm */ 
        /* mem            QM_REPLICATION_CONTEXTm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00130000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 6,
        /* *fields     */ soc_QM_REPLICATION_CONTEXTm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_REPLICATION_DEREFm */ 
        /* mem            QM_REPLICATION_DEREFm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00110000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_REPLICATION_DEREFm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_REPLICATION_LRP_STATEm */ 
        /* mem            QM_REPLICATION_LRP_STATEm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00120000,
        /* gran        */ 1,
        /* bytes       */ 6,
        /* nFields     */ 5,
        /* *fields     */ soc_QM_REPLICATION_LRP_STATEm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_REPLICATION_REFm */ 
        /* mem            QM_REPLICATION_REFm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00100000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_REPLICATION_REFm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_REPLICATION_REP_COPYm */ 
        /* mem            QM_REPLICATION_REP_COPYm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x000f0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_REPLICATION_REP_COPYm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_SCOREBOARD0m */ 
        /* mem            QM_SCOREBOARD0m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 511,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00170000,
        /* gran        */ 1,
        /* bytes       */ 6,
        /* nFields     */ 7,
        /* *fields     */ soc_QM_SCOREBOARD0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_SCOREBOARD1m */ 
        /* mem            QM_SCOREBOARD1m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 511,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00180000,
        /* gran        */ 1,
        /* bytes       */ 6,
        /* nFields     */ 7,
        /* *fields     */ soc_QM_SCOREBOARD0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_SOURCE_QUEUEm */ 
        /* mem            QM_SOURCE_QUEUEm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00140000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 5,
        /* *fields     */ soc_QM_SOURCE_QUEUEm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_SOURCE_QUEUE_CONFIGm */ 
        /* mem            QM_SOURCE_QUEUE_CONFIGm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00000000,
        /* gran        */ 1,
        /* bytes       */ 12,
        /* nFields     */ 10,
        /* *fields     */ soc_QM_SOURCE_QUEUE_CONFIGm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_SOURCE_QUEUE_HEADPTRm */ 
        /* mem            QM_SOURCE_QUEUE_HEADPTRm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00030000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_DEST_QUEUE_HEADPTRm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_SOURCE_QUEUE_STATE0m */ 
        /* mem            QM_SOURCE_QUEUE_STATE0m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00010000,
        /* gran        */ 1,
        /* bytes       */ 6,
        /* nFields     */ 7,
        /* *fields     */ soc_QM_SOURCE_QUEUE_STATE0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_SOURCE_QUEUE_STATE1m */ 
        /* mem            QM_SOURCE_QUEUE_STATE1m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 127,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x00020000,
        /* gran        */ 1,
        /* bytes       */ 6,
        /* nFields     */ 10,
        /* *fields     */ soc_QM_SOURCE_QUEUE_STATE1m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88030_A0) || defined(BCM_88030_A1) || \
    defined(BCM_88030_B0)
    { /* SOC_MEM_INT_QM_SQ_NEXT_BUFFERm */ 
        /* mem            QM_SQ_NEXT_BUFFERm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 37,
        /* maxblock    */ 37,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x20,
        /* base        */ 0x000d0000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QM_DQ_NEXT_BUFFERm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QPRISELm */ 
        /* mem            QPRISELm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 511,
        /* minblock    */ 23,
        /* maxblock    */ 23,
        /* blocks      */ 0x800000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00020000,
        /* gran        */ 1,
        /* bytes       */ 1,
        /* nFields     */ 1,
        /* *fields     */ soc_QPRISELm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QSMm */ 
        /* mem            QSMm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 511,
        /* minblock    */ 14,
        /* maxblock    */ 14,
        /* blocks      */ 0x4000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00230000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 1,
        /* *fields     */ soc_QSMm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QSZm */ 
        /* mem            QSZm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 32767,
        /* minblock    */ 23,
        /* maxblock    */ 23,
        /* blocks      */ 0x800000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00058000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 3,
        /* *fields     */ soc_QSZm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QSZTHm */ 
        /* mem            QSZTHm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 15,
        /* minblock    */ 23,
        /* maxblock    */ 23,
        /* blocks      */ 0x800000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00030000,
        /* gran        */ 1,
        /* bytes       */ 5,
        /* nFields     */ 5,
        /* *fields     */ soc_QSZTHm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_QTYPEm */ 
        /* mem            QTYPEm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 32767,
        /* minblock    */ 23,
        /* maxblock    */ 23,
        /* blocks      */ 0x800000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00018000,
        /* gran        */ 1,
        /* bytes       */ 1,
        /* nFields     */ 1,
        /* *fields     */ soc_QTYPEm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_MAPm */ 
        /* mem            QUEUE_MAPm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 65535,
        /* minblock    */ 32,
        /* maxblock    */ 32,
        /* blocks      */ 0,
        /* blocks_hi   */ 0x1,
        /* base        */ 0x0b000000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 4,
        /* *fields     */ soc_QUEUE_MAPm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_PARAMETER_HIm */ 
        /* mem            QUEUE_PARAMETER_HIm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 32767,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x03000000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 4,
        /* *fields     */ soc_QUEUE_PARAMETER_HIm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_PARAMETER_LOm */ 
        /* mem            QUEUE_PARAMETER_LOm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 32767,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x04000000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 4,
        /* *fields     */ soc_QUEUE_PARAMETER_LOm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_STATE_HIm */ 
        /* mem            QUEUE_STATE_HIm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 32767,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x01000000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 4,
        /* *fields     */ soc_QUEUE_STATE_HIm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_STATE_LOm */ 
        /* mem            QUEUE_STATE_LOm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 32767,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x02000000,
        /* gran        */ 1,
        /* bytes       */ 2,
        /* nFields     */ 4,
        /* *fields     */ soc_QUEUE_STATE_LOm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_TO_SC_0m */ 
        /* mem            QUEUE_TO_SC_0m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x0a000000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 5,
        /* *fields     */ soc_QUEUE_TO_SC_0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_TO_SC_1m */ 
        /* mem            QUEUE_TO_SC_1m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x09000000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 5,
        /* *fields     */ soc_QUEUE_TO_SC_1m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_TO_SC_2m */ 
        /* mem            QUEUE_TO_SC_2m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x08000000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 5,
        /* *fields     */ soc_QUEUE_TO_SC_2m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_QUEUE_TO_SC_3m */ 
        /* mem            QUEUE_TO_SC_3m */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 16383,
        /* minblock    */ 30,
        /* maxblock    */ 30,
        /* blocks      */ 0x40000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x07000000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 5,
        /* *fields     */ soc_QUEUE_TO_SC_3m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0) || defined(BCM_88230_B0) || \
    defined(BCM_88230_C0)
    { /* SOC_MEM_INT_Q_MAX_BUFFSm */ 
        /* mem            Q_MAX_BUFFSm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 511,
        /* minblock    */ 27,
        /* maxblock    */ 27,
        /* blocks      */ 0x8000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x01000000,
        /* gran        */ 1,
        /* bytes       */ 4,
        /* nFields     */ 4,
        /* *fields     */ soc_Q_MAX_BUFFSm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_A0)
    { /* SOC_MEM_INT_Q_MIN_BUFFSm */ 
        /* mem            Q_MIN_BUFFSm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 511,
        /* minblock    */ 27,
        /* maxblock    */ 27,
        /* blocks      */ 0x8000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x02000000,
        /* gran        */ 1,
        /* bytes       */ 3,
        /* nFields     */ 3,
        /* *fields     */ soc_Q_MIN_BUFFSm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_B0)
    { /* SOC_MEM_INT_Q_MIN_BUFFS_BCM88230_B0m */ 
        /* mem            Q_MIN_BUFFSm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 511,
        /* minblock    */ 27,
        /* maxblock    */ 27,
        /* blocks      */ 0x8000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x02000000,
        /* gran        */ 1,
        /* bytes       */ 4,
        /* nFields     */ 4,
        /* *fields     */ soc_Q_MIN_BUFFS_BCM88230_B0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88230_C0)
    { /* SOC_MEM_INT_Q_MIN_BUFFS_BCM88230_C0m */ 
        /* mem            Q_MIN_BUFFSm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ _soc_mem_entry_null_zeroes,
        /* index_min   */ 0,
        /* index_max   */ 511,
        /* minblock    */ 27,
        /* maxblock    */ 27,
        /* blocks      */ 0x8000000,
        /* blocks_hi   */ 0,
        /* base        */ 0x02000000,
        /* gran        */ 1,
        /* bytes       */ 4,
        /* nFields     */ 5,
        /* *fields     */ soc_Q_MIN_BUFFS_BCM88230_C0m_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

#if defined(BCM_88640_A0)
    { /* SOC_MEM_INT_Q_PRIORITY_BIT_MAPm */ 
        /* mem            Q_PRIORITY_BIT_MAPm */
        /* flags       */ SOC_MEM_FLAG_VALID,   /* 0x2 */
        /* cmp_fn      */ NULL,
        /* *null_entry */ NULL,
        /* index_min   */ 0,
        /* index_max   */ 3,
        /* minblock    */ 23,
        /* maxblock    */ 23,
        /* blocks      */ 0x800000,
        /* blocks_hi   */ 0,
        /* base        */ 0x00028000,
        /* gran        */ 1,
        /* bytes       */ 8,
        /* nFields     */ 1,
        /* *fields     */ soc_Q_PRIORITY_BIT_MAPm_fields,
        /* *views      */ NULL,
        /* snoop_cb    */ NULL, 
        /* snoop_user_data */ NULL, 
        /* snoop_flags */ 0,
    },
#endif /* chips */

