/*
 * $Id: wcmod_phyreg.h 1.2 Broadcom SDK $
 *
 * $Copyright: Copyright 2012 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 */
#include <sal/types.h>
/* FILE: wcmod_phyreg.h */
/* DATE: Mon Jun 13 10:28:56 PDT 2011 */


/*!
\file wcmod_phyreg.h Declares verilog interface functions.
This file contains declarations of functions that are necessary to 
hook up WCMod to various verilog platforms. The drivers of WCMod are
hooked to verilog tasks as a first level interface to the actual drivers in the 
verilog testbench. These 'C' functions and verilog tasks are attached via 
a mechanism called 'DPI' (direct programming interface) supported by all
verilog simulators.  Note that C platforms need no special attachments.
*/

#ifndef   _WCMOD_PHYREG_H_
#define   _WCMOD_PHYREG_H_

#include "wcmod_main.h"  
#include "wcmod_defines.h"

#if defined (_MDK_WCMOD_)
extern int cdk_xgs_miim_read(int u, uint32_t pa, uint32_t ra, uint32_t *val);
extern int cdk_xgs_miim_write(int u, uint32_t pa, uint32_t ra, uint32_t val);

#endif

#ifndef __KERNEL__
#if defined (_DV_TRIUMPH3) || (_DV_ODYSSEY) || (_DV_NATIVE)
/* normally the externs are generated by irun/vcs -dpiheader. */
/* Manually typing this in to reduce header files. */
#ifdef CADENCE
/* svdpi.h to be conditional to cadence (or irun). vcs does not have this. */
#include "svdpi.h"
#endif /* CADENCE */

extern void dv_reg_cl45_read  (int ut,int pt,int pa,int ln,int ad,int *dt);
extern void dv_reg_cl22_read  (int ut,int pt,int pa,int ln,int ad,int *dt);

extern void dv_reg_cl45_write (int ut,int pt,int pa,int ln,int ad,int dt);
extern void dv_reg_cl22_write (int ut,int pt,int pa,int ln,int ad,int dt);

extern void dv_reg_cl45_modify(int ut,int pt,int pa,int ln,int ad,int dt,int m);
extern void dv_reg_cl22_modify(int ut,int pt,int pa,int ln,int ad,int dt,int m);

extern void dv_wait (int delay);

extern void dv_slam_read_reg  (void *pi,  int a, int *d);
extern void dv_slam_write_reg (void *pi, int addr, int d);
extern void dv_slam_modify_reg(void *pi,int a,int d,int m);

#endif /* triumph + odyssey + native */
#endif

extern int  wcmod_reg_aer_read  (uint32 u,wcmod_st* w,uint32 a,uint16 *d);
extern int  wcmod_reg_aer_write (uint32 u,wcmod_st* w,uint32 a,uint16  d);
extern int  wcmod_reg_aer_modify(uint32 u,wcmod_st* w,uint32 a,uint16 d,uint16 m);

extern int  wcmod_cl22_read  (wcmod_st* ws,uint32 addr,uint16 *data);
extern int  wcmod_cl22_write (wcmod_st* ws,uint32 addr,uint16 data);
extern int  wcmod_cl45_read  (wcmod_st* ws,uint32 addr,uint16 *data);
extern int  wcmod_cl45_write (wcmod_st* ws,uint32 addr,uint16 data);
extern void wcmod_timeout_init(soc_timeout_t *to, uint32 usec, int min_polls);  
extern int  wcmod_timeout_check(soc_timeout_t *to);  
extern int  wcmod_regbit_set_wait_check(wcmod_st* w,int r,int b,int bt,int to); 
#endif   /*  _WCMOD_PHYREG_H_ */
